### PR TITLE
Remove temporary `.lock` files unintentionally left around by gem installer

### LINKED ISSUE #7997: Shouldnt lock files be removed again after the file is handled?
with the upgrade to 3.3.5 i noticed that our gem based rpms started failing with extra installed files. which i tracked down to:

[ce8bcba90f5bdaae652165f8e680c2b3abecea7c](https://github.com/rubygems/rubygems/commit/ce8bcba90f5bdaae652165f8e680c2b3abecea7c)
[d99a80e62d75ccdc5ada8202d9b9e28bd97f1974](https://github.com/rubygems/rubygems/commit/d99a80e62d75ccdc5ada8202d9b9e28bd97f1974)

Shouldnt the lock file be cleaned up again after changing the file is done?

### PR DESCRIPTION
**Pull request by nobu**
## What was the end-user or developer problem that led to this PR?

_Originally posted by @sunpoet in https://github.com/rubygems/rubygems/issues/7806#issuecomment-2241662488_
> IIUC, the lock files were created to avoid the breakage while modifying the conflicting binstub from mutliple gems. If so, could you please consider removing the lock files when the operation is done.
> 
> ```
> % ls -l bin/
> total 1
> -rwxr-xr-x  1 sunpoet wheel 568 Jul 21 20:00 bundle
> -rw-r--r--  1 sunpoet wheel   0 Jul 21 20:00 bundle.lock
> -rwxr-xr-x  1 sunpoet wheel 570 Jul 21 20:00 bundler
> -rw-r--r--  1 sunpoet wheel   0 Jul 21 20:00 bundler.lock
> ```

## What is your fix for the problem, implemented in this PR?

Remove lock files at the end of locking.

Fixes #7997.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: lib/rubygems/installer.rb [hunk 1]
```diff
@@ -538,14 +538,15 @@ def generate_plugins # :nodoc:
...
-    Gem.open_file_with_flock("#{bin_script_path}.lock") do
+    Gem.open_file_with_flock("#{bin_script_path}.lock") do |lock|
       require "fileutils"
       FileUtils.rm_f bin_script_path # prior install may have been --no-wrappers
 
       File.open(bin_script_path, "wb", 0o755) do |file|
         file.write app_script_text(filename)
         file.chmod(options[:prog_mode] || 0o755)
       end
+      File.unlink(lock.path)
```
Comment (segiddins) [inline lib/rubygems/installer.rb:549]: Should this go in an ensure in `open_file_with_flock` ?

Comment (nobu) [reply lib/rubygems/installer.rb:549]: Good catch!

Comment (nobu) [reply lib/rubygems/installer.rb:549]: Not only the lock file, the executable script seems left, after an error occurred.
This should be removed as well, and windows .bat files?

**Comment by nobu** [comment]
Hmmm, I can't reproduce a failure on TruffleRuby locally.

**Comment by deivid-rodriguez** [comment]
Just to make sure, you built this PR on top of https://github.com/rubygems/rubygems/pull/7931, so your intention is to get https://github.com/rubygems/rubygems/pull/7931 landed first. Is that correct, @nobu? If that's the case, I have a question about the Solaris specific code, other than that seems fine!

**Comment by voxik** [comment]
Just FTR, we have just hist this issue during preparation of update for Fedora:

https://src.fedoraproject.org/rpms/ruby/pull-request/190#comment-217215

We are going to apply this PR including #7931 to fix this issue, otherwise it would break all our rubygem packages which installs executable

File: test/rubygems/test_gem_installer.rb [hunk 2]
```diff
@@ -1222,6 +1230,35 @@ def test_install_creates_binstub_that_dont_trust_encoding
...
+        raise Gem::Ext::BuildError if path.end_with?("/executable")
+      end
+    end
+
+    assert_raise(Gem::Ext::BuildError) do
+      installer.install
+    end
+
+    assert_path_not_exist(File.join(installer.bin_dir, "executable.lock"))
+    # assert_path_not_exist(File.join(installer.bin_dir, "executable"))
```
Comment (deivid-rodriguez) [inline test/rubygems/test_gem_installer.rb:1255]: Did you mean to uncomment this? or is it not passing and you left it there as a TODO? If the latter, can you add a comment on top of it explaining it?

Comment (nobu) [reply test/rubygems/test_gem_installer.rb:1255]: I had to confirm it because I was uncertain if executables would be removed or left when an installer failed in middle.
Currently it seems to leave already copied files in that case.
Is this behavior expected or a TODO?

Comment (deivid-rodriguez) [reply test/rubygems/test_gem_installer.rb:1255]: In my opinion that's a bug that we should fix. A aborted installer would ideally leave no side-effects?

Comment (nobu) [reply test/rubygems/test_gem_installer.rb]: Updated.

Comment (nobu) [reply test/rubygems/test_gem_installer.rb]: The `executable` seems to be removed on JRuby and TruffleRuby...

**Review by deivid-rodriguez — APPROVED** [review]
Thank you @nobu!

**Comment by sunpoet** [comment]
@nobu and @deivid-rodriguez, thank you!

**Comment by deivid-rodriguez** [comment]
I found that Bundler was still not removing `.lock` files when using with older RubyGems, so I fixed that at #8022, and I also included a fix to https://github.com/rubygems/rubygems/pull/7931#issuecomment-2326264701, so that Bundler & RubyGems implementations can be kept in sync (I ended up removing the `MODE_TO_FLOCK` constant for simplicity).
