### PR TITLE
Fix #1470: generate documentation when --install-dir is present.

### LINKED ISSUE #1470: Documentation is not generated when --install-dir is used.
```
$ gem install -V --install-dir ./usr/share/vagrant/gems --bindir ./usr/bin --force --rdoc --ri --backtrace will_paginate
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=will_paginate
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/LICENSE
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/README.md
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/active_record.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/array.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/collection.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/core_ext.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/data_mapper.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/deprecation.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/i18n.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/locale/en.yml
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/mongoid.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/page_number.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/per_page.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/railtie.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/sequel.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/version.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/view_helpers.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/view_helpers/action_view.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/view_helpers/link_renderer.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/view_helpers/link_renderer_base.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/view_helpers/merb.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/lib/will_paginate/view_helpers/sinatra.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/collection_spec.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/console
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/console_fixtures.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/database.yml
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fake_rubygems.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/finders/active_record_spec.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/finders/activerecord_test_connector.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/finders/data_mapper_spec.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/finders/data_mapper_test_connector.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/finders/mongoid_spec.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/finders/sequel_spec.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/finders/sequel_test_connector.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/admin.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/developer.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/developers_projects.yml
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/project.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/projects.yml
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/replies.yml
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/reply.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/schema.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/topic.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/topics.yml
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/user.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/fixtures/users.yml
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/matchers/deprecation_matcher.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/matchers/phrase_matcher.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/matchers/query_count_matcher.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/page_number_spec.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/per_page_spec.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/spec_helper.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/view_helpers/action_view_spec.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/view_helpers/base_spec.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/view_helpers/link_renderer_base_spec.rb
/home/vondruch/usr/share/vagrant/gems/gems/will_paginate-3.1.0/spec/view_helpers/view_example_group.rb
Successfully installed will_paginate-3.1.0
1 gem installed
```

This looks to be similar to #961

### PR DESCRIPTION
**Pull request by knifecake**
# Description:
Fixes a problem (#1470) where documentation would not be generated when selecting a directory for installation using `--install-dir`. The code for calling hooks was moved onto a separate function (`install_hooks`) which is now called from both `install` and `install_into` (in `request_set.rb`).

___________

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends: **comments are very appreciated!**

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by knifecake** [comment]
Update: added a test in `test_gem_commands_install_command`.

**Comment by segiddins** [comment]
Thanks! This seems to break a few tests that are asserting gem_dir shouldn't exist: https://travis-ci.org/rubygems/rubygems/jobs/351724658#L688

**Comment by knifecake** [comment]
Hmmm, I see... These did not fail locally... After seeing the Travis build I tried it to reproduce them locally but couldn't: even though I used the same seed, ruby version and ubuntu version the tests still don't fail.

I think it's not the code what breaks the tests, but rather the test I wrote for the code (`test_gem_commands_install_command#test_execute_rdoc_with_path`). To verify this, I pushed another commit without the test and it successfully passed (https://travis-ci.org/rubygems/rubygems/builds/351958579). I would have done this locally but I do not get the same results.

Also, before adding any tests, the code did not break anything (https://travis-ci.org/rubygems/rubygems/builds/351572508). To be honest I'm a bit lost and I have no clue of what may be going wrong. Any help would be very much appreciated 😄 .

**Comment by bronzdoc** [comment]
@knifecake can you add your tests back, i think test failing might be related to https://github.com/rubygems/rubygems/issues/2133

**Comment by knifecake** [comment]
@bronzdoc It looks like you were right. Tests are passing 😄

File: lib/rubygems/request_set.rb [hunk 1]
```diff
@@ -283,11 +268,35 @@ def install_into dir, force = true, options = {}
...
+    specs = requests.map do |request|
+      case request
+      when Gem::Resolver::ActivationRequest then
+        request.spec.spec
+      else
+        request
+      end
+    end
+
+    require 'rubygems/dependency_installer'
```
Comment (bronzdoc) [inline lib/rubygems/request_set.rb]: can you use double quotes? :)

**Comment by bronzdoc** [comment]
@knifecake LGTM! can you squash your `Undo tests to diagnose w/ Travis CI` and `Add tests back `

into your `Add tests` commit?

File: lib/rubygems/request_set.rb (hunk 1 above)
Comment (knifecake) [reply lib/rubygems/request_set.rb]: Sure!

**Comment by bronzdoc** [comment]
@bundlerbot r+
