### PR TITLE
Fix `bundle gem` on path with spaces

### LINKED ISSUE #4622: Unable to create gem using Bundler
### Describe the problem as clearly as you can

Hi, I'm new to ruby. I tried to use Bundler to create a gem with the command: bundle gem string_extend
This produced an error report template and gave the error message " Unfortunately, an unexpected error occurred, and Bundler cannot continue. "

### Post steps to reproduce the problem

this my ruby file:

class String
	def punctuation
		scan(/[.?!,]/i)
	end
end

I navigated to the folder it is stored at and ran: bundle gem string_extend
to create a gem file there

### Which command did you run?

bundle gem string_extend

### What were you expecting to happen?

I was expecting an output similar to below in the terminal

create string_extend/Gemfile
create string_extend/Rakefile
create string_extend/LICENSE.txt
create string_extend/README.md
create string_extend/.gitignore
create string_extend/string_extend.gemspec
create string_extend/lib/string_extend.rb
create string_extend/lib/string_extend/version.rb

### What actually happened?

usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

## Backtrace

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/User/Documents/string_extend/.git/HEAD
   /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/lib/bundler/cli/gem.rb:196:in `read'
   /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/lib/bundler/cli/gem.rb:196:in `run'
   /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/lib/bundler/cli.rb:593:in `run'
   /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
   /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
 /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/lib/bundler/cli.rb:30:in `dispatch'
   /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
   /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/lib/bundler/cli.rb:24:in `start'
   /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/exe/bundle:49:in `block in <top (required)>'
   /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
   /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.18/exe/bundle:37:in `<top (required)>'
   /home/User/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
   /home/User/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.18
  Platforms   ruby, x86-linux
Ruby          2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [i686-linux]
  Full Path    /home/User/.rbenv/versions/2.7.2/bin/ruby
  Config Dir   /home/User/.rbenv/versions/2.7.2/etc
RubyGems      3.2.17
  Gem Home    / /home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
  Gem Path     /home/User/.gem/ruby/2.7.0:/home/User/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
  User Home    /home/User
  User Path    /home/User/.gem/ruby/2.7.0
  Bin Dir      /home/User/.rbenv/versions/2.7.2/bin
Tools         
  Git         2.17.1
  RVM         not installed
  rbenv       rbenv 1.1.2-44-gd604acb
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-05-25
Git SHA           <User SHA>
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user ( /home/User/.bundle/config): true
gem.ci
  Set for the current user ( /home/User/.bundle/config): "github"
gem.coc
  Set for the current user ( /home/User/.bundle/config): true
gem.mit
  Set for the current user ( /home/User/.bundle/config): false
gem.rubocop
  Set for the current user ( /home/User/.bundle/config): false
gem.test
  Set for the current user ( /home/User/.bundle/config): "rspec"
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

`bundler` would fail to initialize the fresh git repository of new gems when `bundle gem` is run inside a path with spaces.

## What is your fix for the problem, implemented in this PR?

Properly shellescape target folder.

Closes #4622.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/lib/bundler/cli/gem.rb [hunk 1]
```diff
@@ -185,14 +185,15 @@ def run
         )
       end
 
-      if File.exist?(target) && !File.directory?(target)
+      if target.exist? && !target.directory?
```
Comment (olleolleolle) [inline bundler/lib/bundler/cli/gem.rb:188]: Nice! `Pathname` ❤️ !

**Review by olleolleolle — APPROVED** [review]
💯 

The tests were improved, too. Much easier to follow, and the `context` used is now for "the exceptional", whereas the regular cases are ordinary `it`s. Super!

**Comment by deivid-rodriguez** [comment]
Thanks for your review @olleolleolle!
