### PR TITLE
Don't print bug report template when bin dir is not writable

### LINKED ISSUE #7745: bundle install failed
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ rb_sysopen - C:/Ruby32-x64/bin/racc.bat        
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `initialize'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `open'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `generate_windows_script'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:546:in `generate_bin_script' 
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:506:in `block in generate_bin'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `each'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `generate_bin'        
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/rubygems_gem_installer.rb:32:in `install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/source/rubygems.rb:202:in `install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:62:in `apply_func'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in `loop'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in `process_queue'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
Errno::EACCES: Permission denied @ rb_sysopen - C:/Ruby32-x64/bin/racc.bat        
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `initialize'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `open'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `generate_windows_script'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:546:in `generate_bin_script' 
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:506:in `block in generate_bin'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `each'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `generate_bin'        
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/rubygems_gem_installer.rb:32:in `install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/source/rubygems.rb:202:in `install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:62:in `apply_func'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in `loop'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in `process_queue'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.4.17
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x64-mingw-ucrt]
  Full Path   C:/Ruby32-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.4.10
  Gem Home    C:/Ruby32-x64/lib/ruby/gems/3.2.0
  Gem Path    C:/Users/ayush.kushwah/.local/share/gem/ruby/3.2.0;C:/Ruby32-x64/lib/ruby/gems/3.2.0
  User Home   C:/Users/ayush.kushwah
  User Path   C:/Users/ayush.kushwah/.local/share/gem/ruby/3.2.0
  Bin Dir     C:/Ruby32-x64/bin
OpenSSL
  Compiled    OpenSSL 3.1.0 14 Mar 2023
  Loaded      OpenSSL 3.1.0 14 Mar 2023
  Cert File   C:/Ruby32-x64/bin/etc/ssl/cert.pem
  Cert Dir    C:/Ruby32-x64/bin/etc/ssl/certs
Tools
  Git         2.36.1.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-07-14
Git SHA           36ea2bc283
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (C:/Users/ayush.kushwah/.bundle/config): false
gem.ci
  Set for the current user (C:/Users/ayush.kushwah/.bundle/config): false
gem.coc
  Set for the current user (C:/Users/ayush.kushwah/.bundle/config): false
gem.linter
  Set for the current user (C:/Users/ayush.kushwah/.bundle/config): false
gem.mit
  Set for the current user (C:/Users/ayush.kushwah/.bundle/config): false
gem.test
  Set for the current user (C:/Users/ayush.kushwah/.bundle/config): false
```

### Gemfile

```ruby
ruby '>= 2.6'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.4'
gem 'middleman-syntax', '~> 3.2'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-sprockets', '~> 4.1'
gem 'rouge', '~> 3.21'
gem 'redcarpet', '~> 3.6.0'
gem 'nokogiri', '~> 1.13.3'
gem 'sass'
gem 'webrick'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (6.1.6.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    autoprefixer-rails (10.2.5.0)
      execjs (< 2.8.0)
    backports (3.23.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.2.0)
    contracts (0.16.1)
    dotenv (2.8.1)
    erubis (2.7.0)
    execjs (2.7.0)
    fast_blank (1.0.1)
    fastimage (2.2.6)
    ffi (1.15.5)
    haml (5.2.2)
      temple (>= 0.8.0)
      tilt
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    hashie (3.6.0)
    i18n (1.6.0)
      concurrent-ruby (~> 1.0)
    kramdown (2.4.0)
      rexml
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    memoist (0.16.2)
    middleman (4.4.3)
      coffee-script (~> 2.2)
      haml (>= 4.0.5, < 6.0)
      kramdown (>= 2.3.0)
      middleman-cli (= 4.4.3)
      middleman-core (= 4.4.3)
    middleman-autoprefixer (3.0.0)
      autoprefixer-rails (~> 10.0)
      middleman-core (>= 4.0.0)
    middleman-cli (4.4.3)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.4.3)
      activesupport (>= 6.1, < 7.1)
      addressable (~> 2.4)
      backports (~> 3.6)
      bundler (~> 2.0)
      contracts (~> 0.13)
      dotenv
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 2.0)
      hamster (~> 3.0)
      hashie (~> 3.4)
      i18n (~> 1.6.0)
      listen (~> 3.0)
      memoist (~> 0.14)
      padrino-helpers (~> 0.15.0)
      parallel
      rack (>= 1.4.5, < 3)
      sassc (~> 2.0)
      servolux
      tilt (~> 2.0.9)
      toml
      uglifier (~> 3.0)
      webrick
    middleman-sprockets (4.1.1)
      middleman-core (~> 4.0)
      sprockets (>= 3.0)
    middleman-syntax (3.3.0)
      middleman-core (>= 3.2)
      rouge (~> 3.2)
    mini_portile2 (2.8.0)
    minitest (5.17.0)
    nokogiri (1.13.9)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    padrino-helpers (0.15.2)
      i18n (>= 0.6.7, < 2)
      padrino-support (= 0.15.2)
      tilt (>= 1.4.1, < 3)
    padrino-support (0.15.2)
    parallel (1.22.1)
    parslet (2.0.0)
    public_suffix (5.0.1)
    racc (1.6.0)
    rack (2.2.6.2)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    redcarpet (3.6.0)
    rexml (3.2.5)
    rouge (3.30.0)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sassc (2.4.0)
      ffi (~> 1.9)
    servolux (0.13.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    temple (0.10.0)
    thor (1.2.1)
    tilt (2.0.11)
    toml (0.3.0)
      parslet (>= 1.8.0, < 3.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)
    webrick (1.8.1)
    zeitwerk (2.6.0)

PLATFORMS
  ruby

DEPENDENCIES
  middleman (~> 4.4)
  middleman-autoprefixer (~> 3.0)
  middleman-sprockets (~> 4.1)
  middleman-syntax (~> 3.2)
  nokogiri (~> 1.13.3)
  redcarpet (~> 3.6.0)
  rouge (~> 3.21)
  sass
  webrick

RUBY VERSION
   ruby 2.7.2p137

BUNDLED WITH
   2.2.22
```

--- TEMPLATE END ----------------------------------------------------------------

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

When directory to write RubyGems binstubs is not writable, Bundler crashes and prints the bug report template.

## What is your fix for the problem, implemented in this PR?

Wrap executable installation with the proper helper so that we print friendly errors instead.

Fixes #7745.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/spec/commands/install_spec.rb [hunk 1]
```diff
@@ -871,6 +871,36 @@ def run
     end
   end
 
+  describe "when bundle bin dir does not have write access", :permissions do
+    let(:bin_dir) { bundled_app("vendor/#{Bundler.ruby_scope}/bin") }
+
+    before do
+      FileUtils.mkdir_p(bin_dir)
```
Comment (martinemde) [inline bundler/spec/commands/install_spec.rb:878]: do you need to clean up this dir in an `after` block?

**Review by martinemde — APPROVED** [review]

File: bundler/spec/commands/install_spec.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply bundler/spec/commands/install_spec.rb:878]: I think not strictly needed because the global after block cleans up the `bundled_app` folder anyways. But it doesn't hurt to make the test more self-contained in my opinion, will add it!

Comment (deivid-rodriguez) [reply bundler/spec/commands/install_spec.rb:878]: Actually, I see there are many other tests in this file that create some directory inside `bundled_app` and they don't clean up after themselves and rely on the global teardown for the cleanup. So I'll leave it as is for consistency. If we feel it's important enough, we can change everything on a separate PR.
