### PR TITLE
Disallow both `--branch` and `--ref` at the same time in bundle-plugin

### LINKED ISSUE #5845: bundle plugin accepts two exclusive options --branch and --ref
### Describe the problem as clearly as you can

`bundle plugin` sub-command accepts two exclusive options `--branch` and `--ref`, but the last `--ref` value is applied.

_Originally posted by @tnir in https://github.com/rubygems/bundler-site/pull/860#discussion_r949482257_

### Post steps to reproduce the problem

1. `bundle plugin install --local_git https://github.com/rubygems/bundler-graph.git bundler-graph --ref v0.1.0 --branch v0.2.0`
2. `bundle plugin install --local_git https://github.com/rubygems/bundler-graph.git bundler-graph --branch v0.2.0 --ref v0.1.0`

### Which command did you run?

1. `bundle plugin install --local_git https://github.com/rubygems/bundler-graph.git bundler-graph --ref v0.1.0 --branch v0.2.0`
2. `bundle plugin install --local_git https://github.com/rubygems/bundler-graph.git bundler-graph --branch v0.2.0 --ref v0.1.0`

### What were you expecting to happen?

Both commands should be warned or cause errors.

### What actually happened?

v0.1.0 was installed with either command.

### Note
Not sure if we really need to use two different options.

`git-clone -b` supports for arbitrary `rev` value.
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt--bltnamegt

> -b \<name\>
> --branch \<name\>
> Instead of pointing the newly created HEAD to the branch pointed to by the cloned repository’s HEAD, point to `<name>` branch instead. In a non-bare repository, this is the branch that will be checked out. `--branch` can also take tags and detaches the HEAD at that commit in the resulting repository.

### PR DESCRIPTION
**Pull request by tnir**
## What was the end-user or developer problem that led to this PR?

Allowing both --branch and --ref at the same time for `bundle-plugin` makes its behavior unstable by order.

Closes #5845

Updates #5853

## What is your fix for the problem, implemented in this PR?

Raises an error when `--branch` and `--ref` are specified at the same time in `bundle plugin`.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

### CODE REVIEW

File: bundler/spec/plugins/install_spec.rb [hunk 1]
```diff
@@ -85,6 +85,26 @@
     expect(out).to include("Using foo 1.1")
   end
 
+  it "installs when --branch option" do
```
Comment (deivid-rodriguez) [inline bundler/spec/plugins/install_spec.rb:88]:
```suggestion
  it "installs when --branch specified" do
```

File: bundler/spec/plugins/install_spec.rb [hunk 2]
```diff
@@ -85,6 +85,26 @@
...
+    bundle "plugin install foo --branch main --source #{file_uri_for(gem_repo2)}"
+
+    expect(out).to include("Installed plugin foo")
+  end
+
+  it "installs when --ref option" do
```
Comment (deivid-rodriguez) [inline bundler/spec/plugins/install_spec.rb:94]:
```suggestion
  it "installs when --ref specified" do
```

**Review by deivid-rodriguez — COMMENTED** [review]
Looks great, just minor wording comments!

File: bundler/spec/plugins/install_spec.rb (hunk 1 above)
Comment (tnir) [reply bundler/spec/plugins/install_spec.rb]: Thanks!

File: bundler/lib/bundler/plugin.rb [hunk 3]
```diff
@@ -36,6 +36,10 @@ def reset!
     # @param [Hash] options various parameters as described in description.
     #               Refer to cli/plugin for available options
     def install(names, options)
+      if options["branch"] && options["ref"]
+        raise InvalidOption, "You cannot specify both --branch and --ref were specified. You can use either option at the same time."
```
[the remark this answers is not in the document]
Comment (tnir) [reply bundler/lib/bundler/plugin.rb]: Sorry for that. I found a very similar case in https://github.com/rubygems/rubygems/blob/9dc737d679a7062250c9ee2eff451d5f0b6ff5c0/bundler/lib/bundler/cli/add.rb#L37, so applying it to here except for use of `can not`.

This sentence was introduced in https://github.com/rubygems/bundler/pull/6556/commits/13938da3fa46bc54a7008dd134662091fd16393a (in https://github.com/rubygems/bundler/pull/6556).

[the remark this answers is not in the document]
Comment (tnir) [reply bundler/lib/bundler/plugin.rb]: (off-topic note: further actions in other occurrences of `can not` will be done in #5859.)

File: bundler/lib/bundler/man/bundle-plugin.1.ronn [hunk 4]
```diff
@@ -4,7 +4,7 @@ bundle-plugin(1) -- Manage Bundler plugins
 ## SYNOPSIS
 
 `bundle plugin` install PLUGINS [--source=<SOURCE>] [--version=<version>]
-                              [--git|--local_git=<git-url>] [--branch=<branch>] [--ref=<rev>]
+                              [--git|--local_git=<git-url>] [--branch=<branch>|--ref=<rev>]
```
Comment (deivid-rodriguez) [inline bundler/lib/bundler/man/bundle-plugin.1.ronn:7]: Nice catch, I would've forgotten to update this :)

**Review by deivid-rodriguez — APPROVED** [review]

File: bundler/lib/bundler/plugin.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (deivid-rodriguez) [reply bundler/lib/bundler/plugin.rb]: Nice, thanks!
