### PR TITLE
Fix several issues with the `--prefer-local` flag

### LINKED ISSUE #6705: --prefer-local should install a lower matching version too (not just newer versions)
While testing the --prefer-local option introduced in https://github.com/rubygems/rubygems/issues/5657 I noticed it does not install an older version when specifically locked in Gemfile.

### Describe the problem as clearly as you can

```
(debian-sid)pravi@mahishi:/tmp$ cat Gemfile 
source 'https://rubygems.org'

gem 'ipaddr', '1.2.2'

```

This is locked to an older version due issues in gitlab - https://gitlab.com/gitlab-org/gitlab/-/issues/376417

```
bundle install --prefer-local
Could not find gem 'ipaddr (= 1.2.2)' in locally installed gems.

The source contains the following gems matching 'ipaddr':
  * ipaddr-1.2.4
```

So in case the locally installed version cannot satisfy the specified constraint, this should get installed from rubygems.org

### Did you try upgrading rubygems & bundler?

Using bundler 2.3.20

### Post steps to reproduce the problem

Sample Gemfile is provided above and system has a newer ipaddr via ruby.

### Which command did you run?

bundle install --prefer-local

### What were you expecting to happen?

I was expecting bundler to install ipaddr 1.2.2 from rubygems.org as locally available version 1.2.4 is not satisfying the constraint specified in Gemfile, ie, '1.2.2'

### What actually happened?

It failed to install the required version.

### If not included with the output of your command, run `bundle env` and paste the output below

(debian-sid)pravi@mahishi:/tmp$ bundle env
## Environment

```
Bundler       2.3.20
  Platforms   ruby, x86_64-linux
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]
  Full Path   /usr/bin/ruby3.1
  Config Dir  /etc
RubyGems      3.3.15
  Gem Home    /var/lib/gems/3.1.0
  Gem Path    /home/pravi/.gem/ruby/3.1.0:/var/lib/gems/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/lib/ruby/gems/3.1.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.1.0:/usr/share/rubygems-integration/3.1.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0
  User Home   /home/pravi
  User Path   /home/pravi/.gem/ruby/3.1.0
  Bin Dir     /usr/local/bin
Tools         
  Git         2.40.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-08-10
Git SHA           4fd2813f54
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'ipaddr', '1.2.2'
```

### Gemfile.lock

```
<No /tmp/Gemfile.lock found>
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

The original implementation of this flag was too naive and all it did was restricting gems to locally installed versions if there are any local versions installed.

However, it should be much smarter. For example:

* It should fallback to remote versions if locally installed version don't satisfy the requirements.
* It should pick locally installed versions even for subdependencies not yet discovered.

## What is your fix for the problem, implemented in this PR?

This PR fixes both issues by using a smarter approach similar to how we resolve prereleases:

* First resolve optimistically using only locally installed gems.
* If any conflicts are found, scan those conflicts, allow remote versions for the specific gems that run into conflicts, and re-resolve.

Fixes #6705.
Closes #7936.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/lib/bundler/definition.rb [hunk 1]
```diff
@@ -571,7 +571,7 @@ def resolution_packages
       @resolution_packages ||= begin
         last_resolve = converge_locked_specs
         remove_invalid_platforms!
-        packages = Resolver::Base.new(source_requirements, expanded_dependencies, last_resolve, @platforms, locked_specs: @originally_locked_specs, unlock: @gems_to_unlock, prerelease: gem_version_promoter.pre?)
+        packages = Resolver::Base.new(source_requirements, expanded_dependencies, last_resolve, @platforms, locked_specs: @originally_locked_specs, unlock: @gems_to_unlock, prerelease: gem_version_promoter.pre?, prefer_local: @prefer_local)
```
Comment (gouravkhunger) [inline bundler/lib/bundler/definition.rb:574]: Not sure how `prefer_local` is received in the `Base`'s initializer. Does it go to the `options` hash?

https://github.com/rubygems/rubygems/blob/636af9667c1253371cc43c46d15609ed18eed74a/bundler/lib/bundler/resolver/base.rb#L10

**Review by gouravkhunger — COMMENTED** [review]
Thank you so much for this, lgtm! I have a minor question listed below, which is probably because of my lack of expertise in ruby.

I've also created #7952 to add an additional test case for the proposed logic. Please check if you think it is good to have.

File: bundler/lib/bundler/definition.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply bundler/lib/bundler/definition.rb:574]: Yes, it goes into the `options` hash.

**Comment by deivid-rodriguez** [comment]
I merged your new test, and wrote yet one more test to prove that #6705 is fixed as well.

**Comment by gouravkhunger** [comment]
Thanks @deivid-rodriguez! I found a case which I'm not sure is an issue or not. A case where a gem depends on another gem with a higher version. And the sub-dependency is listed as a requirement with a lower version and thus conflicts occur.

```ruby

it "fetches remote sources when local version does not match requirements", :focus => true do
  install_gemfile <<-G, "prefer-local": true, verbose: true
    source "https://gem.repo4"

    gem "b"
    gem "foo", "1.0.0"
  G

  puts out
end
```

This gives an error:

```
       ----------------------------------------------------------------------
       Bundler::SolveFailure: Could not find compatible versions

       Because every version of b depends on foo ~> 1.0.1
         and Gemfile depends on b >= 0,
         foo ~> 1.0.1 is required.
       So, because Gemfile depends on foo = 1.0.0,
         version solving has failed.
...
```

If that kind of Gemfile requirement is non-standard then it is not a big deal ig.

**Comment by deivid-rodriguez** [comment]
@gouravkhunger That's the expected behavior, and the behavior you also get without `--prefer-local`. Basically it's impossible for Bundler to resolve the Gemfile requirements, because they conflict with each other, so Bundler prints a resolution error explaining the conflict found.

**Comment by gouravkhunger** [comment]
Alright, makes sense! All good from my side.

**Comment by deivid-rodriguez** [comment]
Thanks so much @gouravkhunger!

**Comment by deivid-rodriguez** [comment]
No problem! You're co-author in the commit that implemented the fix: https://github.com/rubygems/rubygems/commit/607a3bf479aed71a732da1027d48a1ed7240b302. You're not co-author in the merge commit because I was the one who clicked "Merge". I don't think merge commits get co-authors.

**Comment by gouravkhunger** [comment]
Maybe GitHub didn't pick it up because of the force pushes. But generally they do get added. Or you'd have to manually do this

image

I hoped if you could do that but maybe there could be branch protection rules. However, currently I don't get added as a contributor to the repo

**Comment by deivid-rodriguez** [comment]
GitHub did pick it up, you can see your username in the commit I mentioned in the master branch: https://github.com/rubygems/rubygems/commit/607a3bf479aed71a732da1027d48a1ed7240b302.

The merge commit uses a default commit message, and I was the one who clicked on merge, so that's why you get no attribution there. I guess I could enable the option to customize merge commit message and then manually add `Co-authored-by` information to it. However, I don't think it makes sense to do that, since you did not author the merge commit.

I also see your name listed in [this page](https://github.com/rubygems/rubygems/pulse).

Why do you say that currently you don't get added as a contributor to this repo? Where is it that you'd like to get added?

**Comment by gouravkhunger** [comment]
Oh my bad! I only saw the merge commit and this one was down below because the commit date was 2 days ago. Really sorry for the confusion, squash merging all the way made me forget this behaviour lol.

Initially, I meant the [Contributors](https://github.com/rubygems/rubygems/graphs/contributors) page. Because there GitHub picks up authors of commits from the default branch only.

I hope to could contribute better in the future :)
