### PR TITLE
Fix private registry credentials being written to logs

### LINKED ISSUE #5281: private registry credentials are written to the logs when `bundle install` fails due to `Bundler::PermissionError` error
### Describe the problem as clearly as you can

username and password of a private registry that was configured as an environment variable like `BUNDLE_GITHUB__COM` are visible when the `bundle install` command have errors:
```
Command result error lines for "bundle install":
Read error line #1: [DEPRECATED] Your Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source.
Read error line #2: Retrying download gem from https://sami:notmyrealpassword@example.com due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/local/ruby/2.7.5/lib/ruby/gems/2.7.0/cache/faraday-em_synchrony-1.0.0.gem`. It is likely that you need to grant write permissions for that path.
Read error line #3: Retrying download gem from https://sami:notmyrealpassword@example.com due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/local/ruby/2.7.5/lib/ruby/gems/2.7.0/cache/faraday-em_http-1.0.0.gem`. It is likely that you need to grant write permissions for that path.
```

### Did you try upgrading rubygems & bundler?

yes, using bundler 2.3.4 and ruby 2.7.5

### Post steps to reproduce the problem

install `bundler` with root permissions.
Configure environment variable for holding the credentials information, such that: `export BUNDLE_EXAMPLE__COM=username:password`
Then add a dependency to a private registry and include it in your Gemfile with multiple sources:
 ```
source 'https://rubygems.org'
source 'https://private.example.com'
gem 'private_gem', '~> 1.0.0'
```
run `bundle install` (not in root)

### Which command did you run?

`bundle install`

### What were you expecting to happen?

The logs will not present the real password

### What actually happened?

We can see the real password of the private registry login credentials printed on the logs.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Private registry credentials are written to logs when Bundler runs into errors.

## What is your fix for the problem, implemented in this PR?

Redact credentials before printing it to logs.

Fixes #5281.
Supersedes #5292.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/spec/bundler/rubygems_integration_spec.rb [hunk 1]
```diff
@@ -41,13 +40,43 @@
...
+          and_return(bundler_retry)
+        expect(bundler_retry).to receive(:attempts).and_yield
+        expect(fetcher).to receive(:cache_update_path)
+
+        Bundler.rubygems.download_gem(spec, uri, cache_dir, fetcher)
+      end
+    end
+
+    context "when uri contains user" do
+      let(:uri) { Gem::URI.parse("https://user@foo.bar") }
```
Comment (timon) [inline bundler/spec/bundler/rubygems_integration_spec.rb:70]: Out of context I would find this description confusing, I could easily imagine people going "huh, what's wrong about the user?"

I would consider rewording the description for keeping the context around, for being more obvious about it. What do you think of

```ruby 
    context "when uri contains userinfo part" do
      context "with user and password" 
      context "with token [as user]"
```

or just for this context,

```suggestion
    context "when uri has userinfo which is a token" do
      let(:uri) { Gem::URI.parse("https://token@foo.bar") }
```

(I think the former is slightly more informative)

Comment (deivid-rodriguez) [reply bundler/spec/bundler/rubygems_integration_spec.rb:70]: Great suggestion, you're absolutely right. I will add this 👍.

**Review by simi — APPROVED** [review]
