### PR TITLE
Fix generic arm platform matching against runtime arm platforms with eabi modifiers

### LINKED ISSUE #5940: `arm-linux` gem platform no longer matches `arm-linux-*` runtimes
### Describe the problem as clearly as you can

In Rubygems 3.3.20 and earlier, a gem with platform "arm-linux" would match a runtime platform "arm-linux-eabi" (and others). In Rubygems 3.3.21 and later, it does not.

```ruby
#! /usr/bin/env ruby

Gem::VERSION # => "3.3.20"

x86_64_linux = Gem::Platform.new("x86_64-linux")
x86_64_linux_musl = Gem::Platform.new("x86_64-linux-musl")

x86_64_linux === x86_64_linux_musl # => true

arm_linux = Gem::Platform.new("arm-linux")
arm_linux_eabi = Gem::Platform.new("arm-linux-eabi")
arm_linux_eabihf = Gem::Platform.new("arm-linux-eabihf")

arm_linux === arm_linux_eabi # => true
arm_linux === arm_linux_eabihf # => true
```

vs

```ruby
#! /usr/bin/env ruby

Gem::VERSION # => "3.3.21"

x86_64_linux = Gem::Platform.new("x86_64-linux")
x86_64_linux_musl = Gem::Platform.new("x86_64-linux-musl")

x86_64_linux === x86_64_linux_musl # => true

arm_linux = Gem::Platform.new("arm-linux")
arm_linux_eabi = Gem::Platform.new("arm-linux-eabi")
arm_linux_eabihf = Gem::Platform.new("arm-linux-eabihf")

arm_linux === arm_linux_eabi # => false
arm_linux === arm_linux_eabihf # => false
```

As a result, `gem install nokogiri` on an arm system does not select the `arm-linux` platform gem. With rubygems < 3.3.21 this command will select the `arm-linux` platform gem.

I believe this is the desired behavior, in the form of an addition to the test suite:

```patch
diff --git a/test/rubygems/test_gem_platform.rb b/test/rubygems/test_gem_platform.rb
index f683204..99395b4 100644
--- a/test/rubygems/test_gem_platform.rb
+++ b/test/rubygems/test_gem_platform.rb
@@ -306,6 +306,7 @@ def test_nil_version_is_stricter_for_linux_os
   end
 
   def test_eabi_version_is_stricter_for_linux_os
+    arm_linux = Gem::Platform.new "arm-linux"
     arm_linux_eabi = Gem::Platform.new "arm-linux-eabi"
     arm_linux_gnueabi = Gem::Platform.new "arm-linux-gnueabi"
     arm_linux_musleabi = Gem::Platform.new "arm-linux-musleabi"
@@ -331,6 +332,12 @@ def test_eabi_version_is_stricter_for_linux_os
     # other libc are not glibc compatible
     refute(arm_linux_eabi === arm_linux_uclibceabi, "linux-eabi =~ linux-uclibceabi")
     refute(arm_linux_uclibceabi === arm_linux_eabi, "linux-uclibceabi =~ linux-eabi")
+
+    # gems with platform "arm-linux" should match any of these
+    assert(arm_linux === arm_linux_eabi, "arm_linux === arm_linux_eabi")
+    assert(arm_linux === arm_linux_gnueabi, "arm_linux === arm_linux_gnueabi")
+    assert(arm_linux === arm_linux_musleabi, "arm_linux === arm_linux_musleabi")
+    assert(arm_linux === arm_linux_uclibceabi, "arm_linux === arm_linux_uclibceabi")
   end
 
   def test_equals3_cpu_arm
```

### Did you try upgrading RubyGems?

Issue introduced by #5852 and present on `master` and in 3.3.22

### Post steps to reproduce the problem

In the `ruby:3.1` docker image with platform `linux/arm/v7` (runtime platform string is `arm-linux-eabihf`), running `gem install nokogiri` should select Nokogiri's `arm-linux` gem platform.

### What were you expecting to happen?

`arm-linux` gems should match `arm-linux-eabi` (and other libc versions) the same way that `x86_64-linux` matches `x86_64-linux-musl`.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Since RubyGems 3.3.20, arm platforms with eabi modifiers no longer accept generic `arm-linux` gems.

## What is your fix for the problem, implemented in this PR?

My fix is to refactor platform comparison so that eabi modifiers are properly ignored, except for the musl special case.

Fixes #5940.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by flavorjones** [comment]
@deivid-rodriguez Can you help me understand what behavior you expect for `arm-linux-eabihf`? (This is the platform string in the `ruby:3.1` docker image with platform `linux/arm/v7`.)

Previously (rubygems 3.3.20 and earlier), this was the behavior:

```ruby
#! /usr/bin/env ruby

Gem::VERSION # => "3.3.20"

arm_linux = Gem::Platform.new("arm-linux")
arm_linux_eabi = Gem::Platform.new("arm-linux-eabi")
arm_linux_eabihf = Gem::Platform.new("arm-linux-eabihf")

arm_linux === arm_linux_eabi # => true
arm_linux === arm_linux_eabihf # => true
```

With rubygems 3.3.21, this was the behavior:

```ruby
#! /usr/bin/env ruby

Gem::VERSION # => "3.3.21"

arm_linux = Gem::Platform.new("arm-linux")
arm_linux_eabi = Gem::Platform.new("arm-linux-eabi")
arm_linux_eabihf = Gem::Platform.new("arm-linux-eabihf")

arm_linux === arm_linux_eabi # => false
arm_linux === arm_linux_eabihf # => false
```

With the change in this PR, here's the behavior:

```ruby
#! /usr/bin/env ruby

Gem::VERSION # => "3.4.0.dev"

arm_linux = Gem::Platform.new("arm-linux")
arm_linux_eabi = Gem::Platform.new("arm-linux-eabi")
arm_linux_eabihf = Gem::Platform.new("arm-linux-eabihf")

arm_linux === arm_linux_eabi # => true
arm_linux === arm_linux_eabihf # => false
```

Wearing my nokogiri maintainer hat, I would like `arm-linux-eabihf` platforms to choose the `arm-linux` gem as rubygems did in 3.3.20 and earlier, but I may be missing critical context.

**Comment by deivid-rodriguez** [comment]
I used the failing test cases you provided as a base, and completely missed the `eabihf` modifier, since it was not included in those tests (although it was mentioned in the issue).

Nah, you're not missing any context. these are just oversights, you maintainers of precompiled gems know this much better than I do, so I totally trust you on what the best behavior is.

Let me update this like to work like it worked before.

File: lib/rubygems/platform.rb [hunk 1]
```diff
@@ -181,11 +181,20 @@ def ===(other)
       # version
       (
         (@os != "linux" && (@version.nil? || other.version.nil?)) ||
-        (@os == "linux" && (other.version == "gnu#{@version}" || other.version == "musl#{@version}" || @version == "gnu#{other.version}")) ||
+        (@os == "linux" && (normalized_linux_version == other.normalized_linux_version || ["musl#{@version}", "musleabi#{@version}", "musleabihf#{@version}"].include?(other.version))) ||
         @version == other.version
       )
   end
```
Comment (indirect) [inline lib/rubygems/platform.rb:188]:
```suggestion
# Until it can be removed, changes to this method must also be reflected in `bundler/lib/bundler/rubygems_ext.rb`
```

Comment (deivid-rodriguez) [reply lib/rubygems/platform.rb:188]: Definitely, I don't like having to keep this duplicated but I couldn't find a nicer way to do the backport. A note will definitely help here! Also changes to `===` need to be duplicated in Bundler, so I'll add a note there too.

**Comment by flavorjones** [comment]
Thanks for adding support for `eabihf`! 1ac5b14 looks good in my test script.

**Comment by deivid-rodriguez** [comment]
Awesome, let's do this then!
