### PR TITLE
Fix broken brew formula due to loading `operating_system.rb` customizations too late

### LINKED ISSUE #4399: Error with Jekyll Template
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/Users/benleather/.gem/ruby/2.7.0/bin/bundle exec jekyll serve`

- **What did you expect to happen?**

  I expected Bundler to compile the and build the site

- **What happened instead?**

  Instead, what happened was... I received the following error message (listed below).

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried reinstalling Jekyll, Ruby and re-run the building process of the website.

- **Have you read our issues document, https://github.com/rubygems/rubygems/blob/master/bundler/doc/contributing/ISSUES.md?**
 
   Yes.

## Backtrace

```
Gem::GemNotFoundException: can't find gem bundler (= 2.2.11) with executable bundle
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems.rb:281:in `find_spec_for_exe'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems.rb:258:in `bin_path'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:209:in `bin_path'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:25:in `run'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:494:in `exec'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:24:in `start'
  /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
  /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
  /Users/benleather/.gem/ruby/2.7.0/bin/bundle:23:in `load'
  /Users/benleather/.gem/ruby/2.7.0/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.11
  Platforms   ruby, x86_64-darwin-20
Ruby          3.0.0p0 (2020-12-25 revision 95aff214687a5e12c3eb57d056665741e734c188) [x86_64-darwin20]
  Full Path   /usr/local/opt/ruby/bin/ruby
  Config Dir  /usr/local/Cellar/ruby/3.0.0_1/etc
RubyGems      3.2.11
  Gem Home    /usr/local/lib/ruby/gems/3.0.0
  Gem Path    /Users/benleather/.gem/ruby/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/gems/3.0.0
  User Home   /Users/benleather
  User Path   /Users/benleather/.gem/ruby/3.0.0
  Bin Dir     /usr/local/lib/ruby/gems/3.0.0/bin
Tools         
  Git         2.24.3 (Apple Git-128)
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-02-17
Git SHA           6ca677a0eb
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'jekyll', '3.8.5'

group :jekyll_plugins do
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
end
gem "webrick", "~> 1.7"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.8)
    em-websocket (0.5.2)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    eventmachine (1.2.7)
    ffi (1.14.2)
    forwardable-extended (2.6.0)
    http_parser.rb (0.6.0)
    i18n (0.9.5)
      concurrent-ruby (~> 1.0)
    jekyll (3.8.5)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 0.7)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 1.14)
      liquid (~> 4.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (>= 1.7, < 4)
      safe_yaml (~> 1.0)
    jekyll-paginate (1.1.0)
    jekyll-sass-converter (1.5.2)
      sass (~> 3.4)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (1.17.0)
    liquid (4.0.3)
    listen (3.4.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.3.6)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.6)
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rouge (3.26.0)
    safe_yaml (1.0.5)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    webrick (1.7.0)

PLATFORMS
  x86_64-darwin-20

DEPENDENCIES
  jekyll (= 3.8.5)
  jekyll-paginate
  jekyll-sitemap
  webrick (~> 1.7)

BUNDLED WITH
   2.2.11
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=can%27t+find+gem+bundler+%28%3D+2.2.11%29+with+executable+bundle&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/rubygems/rubygems/issues/new?labels=Bundler

### LINKED ISSUE #5043: RubyGems preloads "fiddle", but reloads a different version on require (Windows)
Demonstration:

```
> gem update --system
Latest version already installed. Done.

> gem list fiddle
*** LOCAL GEMS ***
fiddle (1.1.0, default: 1.0.6)

> ruby -e "p Fiddle::VERSION"
"1.0.6"

> ruby --disable=gems -e "p Fiddle::VERSION"
-e:1:in `<main>': uninitialized constant Fiddle (NameError)

> ruby -e "require 'fiddle'; p Fiddle::VERSION"
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:12: warning: method redefined; discarding old win32_last_error
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:12: warning: previous definition of win32_last_error was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:17: warning: method redefined; discarding old win32_last_error=
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:17: warning: previous definition of win32_last_error= was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:35: warning: method redefined; discarding old last_error
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:23: warning: previous definition of last_error was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:40: warning: method redefined; discarding old last_error=
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:28: warning: previous definition of last_error= was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:67: warning: already initialized constant Fiddle::RTLD_GLOBAL
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:55: warning: previous definition of RTLD_GLOBAL was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:68: warning: already initialized constant Fiddle::RTLD_LAZY
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:56: warning: previous definition of RTLD_LAZY was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:69: warning: already initialized constant Fiddle::RTLD_NOW
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:57: warning: previous definition of RTLD_NOW was here
"1.0.6"
```

After the reload, the version is wrong.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
> gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.30
  - RUBY VERSION: 3.0.2 (2021-07-07 patchlevel 107) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/ruby-3.0.2/lib/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: c:/home/thierry/.gem/ruby/3.0.0
  - RUBY EXECUTABLE: C:/ruby-3.0.2/bin/ruby.exe
  - GIT EXECUTABLE: C:\Programs\Git\cmd/git.EXE
  - EXECUTABLE DIRECTORY: C:/ruby-3.0.2/bin
  - SPEC CACHE DIRECTORY: c:/home/thierry/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86-mingw32
  - GEM PATHS:
     - C:/ruby-3.0.2/lib/ruby/gems/3.0.0
     - c:/home/thierry/.gem/ruby/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
     - "rdoc" => "--format babel"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\WINDOWS\System32\OpenSSH\
     - c:\ruby\bin
     - C:\Programs
```

### LINKED ISSUE #5151: Bundler cannot continue when installing Jekyll.
Hi, 
I'm installing Jekyll with visual studio code in terminal on macbook pro with MacOs Montery version 12.0.1
# Jekyll Installation failed 
mac@MacBook-Pro myblog % bundle init
Writing new Gemfile to /Users/mac/Documents/repos/myblog/Gemfile
mac@MacBook-Pro myblog % bundle config set --local path 'vendor/bundle'
mac@MacBook-Pro myblog % bundle add jekyll
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using bundler 2.2.33
Fetching concurrent-ruby 1.1.9
Fetching eventmachine 1.2.7
Fetching http_parser.rb 0.8.0
Fetching ffi 1.15.4
Fetching forwardable-extended 2.6.0
Fetching rb-fsevent 0.11.0
Fetching public_suffix 4.0.6
Fetching colorator 1.1.0
Installing rb-fsevent 0.11.0
Fetching rexml 3.2.5
Installing eventmachine 1.2.7 with native extensions
Installing public_suffix 4.0.6
Fetching liquid 4.0.3
Installing colorator 1.1.0
Fetching mercenary 0.4.0
Installing forwardable-extended 2.6.0
Fetching rouge 3.26.1
Installing http_parser.rb 0.8.0 with native extensions
Installing concurrent-ruby 1.1.9
Installing mercenary 0.4.0
Fetching safe_yaml 1.0.5
Fetching unicode-display_width 1.8.0
Installing ffi 1.15.4 with native extensions
Installing rexml 3.2.5
Fetching addressable 2.8.0
Installing liquid 4.0.3
Fetching pathutil 0.16.2
Fetching i18n 1.8.11
Installing unicode-display_width 1.8.0
mac@MacBook-Pro myblog % bundle exec jekyll new --force --blank --skip-bundle .
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::GemNotFoundException: can't find gem bundler (= 2.2.33) with executable bundle
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems.rb:278:in `find_spec_for_exe'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems.rb:255:in `bin_path'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:207:in `bin_path'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/shared_helpers.rb:290:in `set_bundle_variables'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:20:in `run'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:479:in `exec'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:25:in `start'
  /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
  /Users/mac/.gem/ruby/3.0.0/bin/bundle:23:in `load'
  /Users/mac/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.33
  Platforms   ruby, arm64-darwin-21
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [arm64-darwin21]
  Full Path   /opt/homebrew/opt/ruby/bin/ruby
  Config Dir  /opt/homebrew/Cellar/ruby/3.0.3/etc
RubyGems      3.2.33
  Gem Home    /opt/homebrew/lib/ruby/gems/3.0.0
  Gem Path    /Users/mac/.gem/ruby/3.0.0:/opt/homebrew/lib/ruby/gems/3.0.0:/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/gems/3.0.0
  User Home   /Users/mac
  User Path   /Users/mac/.gem/ruby/3.0.0
  Bin Dir     /opt/homebrew/lib/ruby/gems/3.0.0/bin
Tools         
  Git         2.30.1 (Apple Git-130)
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-07
Git SHA           9b5e2a350b
Released Version  true
```

## Bundler settings

```
path
  Set for your local app (/Users/mac/Documents/repos/myblog/.bundle/config): "vendor/bundle"
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 4.2"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.9)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    ffi (1.15.4)
    forwardable-extended (2.6.0)
    http_parser.rb (0.8.0)
    i18n (1.8.11)
      concurrent-ruby (~> 1.0)
    jekyll (4.2.1)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (~> 2.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (~> 0.4.0)
      pathutil (~> 0.9)
      rouge (~> 3.0)
      safe_yaml (~> 1.0)
      terminal-table (~> 2.0)
    jekyll-sass-converter (2.1.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (2.3.1)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.3)
    listen (3.7.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.6)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (3.26.1)
    safe_yaml (1.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    terminal-table (2.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    unicode-display_width (1.8.0)

PLATFORMS
  arm64-darwin-21

DEPENDENCIES
  jekyll (~> 4.2)

BUNDLED WITH
   2.2.33
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=can%27t+find+gem+bundler+%28%3D+2.2.33%29+with+executable+bundle&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

# Can you help me Thanks :)

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Hombrew ruby formula no longer works since #5044 .

## What is your fix for the problem, implemented in this PR?

The problem is that setting up default gems needs `Gem.default_dir`, which is something commonly customized in this file. So if we setup default gems before loading `operating_system.rb` customizations, we will setup the wrong default gems.

Unfortunately fixing this requires reverting #5044, but I wasn't even sure that enhancement was the right thing to do, and the culprit ended up being something else, so we should fix the real culprit there instead.

Fixes #5151.
Fixes #5043.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by broonzman — APPROVED** [review]

File: lib/rubygems.rb [hunk 1]
```diff
@@ -1293,7 +1293,12 @@ def already_loaded?(file)
     end
 
     def default_gem_load_paths
-      @default_gem_load_paths ||= $LOAD_PATH[load_path_insert_index..-1]
+      @default_gem_load_paths ||= $LOAD_PATH[load_path_insert_index..-1].map do |lp|
+        expanded = File.expand_path(lp)
+        next expanded unless File.exist?(expanded)
+
+        File.realpath(expanded)
```
Comment (voxik) [inline lib/rubygems.rb:1300]: I am afraid that using `require_relative` is digging its own rabbit hole and solves no issue. I wish Rubygems returned to using plain require. There are at least two reasons:

1) `require_relative` does not avoid double loading of files, it just shifts the problem elsewhere
2) The real issue is actually class reopening and redefinition attempts, which it does not avoid either.

Comment (voxik) [reply lib/rubygems.rb:1300]: Although in Ruby 3.1, there is ruby/ruby/pull/4887, so maybe the situation might be a tiny bit better.

Comment (deivid-rodriguez) [reply lib/rubygems.rb:1300]: I don't use `require_relative` for any of those reasons. I use `require_relative` because it's faster and simpler to understand for requiring internal code. We are not going back to plain `require` since everybody agrees here, I've been proposing PRs in this repository and many others and you have been the only person against it in all this time.

Comment (deivid-rodriguez) [reply lib/rubygems.rb:1300]: By the way, maybe this diff is confusing because I changed some `autoload`s to `require_relative` while investigating, but `require_relative` is completely unrelated to this issue. Or at least I don't get how it's connected.

Comment (voxik) [reply lib/rubygems.rb:1300]: I don't see why are you suddenly need to expand the paths. That was not needed before and the only reason I can imagine is the `require_relative` and its incompatibility with `require`. The commit message does not provide more insights. Maybe it is completely unrelated.

Comment (deivid-rodriguez) [reply lib/rubygems.rb:1300]: Yeah, it's completely unrelated, I'll improve the commit message.

**Comment by voxik** [comment]
~~~
  1) Failure:
GemTest#test_operating_system_customizing_default_dir [/builddir/build/BUILD/ruby-3.0.3/test/rubygems/test_rubygems.rb:39]:
Expected "/builddir/build/BUILD/ruby-3.0.3/ruby: No such file or directory -- gem (LoadError)" to be empty.
~~~

**Comment by voxik** [comment]
Just FTR, the test failure happened when I applied the patch to Ruby 3.0.3 and executed the test suite via `make check`. I am not sure that the `gem` command could be found on `PATH` in this configuration.

**Comment by voxik** [comment]
And again, I am not happy about the symlink expansion. This is not right. This is not intuitive.

Just for example, if you execute Ruby via `/bin/ruby`, then it is not acceptable Gems to be reported from `/urs/lib`. This causes just confusion.

If the symlink expansion would be so good idea, then this would be the shell behavior:

~~~
$ $ ll /
celkem 20
dr-xr-xr-x.   1 root root    0 22. zář 11.54 afs
lrwxrwxrwx.   1 root root    7 22. zář 11.54 bin -> usr/bin
dr-xr-xr-x.   7 root root 4096  4. lis 18.40 boot
drwxr-xr-x.  20 root root 4660 10. pro 09.31 dev
drwxr-xr-x.   1 root root 4716  8. pro 16.22 etc
drwxr-xr-x.   1 root root   16 22. zář 11.54 home
lrwxrwxrwx.   1 root root    7 22. zář 11.54 lib -> usr/lib
lrwxrwxrwx.   1 root root    9 22. zář 11.54 lib64 -> usr/lib64
drwx------.   1 root root    0 29. říj  2020 lost+found
drwxr-xr-x.   1 root root    0 22. zář 11.54 media
drwxr-xr-x.   1 root root   30 22. zář 11.54 mnt
drwxr-xr-x.   1 root root    0 22. zář 11.54 opt
dr-xr-xr-x. 389 root root    0 12. lis 10.25 proc
dr-xr-x---.   1 root root  206  1. pro 15.59 root
drwxr-xr-x.  51 root root 1340 10. pro 06.28 run
lrwxrwxrwx.   1 root root    8 22. zář 11.54 sbin -> usr/sbin
drwxr-xr-x.   1 root root    0 22. zář 11.54 srv
dr-xr-xr-x.  13 root root    0 12. lis 10.25 sys
drwxrwxrwt.  30 root root  780 10. pro 13.28 tmp
drwxr-xr-x.   1 root root  100  1. říj 10.29 usr
drwxr-xr-x.   1 root root  200  1. říj 10.36 var

$ cd /bin

$ pwd
/usr/bin
~~~

But in reality, the result is `/bin`.

Just as an example [this](https://src.fedoraproject.org/rpms/rubygem-rdoc/blob/rawhide/f/rubygem-rdoc.spec#_88) is place, where previously used `ln -s` needed to be [replaced](https://src.fedoraproject.org/rpms/rubygem-rdoc/c/ef8f17bbe128e8c8ca125e966e663c4cf52c4085) by `cp -a` when `require_relative` was introduced into RDoc. This is the stuff we need to do in Fedora to be able to execute the test suite. Having multiple copies of test suite around is not better then symlink.

**Comment by voxik** [comment]
Forgot to mention that I have reported this ticket yesterday to solve the issue:

https://bugs.ruby-lang.org/issues/18401

The idea is to really make `require_relative` to behave the same as `require` without expanding the symlinks

**Comment by deivid-rodriguez** [comment]
We have been expanding `$LOAD_PATH` entries in other places for a long time when we need to compare them with other paths, in order to fix issues with symlinked rubies. For example, here: https://github.com/rubygems/rubygems/blob/a969cf029125e9d0a98c12d6bc13f7350c6bcfb2/bundler/lib/bundler/shared_helpers.rb#L315-L331. I think it was added because otherwise bundler was crashing when run on some rvm gemsets that use symlinks.

In general, I think avoiding runtime crashes or redefinition warnings is a higher priority than potentially causing confusion when symlinked rubies are used.

I updated the test so that it hopefully works in your environment now.

**Comment by voxik** [comment]
> I updated the test so that it hopefully works in your environment now.

Yes, the test passes and it seems to fix also the issues #5156 :+1: Going to apply this fix to Ruby in Fedora in a bit.
