### PR TITLE
Fix `bundle install --local` hitting the network when default gems are included

### LINKED ISSUE #8025: `bundle install --local` should not try to reach internet
After Ruby 3.3.5 landed in Fedora, we have started to observe issues with should-matchers test suite:

~~~
$ bundle exec rspec spec/unit
An error occurred while loading ./spec/unit/shoulda/matchers/action_controller/callback_matcher_spec.rb.
Failure/Error: require 'unit_spec_helper'
NoMethodError:
  undefined method `join' for nil
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:165:in `ensure in run'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:165:in `run'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:37:in `call'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:37:in `block in initialize'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:169:in `run_with_wrapper'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:176:in `run_with_debugging'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:66:in `block (2 levels) in call'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:196:in `possibly_running_quickly'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:65:in `block in call'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:202:in `possibly_retrying'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:64:in `call'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:11:in `block in run'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:9:in `run'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:16:in `run!'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/bundle.rb:43:in `install_gems'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/bundle.rb:24:in `updating'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/unit/rails_application.rb:177:in `update_gems'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/unit/rails_application.rb:22:in `block in create'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/filesystem.rb:31:in `chdir'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/filesystem.rb:31:in `within_project'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/unit/rails_application.rb:21:in `create'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/unit/load_environment.rb:7:in `<top (required)>'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/unit_spec_helper.rb:1:in `require_relative'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/unit_spec_helper.rb:1:in `<top (required)>'
# ./spec/unit/shoulda/matchers/action_controller/callback_matcher_spec.rb:1:in `<top (required)>'
# ------------------
# --- Caused by: ---
# IOError:
#   closed stream
#   /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:150:in `spawn'

... snip ...
~~~

Trying to understand what is going on, I have narrowed the test:

~~~
$ RUBYOPT=-d bundle exec rspec spec/unit/shoulda/matchers/action_controller/callback_matcher_spec.rb 
Exception `LoadError' at /usr/share/rubygems/rubygems.rb:1361 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136 - cannot load such file -- abrt
Exception `LoadError' at <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:144 - cannot load such file -- abrt
Exception `NameError' at /usr/share/gems/gems/bundler-2.5.16/lib/bundler/rubygems_integration.rb:369 - method `gem' not defined in #<Class:Kernel>
Exception `NameError' at /usr/share/gems/gems/rspec-core-3.13.1/lib/rspec/core/pending.rb:20 - uninitialized constant RSpec::Core::Pending::Test
Exception `NameError' at /usr/share/gems/gems/psych-5.1.2/lib/psych/class_loader.rb:70 - uninitialized constant BigDecimal
Exception `NameError' at /usr/share/gems/gems/psych-5.1.2/lib/psych/class_loader.rb:70 - uninitialized constant Date
Exception `NameError' at /usr/share/gems/gems/psych-5.1.2/lib/psych/class_loader.rb:70 - uninitialized constant DateTime
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `EOFError' at <internal:io>:63 - end of file reached
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at <internal:io>:63 - Resource temporarily unavailable - read would block
Exception `EOFError' at <internal:io>:63 - end of file reached
Exception `RuntimeError' at /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:111 - Command "bundle install --local" exited with status 5.
Output:
---START----------------------------------------------------------------
Exception `LoadError' at /usr/share/rubygems/rubygems.rb:1361 - cannot load such file -- rubygems/defaults/ruby
Exception `NameError' at /usr/share/gems/gems/bundler-2.5.16/lib/bundler/rubygems_integration.rb:369 - method `gem' not defined in #<Class:Kernel>
Exception `LoadError' at /usr/share/ruby/bundled_gems.rb:75 - cannot load such file -- abrt
Exception `Socket::ResolutionError' at /usr/share/rubygems/rubygems/vendor/net-http/lib/net/http.rb:1603 - getaddrinfo: Temporary failure in name resolution
Exception `Socket::ResolutionError' at /usr/share/rubygems/rubygems/vendor/net-http/lib/net/http.rb:1605 - Failed to open TCP connection to index.rubygems.org:443 (getaddrinfo: Temporary failure in name resolution)
Exception `Socket::ResolutionError' at /usr/share/rubygems/rubygems/vendor/net-http/lib/net/http.rb:1691 - Failed to open TCP connection to index.rubygems.org:443 (getaddrinfo: Temporary failure in name resolution)
Exception `Bundler::Fetcher::NetworkDownError' at /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher/downloader.rb:73 - Could not reach host index.rubygems.org. Check your network connection and try again.
Exception `Bundler::Fetcher::NetworkDownError' at /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher/compact_index.rb:113 - Could not reach host index.rubygems.org. Check your network connection and try again.
Exception `Bundler::HTTPError' at /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher/compact_index.rb:15 - Could not reach host index.rubygems.org. Check your network connection and try again.
Exception `Bundler::InstallError' at /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/parallel_installer.rb:166 - Bundler::HTTPError: Could not reach host index.rubygems.org. Check your network connection and try again.
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher/compact_index.rb:15:in `rescue in block in compact_index_request'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher/compact_index.rb:13:in `block in compact_index_request'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher.rb:232:in `block in fetchers'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher.rb:232:in `drop_while'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher.rb:232:in `fetchers'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher.rb:205:in `api_fetcher?'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:400:in `select'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:400:in `api_fetchers'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:405:in `block in remote_specs'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/index.rb:9:in `build'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:404:in `remote_specs'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:228:in `cached_built_in_gem'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:151:in `install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/parallel_installer.rb:117:in `install_serially'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/parallel_installer.rb:93:in `call'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/parallel_installer.rb:66:in `call'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer.rb:242:in `install_in_parallel'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer.rb:199:in `install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer.rb:87:in `block in run'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/process_lock.rb:9:in `open'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/process_lock.rb:9:in `lock'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer.rb:71:in `run'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer.rb:23:in `install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/cli/install.rb:63:in `run'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/cli.rb:247:in `block in install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/settings.rb:158:in `temporary'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/cli.rb:246:in `install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/cli.rb:35:in `dispatch'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/cli.rb:29:in `start'
  /usr/share/gems/gems/bundler-2.5.16/exe/bundle:28:in `block in <top (required)>'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/share/gems/gems/bundler-2.5.16/exe/bundle:20:in `<top (required)>'
  /usr/bin/bundle:25:in `load'
  /usr/bin/bundle:25:in `<main>'

An error occurred while installing base64 (0.2.0), and Bundler cannot continue.

In Gemfile:
  rails was resolved to 7.0.8, which depends on
    actioncable was resolved to 7.0.8, which depends on
      actionpack was resolved to 7.0.8, which depends on
        actionview was resolved to 7.0.8, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            activesupport was resolved to 7.0.8, which depends on
              base64

Bundler::HTTPError: Could not reach host index.rubygems.org. Check your network connection and try again.
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher/compact_index.rb:15:in `rescue in block in compact_index_request'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher/compact_index.rb:13:in `block in compact_index_request'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher.rb:232:in `block in fetchers'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher.rb:232:in `drop_while'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher.rb:232:in `fetchers'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/fetcher.rb:205:in `api_fetcher?'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:400:in `select'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:400:in `api_fetchers'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:405:in `block in remote_specs'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/index.rb:9:in `build'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:404:in `remote_specs'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:228:in `cached_built_in_gem'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/source/rubygems.rb:151:in `install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/parallel_installer.rb:117:in `install_serially'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/parallel_installer.rb:93:in `call'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer/parallel_installer.rb:66:in `call'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer.rb:242:in `install_in_parallel'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer.rb:199:in `install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer.rb:87:in `block in run'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/process_lock.rb:9:in `open'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/process_lock.rb:9:in `lock'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer.rb:71:in `run'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/installer.rb:23:in `install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/cli/install.rb:63:in `run'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/cli.rb:247:in `block in install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/settings.rb:158:in `temporary'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/cli.rb:246:in `install'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/cli.rb:35:in `dispatch'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/cli.rb:29:in `start'
  /usr/share/gems/gems/bundler-2.5.16/exe/bundle:28:in `block in <top (required)>'
  /usr/share/gems/gems/bundler-2.5.16/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/share/gems/gems/bundler-2.5.16/exe/bundle:20:in `<top (required)>'
  /usr/bin/bundle:25:in `load'
  /usr/bin/bundle:25:in `<main>'

An error occurred while installing base64 (0.2.0), and Bundler cannot continue.

In Gemfile:
  rails was resolved to 7.0.8, which depends on
    actioncable was resolved to 7.0.8, which depends on
      actionpack was resolved to 7.0.8, which depends on
        actionview was resolved to 7.0.8, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            activesupport was resolved to 7.0.8, which depends on
              base64
---END------------------------------------------------------------------


Exception `IOError' at /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:150 - closed stream
Exception `NoMethodError' at /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:165 - undefined method `join' for nil
Exception `IOError' at /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:150 - closed stream
Exception `NoMethodError' at /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:165 - undefined method `join' for nil
Exception `IOError' at /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:150 - closed stream
Exception `NoMethodError' at /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:165 - undefined method `join' for nil
Exception `IOError' at /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:150 - closed stream
Exception `NoMethodError' at /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:165 - undefined method `join' for nil
Exception `NoMethodError' at /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:210 - undefined method `join' for nil
Exception `LoadError' at /usr/share/ruby/bundled_gems.rb:75 - cannot load such file -- coderay

An error occurred while loading ./spec/unit/shoulda/matchers/action_controller/callback_matcher_spec.rb.
Failure/Error: require 'unit_spec_helper'

NoMethodError:
  undefined method `join' for nil
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:165:in `ensure in run'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:165:in `run'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:37:in `call'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:37:in `block in initialize'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:169:in `run_with_wrapper'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:176:in `run_with_debugging'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:66:in `block (2 levels) in call'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:196:in `possibly_running_quickly'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:65:in `block in call'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:202:in `possibly_retrying'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:64:in `call'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:11:in `block in run'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:9:in `run'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:16:in `run!'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/bundle.rb:43:in `install_gems'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/bundle.rb:24:in `updating'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/unit/rails_application.rb:177:in `update_gems'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/unit/rails_application.rb:22:in `block in create'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/filesystem.rb:31:in `chdir'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/filesystem.rb:31:in `within_project'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/unit/rails_application.rb:21:in `create'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/unit/load_environment.rb:7:in `<top (required)>'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/unit_spec_helper.rb:1:in `require_relative'
# /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/unit_spec_helper.rb:1:in `<top (required)>'
# ./spec/unit/shoulda/matchers/action_controller/callback_matcher_spec.rb:1:in `<top (required)>'
# ------------------
# --- Caused by: ---
# IOError:
#   closed stream
#   /builddir/build/BUILD/rubygem-shoulda-matchers-5.1.0-build/spec/support/tests/command_runner.rb:150:in `spawn'
No examples found.


Finished in 0.00003 seconds (files took 10.61 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
~~~

where I believe that these are the important bits:

~~~
An error occurred while installing base64 (0.2.0), and Bundler cannot continue.

In Gemfile:
  rails was resolved to 7.0.8, which depends on
    actioncable was resolved to 7.0.8, which depends on
      actionpack was resolved to 7.0.8, which depends on
        actionview was resolved to 7.0.8, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            activesupport was resolved to 7.0.8, which depends on
              base64

Bundler::HTTPError: Could not reach host index.rubygems.org. Check your network connection and try again.
~~~

So the issues is that either Bundler tries to reach to the internet (which is not available on purpose) or it cannot handle the default base64 gem. This was not problem with Ruby 3.3.4. So the difference is either Ruby and handling of default / bundled gems or Bundler which changed from 2.5.11 to 2.5.16 with the Ruby version bump

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

This is a regression from #7673, where Bundler will no longer respect the `--local` install flag if default gems are included in the Gemfile.

## What is your fix for the problem, implemented in this PR?

My fix is to make sure the installer respects the `--local` flag and avoids fetching `.gem` packages for default gems if `--local` was given.

Fixes #8025.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/spec/cache/gems_spec.rb [hunk 1]
```diff
@@ -149,9 +151,10 @@
     end
 
     context "when a remote gem is not available for caching" do
-      it "uses builtin gems when installing to system gems" do
+      it "warsn, but uses builtin gems when installing to system gems" do
```
Comment (voxik) [inline bundler/spec/cache/gems_spec.rb:154]: s/warsn/warns/
