### PR TITLE
ensure `default_path` and `home` are set for paths

### LINKED ISSUE #1510: Gems installed via --user-install missing from `gem list` in 2.6.0
My gems were all installed to `~/.gem/ruby/2.3.0` and it works fine in 2.5.2,
however after updated to 2.6.0, they're missing from `gem list` -- it now
shows no gems. On the other hand, I could still `require` them regularly.

Here's some demonstrating this:

I can require it:
```
> ruby -rrib -ve 'puts Rib::VERSION'
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin12.0]
1.2.91
```

I cannot find it via `gem list`

```
> gem list rib

*** LOCAL GEMS ***
```

I could find it if I set `GEM_HOME` to be `Gem.path.first`: ([Fish](http://fishshell.com/) command)

```
> env GEM_HOME=(ruby -e 'puts Gem.path.first') gem list rib

*** LOCAL GEMS ***

rib (1.2.91)
```

I believe something is wrong, and I haven't figured out which commit broke this.
It seems that somewhere is not respecting `Gem.path`

### PR DESCRIPTION
**Pull request by tenderlove**
When calling `use_paths` with nil values, `home` should be set to
`Gem.default_dir`, and `path` should be the default dir *plus* the home
dir.

Fixes #1510

### CODE REVIEW

File: lib/rubygems.rb [hunk 1]
```diff
@@ -956,7 +956,7 @@ def self.ui
   def self.use_paths(home, *paths)
     paths.flatten!
     paths.compact!
-    hash = { "GEM_HOME" => home, "GEM_PATH" => paths.join(File::PATH_SEPARATOR) }
+    hash = { "GEM_HOME" => home, "GEM_PATH" => paths.empty? ? home : paths.join(File::PATH_SEPARATOR) }
     hash.delete_if { |_, v| v.nil? }
```
Comment (segiddins) [inline lib/rubygems.rb]: alternatively, this could be `delete_if { |_, v| v.nil? || v.empty? }`

Comment (tenderlove) [inline lib/rubygems.rb]: Unless I misunderstand, I'm not sure if that is a viable alternative:

```
[aaron@TC rubygems (path_defaults)]$ git diff master
diff --git a/lib/rubygems.rb b/lib/rubygems.rb
index 53f7394..c71b0c7 100644
--- a/lib/rubygems.rb
+++ b/lib/rubygems.rb
@@ -957,7 +957,7 @@ module Gem
     paths.flatten!
     paths.compact!
     hash = { "GEM_HOME" => home, "GEM_PATH" => paths.join(File::PATH_SEPARATOR) }
-    hash.delete_if { |_, v| v.nil? }
+    hash.delete_if { |_, v| v.nil? || v.empty? }
     self.paths = hash
   end
 
diff --git a/test/rubygems/test_gem.rb b/test/rubygems/test_gem.rb
index 10f637f..94b1863 100644
--- a/test/rubygems/test_gem.rb
+++ b/test/rubygems/test_gem.rb
@@ -1010,6 +1010,17 @@ class TestGem < Gem::TestCase
     assert_equal expected, err
   end
 
+  def test_self_use_paths_with_nils
+    orig_home = ENV.delete 'GEM_HOME'
+    orig_path = ENV.delete 'GEM_PATH'
+    Gem.use_paths nil, nil
+    assert_equal Gem.default_dir, Gem.paths.home
+    assert_equal (Gem.default_path + [Gem.paths.home]).uniq, Gem.paths.path
+  ensure
+    ENV['GEM_HOME'] = orig_home
+    ENV['GEM_PATH'] = orig_path
+  end
+
   def test_self_use_paths
     util_ensure_gem_dirs
 
[aaron@TC rubygems (path_defaults)]$ rake test
/Users/aaron/.rbenv/versions/ruby-trunk/bin/ruby -w -Ilib:bin:test:. --disable-gems -e 'require "rubygems"; gem "minitest", "~> 4.0"; require "minitest/autorun"; require "test/rubygems/test_bundled_ca.rb"; require "test/rubygems/test_config.rb"; require "test/rubygems/test_deprecate.rb"; require "test/rubygems/test_gem.rb"; require "test/rubygems/test_gem_available_set.rb"; require "test/rubygems/test_gem_command.rb"; require "test/rubygems/test_gem_command_manager.rb"; require "test/rubygems/test_gem_commands_build_command.rb"; require "test/rubygems/test_gem_commands_cert_command.rb"; require "test/rubygems/test_gem_commands_check_command.rb"; require "test/rubygems/test_gem_commands_cleanup_command.rb"; require "test/rubygems/test_gem_commands_contents_command.rb"; require "test/rubygems/test_gem_commands_dependency_command.rb"; require "test/rubygems/test_gem_commands_environment_command.rb"; require "test/rubygems/test_gem_commands_fetch_command.rb"; require "test/rubygems/test_gem_commands_generate_index_command.rb"; require "test/rubygems/test_gem_commands_help_command.rb"; require "test/rubygems/test_gem_commands_install_command.rb"; require "test/rubygems/test_gem_commands_list_command.rb"; require "test/rubygems/test_gem_commands_lock_command.rb"; require "test/rubygems/test_gem_commands_mirror.rb"; require "test/rubygems/test_gem_commands_open_command.rb"; require "test/rubygems/test_gem_commands_outdated_command.rb"; require "test/rubygems/test_gem_commands_owner_command.rb"; require "test/rubygems/test_gem_commands_pristine_command.rb"; require "test/rubygems/test_gem_commands_push_command.rb"; require "test/rubygems/test_gem_commands_query_command.rb"; require "test/rubygems/test_gem_commands_search_command.rb"; require "test/rubygems/test_gem_commands_server_command.rb"; require "test/rubygems/test_gem_commands_setup_command.rb"; require "test/rubygems/test_gem_commands_sources_command.rb"; require "test/rubygems/test_gem_commands_specification_command.rb"; require "test/rubygems/test_gem_commands_stale_command.rb"; require "test/rubygems/test_gem_commands_uninstall_command.rb"; require "test/rubygems/test_gem_commands_unpack_command.rb"; require "test/rubygems/test_gem_commands_update_command.rb"; require "test/rubygems/test_gem_commands_which_command.rb"; require "test/rubygems/test_gem_commands_yank_command.rb"; require "test/rubygems/test_gem_config_file.rb"; require "test/rubygems/test_gem_dependency.rb"; require "test/rubygems/test_gem_dependency_installer.rb"; require "test/rubygems/test_gem_dependency_list.rb"; require "test/rubygems/test_gem_dependency_resolution_error.rb"; require "test/rubygems/test_gem_doctor.rb"; require "test/rubygems/test_gem_ext_builder.rb"; require "test/rubygems/test_gem_ext_cmake_builder.rb"; require "test/rubygems/test_gem_ext_configure_builder.rb"; require "test/rubygems/test_gem_ext_ext_conf_builder.rb"; require "test/rubygems/test_gem_ext_rake_builder.rb"; require "test/rubygems/test_gem_gem_runner.rb"; require "test/rubygems/test_gem_gemcutter_utilities.rb"; require "test/rubygems/test_gem_impossible_dependencies_error.rb"; require "test/rubygems/test_gem_indexer.rb"; require "test/rubygems/test_gem_install_update_options.rb"; require "test/rubygems/test_gem_installer.rb"; require "test/rubygems/test_gem_local_remote_options.rb"; require "test/rubygems/test_gem_name_tuple.rb"; require "test/rubygems/test_gem_package.rb"; require "test/rubygems/test_gem_package_old.rb"; require "test/rubygems/test_gem_package_tar_header.rb"; require "test/rubygems/test_gem_package_tar_reader.rb"; require "test/rubygems/test_gem_package_tar_reader_entry.rb"; require "test/rubygems/test_gem_package_tar_writer.rb"; require "test/rubygems/test_gem_package_task.rb"; require "test/rubygems/test_gem_path_support.rb"; require "test/rubygems/test_gem_platform.rb"; require "test/rubygems/test_gem_rdoc.rb"; require "test/rubygems/test_gem_remote_fetcher.rb"; require "test/rubygems/test_gem_request.rb"; require "test/rubygems/test_gem_request_connection_pools.rb"; require "test/rubygems/test_gem_request_set.rb"; require "test/rubygems/test_gem_request_set_gem_dependency_api.rb"; require "test/rubygems/test_gem_request_set_lockfile.rb"; require "test/rubygems/test_gem_request_set_lockfile_parser.rb"; require "test/rubygems/test_gem_request_set_lockfile_tokenizer.rb"; require "test/rubygems/test_gem_requirement.rb"; require "test/rubygems/test_gem_resolver.rb"; require "test/rubygems/test_gem_resolver_activation_request.rb"; require "test/rubygems/test_gem_resolver_api_set.rb"; require "test/rubygems/test_gem_resolver_api_specification.rb"; require "test/rubygems/test_gem_resolver_best_set.rb"; require "test/rubygems/test_gem_resolver_composed_set.rb"; require "test/rubygems/test_gem_resolver_conflict.rb"; require "test/rubygems/test_gem_resolver_dependency_request.rb"; require "test/rubygems/test_gem_resolver_git_set.rb"; require "test/rubygems/test_gem_resolver_git_specification.rb"; require "test/rubygems/test_gem_resolver_index_set.rb"; require "test/rubygems/test_gem_resolver_index_specification.rb"; require "test/rubygems/test_gem_resolver_installed_specification.rb"; require "test/rubygems/test_gem_resolver_installer_set.rb"; require "test/rubygems/test_gem_resolver_local_specification.rb"; require "test/rubygems/test_gem_resolver_lock_set.rb"; require "test/rubygems/test_gem_resolver_lock_specification.rb"; require "test/rubygems/test_gem_resolver_requirement_list.rb"; require "test/rubygems/test_gem_resolver_specification.rb"; require "test/rubygems/test_gem_resolver_vendor_set.rb"; require "test/rubygems/test_gem_resolver_vendor_specification.rb"; require "test/rubygems/test_gem_security.rb"; require "test/rubygems/test_gem_security_policy.rb"; require "test/rubygems/test_gem_security_signer.rb"; require "test/rubygems/test_gem_security_trust_dir.rb"; require "test/rubygems/test_gem_server.rb"; require "test/rubygems/test_gem_silent_ui.rb"; require "test/rubygems/test_gem_source.rb"; require "test/rubygems/test_gem_source_fetch_problem.rb"; require "test/rubygems/test_gem_source_git.rb"; require "test/rubygems/test_gem_source_installed.rb"; require "test/rubygems/test_gem_source_list.rb"; require "test/rubygems/test_gem_source_local.rb"; require "test/rubygems/test_gem_source_lock.rb"; require "test/rubygems/test_gem_source_specific_file.rb"; require "test/rubygems/test_gem_source_vendor.rb"; require "test/rubygems/test_gem_spec_fetcher.rb"; require "test/rubygems/test_gem_specification.rb"; require "test/rubygems/test_gem_stream_ui.rb"; require "test/rubygems/test_gem_stub_specification.rb"; require "test/rubygems/test_gem_text.rb"; require "test/rubygems/test_gem_uninstaller.rb"; require "test/rubygems/test_gem_unsatisfiable_dependency_error.rb"; require "test/rubygems/test_gem_uri_formatter.rb"; require "test/rubygems/test_gem_util.rb"; require "test/rubygems/test_gem_validator.rb"; require "test/rubygems/test_gem_version.rb"; require "test/rubygems/test_gem_version_option.rb"; require "test/rubygems/test_kernel.rb"; require "test/rubygems/test_require.rb"' -- 
/Users/aaron/git/rubygems/test/rubygems/test_gem_commands_open_command.rb:45: warning: assigned but unused variable - spec
Run options: --seed 38858

# Running tests:

........................................F..................................F...................F...........................................................................................................................................F................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished tests in 37.892473s, 49.7196 tests/s, 148.2089 assertions/s.

  1) Failure:
TestGem#test_self_path_ENV_PATH [/Users/aaron/git/rubygems/test/rubygems/test_gem.rb:651]:
extra path components: ["/var/folders/dv/kf69sc1162s1h7jmwk9383_h0000gn/T/home20160226-95741-g7nin5"].
Expected: 4
  Actual: 3

  2) Failure:
TestGem#test_self_path [/Users/aaron/git/rubygems/test/rubygems/test_gem.rb:597]:
--- expected
+++ actual
@@ -1 +1,2 @@
-["/private/var/folders/dv/kf69sc1162s1h7jmwk9383_h0000gn/T/test_rubygems_95741/gemhome"]
+["/var/folders/dv/kf69sc1162s1h7jmwk9383_h0000gn/T/path20160226-95741-alkt0z",
+ "/private/var/folders/dv/kf69sc1162s1h7jmwk9383_h0000gn/T/test_rubygems_95741/gemhome"]


  3) Failure:
TestGem#test_self_clear_paths [/Users/aaron/git/rubygems/test/rubygems/test_gem.rb:210]:
Expected /gemhome$/ to match "/var/folders/dv/kf69sc1162s1h7jmwk9383_h0000gn/T/path20160226-95741-alkt0z".

  4) Failure:
TestGemCommandsEnvironmentCommand#test_execute_gempath [/Users/aaron/git/rubygems/test/rubygems/test_gem_commands_environment_command.rb:73]:
--- expected
+++ actual
@@ -1,2 +1,2 @@
-"/private/var/folders/dv/kf69sc1162s1h7jmwk9383_h0000gn/T/test_rubygems_95741/gemhome
+"/var/folders/dv/kf69sc1162s1h7jmwk9383_h0000gn/T/path20160226-95741-alkt0z:/private/var/folders/dv/kf69sc1162s1h7jmwk9383_h0000gn/T/test_rubygems_95741/gemhome
 "


1884 tests, 5616 assertions, 4 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [/Users/aaron/.rbenv/versions/ruby-trunk/bi...]

Tasks: TOP => test
(See full trace by running task with --trace)
[aaron@TC rubygems (path_defaults)]$ 
```

**Comment by segiddins** [comment]
This should've been merged via `homu` now that we have it setup

**Comment by drbrain** [comment]
Where is `homu` documented?  I don't see in in the policies or contributing documents.

**Comment by segiddins** [comment]
@indirect ^

**Comment by godfat** [comment]
That means we're still passing `nil` as GEM_PATH. I am really confused :x I'll try this later, thanks!
