### PR TITLE
Fix missing require breaking `gem cert`

### LINKED ISSUE #4463: uninitialized constant Gem::Security::TrustDir::FileUtils
I'm having a problem or would like to suggest a feature.

My current problem is `uninitialized constant Gem::Security::TrustDir::FileUtils`

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.3.0.dev
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

When trying to run gem --cert I get the following failure:

```
ruby -Ilib bin/gem --backtrace cert --add /root/sigruby/certs/lukehinds_pub.pem 
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::Security::TrustDir::FileUtils
Did you mean?  FileTest
	/root/rubygems/lib/rubygems/security/trust_dir.rb:114:in `verify'
	/root/rubygems/lib/rubygems/security/trust_dir.rb:91:in `trust_cert'
	/root/rubygems/lib/rubygems/commands/cert_command.rb:95:in `add_certificate'
	/root/rubygems/lib/rubygems/commands/cert_command.rb:102:in `block in execute'
	/root/rubygems/lib/rubygems/commands/cert_command.rb:101:in `each'
	/root/rubygems/lib/rubygems/commands/cert_command.rb:101:in `execute'
	/root/rubygems/lib/rubygems/command.rb:323:in `invoke_with_build_args'
	/root/rubygems/lib/rubygems/command_manager.rb:178:in `process_args'
	/root/rubygems/lib/rubygems/command_manager.rb:147:in `run'
	/root/rubygems/lib/rubygems/gem_runner.rb:53:in `run'
	bin/gem:15:in `<main>'
```

This is due to a missing requires in `rubygems/security/trust_dir.rb`

PR incoming

### PR DESCRIPTION
**Pull request by lukehinds**
See issue #4463 for more details.

This fix sets the required dependency needed for
`Gem::Security::TrustDir`

Signed-off-by: Luke Hinds <lhinds@redhat.com>

Fixes #4463.

## What was the end-user or developer problem that led to this PR?

A missing requires has broken the ability to use the `gem cert`  and add a public key

## What is your fix for the problem, implemented in this PR?

Set  `require 'fileutils'` in `trust_dir.rb`

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: lib/rubygems/security/trust_dir.rb [hunk 1]
```diff
@@ -3,6 +3,8 @@
 # The TrustDir manages the trusted certificates for gem signature
 # verification.
 
+require 'fileutils'
```
Comment (deivid-rodriguez) [inline lib/rubygems/security/trust_dir.rb:6]: Can you move the require inline right before the usage causing issues? Sometimes requiring default gems at the top level causing activation issues with default gems, so we prefer lazily requiring them.

Comment (lukehinds) [reply lib/rubygems/security/trust_dir.rb]: Thanks @deivid-rodriguez , https://github.com/rubygems/rubygems/pull/4464/commits/039a290cf1f907c0e6197dac66d1937dee23459b moves inline

**Comment by djberg96** [comment]
👍🏻

File: lib/rubygems/security/trust_dir.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply lib/rubygems/security/trust_dir.rb]: Nice! Can you rebase and squash everything into a single commit?
