### PR TITLE
Prioritise gems with higher version for fetching metadata, and stop fetching once we find a valid candidate

### LINKED ISSUE #4603: Cannot install ruby gem from rubygems.pkg.github.com without specifying the version.
I'm having a problem or would like to suggest a feature.

My current problem is I cannot install a gem from Github packages `rubygems.pkg.github.com` without specifying the version.

With version `3.2.17`

```sh
❯ gem --version
3.2.17

❯ gem install REDACTED_GEM_NAME --verbose
HEAD https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/
404 Not Found
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/prerelease_specs.4.8.gz
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/specs.4.8.gz
200 OK
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/REDACTED_GEM_NAME
404 Not Found
GET https://index.rubygems.org/prerelease_specs.4.8.gz
304 Not Modified
GET https://index.rubygems.org/specs.4.8.gz
304 Not Modified
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/quick/Marshal.4.8/REDACTED_GEM_NAME-0.gemspec.rz
404 Not Found
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/quick/Marshal.4.8/REDACTED_GEM_NAME-0.gemspec.rz)
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/remote_fetcher.rb:239:in `fetch_http'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/remote_fetcher.rb:255:in `fetch_path'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/source.rb:151:in `fetch_spec'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/index_specification.rb:96:in `spec'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/index_specification.rb:43:in `required_ruby_version'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/installer_set.rb:250:in `metadata_satisfied?'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/installer_set.rb:81:in `block in add_always_install'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/installer_set.rb:80:in `select'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/installer_set.rb:80:in `add_always_install'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/dependency_installer.rb:322:in `resolve_dependencies'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/commands/install_command.rb:198:in `install_gem'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/commands/install_command.rb:223:in `block in install_gems'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/commands/install_command.rb:216:in `each'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/commands/install_command.rb:216:in `install_gems'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/commands/install_command.rb:164:in `execute'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/command.rb:323:in `invoke_with_build_args'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/command_manager.rb:178:in `process_args'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/command_manager.rb:147:in `run'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/gem_runner.rb:53:in `run'
	.../.asdf/installs/ruby/2.7.2/bin/gem:15:in `<main>'

```

I can install the gem using by specifying the version
```sh 
❯ gem env version
3.2.17

❯ gem install REDACTED_GEM_NAME --version 0.5.2 --verbose
HEAD https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/
404 Not Found
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/prerelease_specs.4.8.gz
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/specs.4.8.gz
200 OK
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/REDACTED_GEM_NAME
404 Not Found
GET https://index.rubygems.org/prerelease_specs.4.8.gz
304 Not Modified
GET https://index.rubygems.org/specs.4.8.gz
304 Not Modified
 ...
Successfully installed REDACTED_GEM_NAME-0.5.2
1 gem installed
```

Note this was working with an earlier version like `3.1.4` 
```sh
❯ gem --version
3.1.4

❯ gem install REDACTED_GEM_NAME --verbose
HEAD https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies
200 OK
HEAD https://rubygems.org/api/v1/dependencies
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=REDACTED_GEM_NAME
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=REDACTED_GEM_NAME
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=activesupport,httparty,thor,tty-command,tty-logger,tty-which,zeitwerk
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=activesupport,httparty,thor,tty-command,tty-logger,tty-which,zeitwerk
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=pastel
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=pastel
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=tty-color
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=tty-color
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=mime-types,multi_xml
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=mime-types,multi_xml
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=mime-types-data
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=mime-types-data
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=concurrent-ruby,i18n,minitest,tzinfo
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=concurrent-ruby,i18n,minitest,tzinfo
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/quick/Marshal.4.8/REDACTED_GEM_NAME.gemspec.rz
200 OK

```

This issue is related to:

  - [ ] Network problems
  - [ X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.2.17
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by intuxicated**
## What was the end-user or developer problem that led to this PR?

Github has an issue in which it will generate a misleading prerelease output in its RubyGems server API and returns a 0 version for the gem while it doesn't exist.

## What is your fix for the problem, implemented in this PR?

Verifying metadata (which needs a network request to fetch the full gemspec) in order of priority until a valid gem is found, instead of fetching all gemspec candidates unconditionally, avoids the issue.

Fixes #4603.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: lib/rubygems/source.rb [hunk 1]
```diff
@@ -194,7 +194,15 @@ def load_specs(type)
     spec_dump = fetcher.cache_update_path spec_path, local_file, update_cache?
 
     begin
-      Gem::NameTuple.from_list Marshal.load(spec_dump)
+      gem_name_tuples = Gem::NameTuple.from_list Marshal.load(spec_dump)
+
+      if type == :prerelease && is_uri_for_github_rubygems?(uri) && gem_name_tuples.length > 0 && gem_name_tuples.all? {|t| t.version == Gem::Version.new(0) }
```
Comment (intuxicated) [inline lib/rubygems/source.rb:199]: I think it would be better to capture the if condition into a private function. I'll do it after I got the ✅ .

Comment (intuxicated) [reply lib/rubygems/source.rb:199]: Let's go through the conditions:

1. That GitHub issue is only happening for the `prerelease.x.x.gz` file so I thought it would be good to have it as a condition here.
2. making sure the URL is for the GitHub RubyGems server.
3. make sure at least one gem tuple name has been generated
4. make sure at least one gem tuple with version 0 exist

Technically, using version `0.0.0` is not against the Semantic Versioning so I didn't want to blindly warn users for using the `0` or `0.0.0` version. [It's discussed here too.](https://github.com/semver/semver/issues/363)
Also, a user could actually create a `0.0.0` gem in the GitHub Rubygems repository so I thought it wouldn't be a good idea to raise an exception to break the process.

File: test/rubygems/test_gem_source_github_problem.rb [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+    super
+
+    @gem_repo = "https://username:secure_token@rubygems.pkg.github.com/username"
+
+    spec_fetcher
+
+    @source = Gem::Source.new(@gem_repo)
+  end
+
+  def test_load_specs_for_prerelease_0
```
Comment (intuxicated) [inline test/rubygems/test_gem_source_github_problem.rb:16]: When fetching `prerelease` and response contains a gem with version `0` from a Github Rubygems server.

File: test/rubygems/test_gem_source_github_problem.rb [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+    released = nil
+    _out, err = capture_output do
+      released = @source.load_specs(:prerelease).map {|spec| spec.full_name }
+    end
+
+    assert_equal released, %w[a-0]
+    assert_match expected_warning_message, err
+  end
+
+  def test_load_specs_for_a_valid_prerelease
```
Comment (intuxicated) [inline test/rubygems/test_gem_source_github_problem.rb:34]: When fetching `prerelease` and response contains a gem with a valid pre-released version `0.0.1.pre` from a Github Rubygems server.

File: .github/workflows/cancel.yml [hunk 4]
```diff
@@ -0,0 +1,14 @@
+name: Cancel
```
Comment (intuxicated) [inline .github/workflows/cancel.yml:1]: I think this could be useful. but ignore it for now. I'll create another PR to include this if we like it.

Comment (deivid-rodriguez) [reply .github/workflows/cancel.yml:1]: I'm in favour of adding this, our CI is heavy, any savings in terms of unnecessary CI time are welcomed both by us and probably GitHub too. I'm sure they're planning to have this built-in at some point, but in the mean time a separate action seems great!

Can you create the PR?

File: lib/rubygems/source.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply lib/rubygems/source.rb:199]: I see.

My initial idea was meant to be completely independent from GitHub, so not require any hard-coded checks like the ones here.

Initially I thought of warning this case, but then I realized we might not need to warn this case at all, but instead avoid fetching this invalid URI at all, since it's unneeded.

These invalid URIs correspond to `0.0.0` versions which, even if valid as you point out, it should always take the lowest precedence, so as long as we can find other gems with higher version in the index that don't have this problem, we shouldn't have to resort to fetching this URL at all.

From looking at the backtrace of the error, it comes from here:

https://github.com/rubygems/rubygems/blob/c693b899c48197b6411dfac43e80f2c36eb6961a/lib/rubygems/resolver/installer_set.rb#L80-L96

I think, if you change that `found.select` to `found.reverse.find`, then you avoid fetching all potential specs, and instead fetch them one by one in order of priority. If you make this change, you need to also avoid the surrounding code to catch up with the fact that we're now expecting either `nil` or a spec, rather than either an empty array or a non-empty array of specs.

It's completely untested, but hopefully you get the idea and can verify whether it works.

File: .github/workflows/cancel.yml (hunk 4 above)
Comment (intuxicated) [reply .github/workflows/cancel.yml:1]: Sure. It's coming.

File: lib/rubygems/source.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply lib/rubygems/source.rb:199]: @intuxicated I didn't verify whether it fixes the issue since I didn't setup an environment to reproduce it, but I did check that my suggestion breaks no existing specs, which is something. The specific diff would be

```diff
diff --git a/lib/rubygems/resolver/installer_set.rb b/lib/rubygems/resolver/installer_set.rb
index 60181315b0..f4fee351a5 100644
--- a/lib/rubygems/resolver/installer_set.rb
+++ b/lib/rubygems/resolver/installer_set.rb
@@ -77,11 +77,11 @@ def add_always_install(dependency)
     newest = found.last
 
     unless @force
-      found_matching_metadata = found.select do |spec|
+      found_matching_metadata = found.reverse.find do |spec|
         metadata_satisfied?(spec)
       end
 
-      if found_matching_metadata.empty?
+      if found_matching_metadata.nil?
         if newest
           ensure_required_ruby_version_met(newest.spec)
           ensure_required_rubygems_version_met(newest.spec)
@@ -92,7 +92,7 @@ def add_always_install(dependency)
           raise exc
         end
       else
-        newest = found_matching_metadata.last
+        newest = found_matching_metadata
       end
     end
```

Comment (intuxicated) [reply lib/rubygems/source.rb:199]: Thanks @deivid-rodriguez

**Review by deivid-rodriguez — APPROVED** [review]
It looks good to me!

I wasn't sure how to word the title, since this is technically independent from GitHub packages, although the realworld issue this is fixing is not being able to `gem install` from there. :thinking:

File: lib/rubygems/source.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply lib/rubygems/source.rb]: It worked!

**Comment by intuxicated** [comment]
:shipit:
