### PR TITLE
Fix Bundler not choosing the platform specific version for libv8-node and other allowlisted gems

### LINKED ISSUE #6165: Bundler 2.3.26 ignores the precompiled libv8-node on x86_64-linux on TruffleRuby
### Describe the problem as clearly as you can

Given this Gemfile:
```ruby
source 'https://rubygems.org'
                  
gem 'mini_racer'
```

If I use CRuby 3.1.3 and Bundler 2.3.26, `bundle lock` gives:
```
GEM
  remote: https://rubygems.org/
  specs:
    libv8-node (16.10.0.0-x86_64-linux)
    mini_racer (0.6.3)
      libv8-node (~> 16.10.0.0)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  mini_racer

BUNDLED WITH
   2.3.26
```
which is expected and looks fine (and `bundle install` just fetches the binary gem).

Now if I switch to TruffleRuby, here I use truffleruby-dev (from ruby-build).
With Bundler 2.3.7 (which TruffleRuby currently comes with), it works although it chooses x86_64-linux-musl which is a bit weird (#5508).
```
$ rm Gemfile.lock
$ bundle lock
$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    libv8-node (16.10.0.0)
    mini_racer (0.6.3)
      libv8-node (~> 16.10.0.0)

PLATFORMS
  ruby

DEPENDENCIES
  mini_racer

BUNDLED WITH
   2.3.7
$ bundle install
Fetching gem metadata from https://rubygems.org/..
Using bundler 2.3.7
Fetching libv8-node 16.10.0.0 (x86_64-linux-musl)
Installing libv8-node 16.10.0.0 (x86_64-linux-musl)
Fetching mini_racer 0.6.3
Installing mini_racer 0.6.3 with native extensions
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Bundled gems are installed into `/home/eregon/.bundle`
```

But with the latest Bundler, Bundler 2.3.26 it fails, i.e., it doesn't use the precompiled gem:
```
$ gem i bundler
Fetching bundler-2.3.26.gem
Successfully installed bundler-2.3.26
1 gem installed
$ rm Gemfile.lock
$ bundle lock
$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    libv8-node (16.10.0.0)
    mini_racer (0.6.3)
      libv8-node (~> 16.10.0.0)

PLATFORMS
  ruby

DEPENDENCIES
  mini_racer

BUNDLED WITH
   2.3.26
$ bundle install
Fetching gem metadata from https://rubygems.org/..
Using bundler 2.3.26
Installing libv8-node 16.10.0.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```
Just in case:
```
$ ruby -ve 'p Gem::Platform.local'
truffleruby 23.0.0-dev-bdd53f99, like ruby 3.1.2, GraalVM CE Native [x86_64-linux]
#<Gem::Platform:0x768 @cpu="x86_64", @os="linux", @version=nil>
```

This is causing issues while updating TruffleRuby to Ruby 3.1.3 which uses Bundler 2.3.26.

### Did you try upgrading rubygems & bundler?

Yes I tried latest Bundler.

### What actually happened?

See above.

## Environment

```
Bundler       2.3.26
  Platforms   ruby
Ruby          3.1.2p0 (2022-12-19 revision bdd53f99afd36be2eda0aa823db7230b7ad972e8) [x86_64-linux]
  Full Path   /home/eregon/.rubies/truffleruby-dev/bin/ruby
  Config Dir  /home/runner/work/truffleruby-dev-builder/truffleruby-dev-builder/etc
RubyGems      3.3.7
  Gem Home    /home/eregon/.rubies/truffleruby-dev/lib/gems
  Gem Path    /home/eregon/.gem/truffleruby/3.1.2.4:/home/eregon/.rubies/truffleruby-dev/lib/gems
  User Home   /home/eregon
  User Path   /home/eregon/.gem/truffleruby/3.1.2.4
  Bin Dir     /home/eregon/.rubies/truffleruby-dev/bin
Tools         
  Git         2.37.2
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2022-11-17
Git SHA           23ec5b8501
Released Version  true
```

## Bundler settings

```
path
  Set for the current user (/home/eregon/.bundle/config): "/home/eregon/.bundle"
```

### Gemfile

```ruby
source 'https://rubygems.org'
                  
gem 'mini_racer'
```

### Gemfile.lock

```
<No /home/eregon/code/truffleruby-ws/truffleruby/Gemfile.lock found>
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

This was supposed to have been fixed, but Bundler was still not able to choose the precompiled version of those gems that truffleruby has deemed as having precompiled versions that work fine with truffleruby.

This reintroduces the approach in https://github.com/rubygems/rubygems/pull/4049/commits/6085de09c711f072ddd9fa06d125a6da65ebc501, which was reverted at https://github.com/rubygems/rubygems/pull/5711 because it caused some issues. Unfortunately the revert created the original problem again, due to a problem with the spec initially added that was not able to properly cover the fix.

## What is your fix for the problem, implemented in this PR?

Reintroduce the same approach of setting a proper default value for the `:force_ruby_platform` dependency attribute, and to locked specifications. This approach no longer seem to cause any issues.

Also fix our specs to properly cover the issue.

Fixes #6165.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] ~Write~ Fix [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/lib/bundler/rubygems_ext.rb [hunk 1]
```diff
@@ -277,6 +282,10 @@ def normalized_linux_version_ext
         without_gnu_nor_abi_modifiers
       end
     end
+
+    if RUBY_ENGINE == "truffleruby" && !defined?(REUSE_AS_BINARY_ON_TRUFFLERUBY)
+      REUSE_AS_BINARY_ON_TRUFFLERUBY = %w[libv8 libv8-node sorbet-static].freeze
+    end
```
Comment (deivid-rodriguez) [inline bundler/lib/bundler/rubygems_ext.rb:288]: Later I will propose that truffleruby moves this constant to the `defaults/truffleruby` file, so that eventually we no longer need to keep it ourselves. We currently need to keep it ourselves for our own tests, and to work properly with upgraded copies of RubyGems that don't include it like the "blessed copy" of RubyGems included with truffleruby does.

Comment (eregon) [reply bundler/lib/bundler/rubygems_ext.rb:288]: Should I do a PR to truffleruby to have
```ruby
class Gem::Platform
  remove_const :REUSE_AS_BINARY_ON_TRUFFLERUBY if const_defined?(:REUSE_AS_BINARY_ON_TRUFFLERUBY)
  REUSE_AS_BINARY_ON_TRUFFLERUBY = %w[libv8 libv8-node sorbet-static]
end
```
in `defaults/truffleruby` then?
I can do that soon.

Or where you thinking of something else?

Comment (deivid-rodriguez) [reply bundler/lib/bundler/rubygems_ext.rb:288]: Yup, that's what I was thinking.

Comment (eregon) [reply bundler/lib/bundler/rubygems_ext.rb:288]: Depending on https://github.com/rubygems/rubygems/pull/6238#issuecomment-1372313641 we might need to remove the constant

Comment (deivid-rodriguez) [reply bundler/lib/bundler/rubygems_ext.rb:288]: Yep, you shouldn't need `remove_const` because of that.
