### PR TITLE
Fix default gem executable installation when folder is not `bin/`

### LINKED ISSUE #2646: `gem install --default` installs executables from `bin` unconditionally
On a clean docker image of latest trunk:

``` 
$ gem --version
3.1.0.pre1
$ irb --version
irb 1.0.0 (2018-12-18)
$ gem install irb:1.0.0 --default
Fetching irb-1.0.0.gem
Successfully installed irb-1.0.0 as a default gem
Done installing documentation for irb after 0 seconds
1 gem installed
$ irb --version
Traceback (most recent call last):
	1: from /usr/local/bin/irb:23:in `<main>'
/usr/local/bin/irb:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.0.0/exe/irb $ ls -ld /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.0.0/*
drwxr-xr-x    2 root     root          4096 Feb 15 10:34 /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.0.0/bin
$ ls -la /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.0.0/bin/
total 16
drwxr-xr-x    2 root     root          4096 Feb 15 10:34 .
drwxr-xr-x    3 root     root          4096 Feb 15 10:34 ..
-rwxr-xr-x    1 root     root            96 Feb 15 10:34 console
-rwxr-xr-x    1 root     root            74 Feb 15 10:34 setup

```

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

I have a fix for this, I'll open a PR as soon as #2644 is merged since I'm using the helper introduced in that PR for the test.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

Fixes #2646 by making sure executables are extracted to the proper folder.

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

File: lib/rubygems/installer.rb [hunk 1]
```diff
@@ -844,7 +844,7 @@ def extract_files
   # without the full gem installed.
 
   def extract_bin
-    @package.extract_files gem_dir, "bin/*"
+    @package.extract_files gem_dir, "#{spec.bindir}/*"
```
Comment (hsbt) [inline lib/rubygems/installer.rb]: 👍

**Comment by hsbt** [comment]
@bundlerbot r+
