### PR TITLE
Fix `ENAMETOOLONG` error when creating compact index cache

### LINKED ISSUE #5505: Errno::ENAMETOOLONG when running bundle install with non-rubygems source
### Describe the problem as clearly as you can

Bundle install fails with `Errno::ENAMETOOLONG: File name too long` on Github Actions.

```
bundle config set --global [organization].jfrog.io [credentials]
bundle install
```

Using JFrog's artifactory rather than RubyGems on GithubActions, it fails with `Errno::ENAMETOOLONG: File name too long`

```
There was an error accessing
`/home/runner/.bundle/cache/compact_index/[organization].jfrog.io.[redacted in GHA logs, most likely the password].443.[some hash]/info`.
The underlying system error is Errno::ENAMETOOLONG: File name too long @
dir_s_mkdir -
/home/runner/.bundle/cache/compact_index/[organization].jfrog.io.[redacted in GHA logs, most likely the password].443.[some hash]
```

I tried setting `BUNDLE_GLOBAL_GEM_CACHE=true` to see if that would bypass the gem source specific filenames/directories, but ran into the exact same error.

### Did you try upgrading rubygems & bundler?

Yes. 

### Post steps to reproduce the problem

`gem update --system` ran on the action, first.

* Configure Gemfile source to jfrog.io `source 'https://[organization].jfrog.io/artifactory/api/gems/[bundle name]/'`
* Bundle install locally
* Run `bundle install` on github actions (runner `ubuntu-latest`)
* Fails with file name too long error

```
RUBY VERSION
   ruby 3.1.2p20

BUNDLED WITH
   2.3.12
```

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Install gems from JFrog Artifactory source

### What actually happened?

Bundle install failed due to a filename which was too long

## Environment

```
Bundler       2.3.12
  Platforms   ruby, x86_64-linux
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]
  Full Path   /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/ruby
  Config Dir  /opt/hostedtoolcache/Ruby/3.1.2/x64/etc
RubyGems      3.3.12
  Gem Home    /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0
  Gem Path    /home/runner/.local/share/gem/ruby/3.1.0:/opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0
  User Home   /home/runner
  User Path   /home/runner/.local/share/gem/ruby/3.1.0
  Bin Dir     /opt/hostedtoolcache/Ruby/3.1.2/x64/bin
Tools         
  Git         2.36.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-04-20
Git SHA           75031e03f4
Released Version  true
```

## Bundler settings

```
[organization].jfrog.io
  Set for the current user (/home/runner/.bundle/config): "***"
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://[organization].jfrog.io/artifactory/api/gems/[gem bundle]/'
ruby '3.1.2'

gem 'activesupport'
gem 'aws-sdk-s3', '~> 1'
gem 'ddtrace'
gem 'dogstatsd-ruby'
gem 'hermes_messenger_of_the_gods', '~> 2.2.0'
gem 'instrument_all_the_things', '~> 1.3.0'
gem 'pry'
gem 'restforce', '~> 5'

group :test do
  gem 'coveralls', '~>0.8.23', require: false
  gem 'deep-cover', require: false
  gem 'factory_bot'
  gem 'rspec', '3.9.0'
  gem 'rubocop', '1.20.0'
  gem 'simplecov', '~> 0.16.1'
  gem 'timecop'
  gem 'webmock'
end

group :development do
  gem 'bundle-audit'
  gem 'dotenv'
  gem 'fasterer'
  gem 'grpc-tools'
  gem 'overcommit'
end
```

### Gemfile.lock

```
GEM
  remote: https://[organization].jfrog.io/artifactory/api/gems/[gem bundle]/
  specs:
    activemodel (7.0.2.4)
      activesupport (= 7.0.2.4)
    activesupport (7.0.2.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    ast (2.4.2)
    aws-eventstream (1.2.0)
    aws-partitions (1.581.0)
    aws-sdk-core (3.130.2)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.525.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.56.0)
      aws-sdk-core (~> 3, >= 3.127.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.113.2)
      aws-sdk-core (~> 3, >= 3.127.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sdk-sns (1.53.0)
      aws-sdk-core (~> 3, >= 3.127.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-sqs (1.51.0)
      aws-sdk-core (~> 3, >= 3.127.0)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.5.0)
      aws-eventstream (~> 1, >= 1.0.2)
    backports (3.23.0)
    binding_of_caller (1.0.0)
      debug_inspector (>= 0.0.1)
    bundle-audit (0.1.0)
      bundler-audit
    bundler-audit (0.9.0.1)
      bundler (>= 1.2.0, < 3)
      thor (~> 1.0)
    childprocess (4.1.0)
    coderay (1.1.3)
    colorize (0.8.1)
    concurrent-ruby (1.1.10)
    coveralls (0.8.23)
      json (>= 1.8, < 3)
      simplecov (~> 0.16.1)
      term-ansicolor (~> 1.3)
      thor (>= 0.19.4, < 2.0)
      tins (~> 1.6)
    crack (0.4.5)
      rexml
    ddtrace (0.54.2)
      debase-ruby_core_source (<= 0.10.14)
      msgpack
    debase-ruby_core_source (0.10.14)
    debug_inspector (1.1.0)
    deep-cover (1.1.0)
      deep-cover-core (= 1.1.0)
      highline
      thor (>= 0.20.3)
      with_progress
    deep-cover-core (1.1.0)
      backports (>= 3.11.0)
      binding_of_caller
      parser (>= 2.5)
      pry
      term-ansicolor
      terminal-table
    diff-lcs (1.5.0)
    docile (1.4.0)
    dogstatsd-ruby (5.4.0)
    dotenv (2.7.6)
    factory_bot (6.2.1)
      activesupport (>= 5.0.0)
    faraday (1.8.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0.1)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.1)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday_middleware (1.2.0)
      faraday (~> 1.0)
    fasterer (0.10.0)
      colorize (~> 0.7)
      ruby_parser (>= 3.19.1)
    grpc-tools (1.45.0)
    hashdiff (1.0.1)
    hashie (5.0.0)
    hermes_messenger_of_the_gods (2.2.0)
      activemodel (> 4.2.3)
      activesupport (> 4.2.3)
      aws-sdk-sns (~> 1.0)
      aws-sdk-sqs (~> 1.0)
      rexml
      thor
    highline (2.0.3)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    iniparse (1.5.0)
    instrument_all_the_things (1.3.0)
      ddtrace
      dogstatsd-ruby
    jmespath (1.6.1)
    json (2.6.1)
    jwt (2.3.0)
    method_source (1.0.0)
    minitest (5.15.0)
    msgpack (1.5.1)
    multipart-post (2.1.1)
    overcommit (0.58.0)
      childprocess (>= 0.6.3, < 5)
      iniparse (~> 1.4)
      rexml (~> 3.2)
    parallel (1.22.1)
    parser (3.1.2.0)
      ast (~> 2.4.1)
    pry (0.14.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    public_suffix (4.0.7)
    rainbow (3.1.1)
    regexp_parser (2.3.1)
    restforce (5.2.4)
      faraday (>= 0.9.0, < 1.9.0)
      faraday_middleware (>= 0.8.8, <= 2.0)
      hashie (>= 1.2.0, < 6.0)
      jwt (>= 1.5.6)
    rexml (3.2.5)
    rspec (3.9.0)
      rspec-core (~> 3.9.0)
      rspec-expectations (~> 3.9.0)
      rspec-mocks (~> 3.9.0)
    rspec-core (3.9.3)
      rspec-support (~> 3.9.3)
    rspec-expectations (3.9.4)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-mocks (3.9.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-support (3.9.4)
    rubocop (1.20.0)
      parallel (~> 1.10)
      parser (>= 3.0.0.0)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml
      rubocop-ast (>= 1.9.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.17.0)
      parser (>= 3.1.1.0)
    ruby-progressbar (1.11.0)
    ruby2_keywords (0.0.5)
    ruby_parser (3.19.1)
      sexp_processor (~> 4.16)
    sexp_processor (4.16.1)
    simplecov (0.16.1)
      docile (~> 1.1)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)
    sync (0.5.0)
    term-ansicolor (1.7.1)
      tins (~> 1.0)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    thor (1.2.1)
    timecop (0.9.5)
    tins (1.31.0)
      sync
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.1.0)
    webmock (3.14.0)
      addressable (>= 2.8.0)
      crack (>= 0.3.2)
      hashdiff (>= 0.4.0, < 2.0.0)
    with_progress (1.0.1)
      ruby-progressbar (~> 1.4)

PLATFORMS
  ruby

DEPENDENCIES
  activesupport
  aws-sdk-s3 (~> 1)
  bundle-audit
  coveralls (~> 0.8.23)
  ddtrace
  deep-cover
  dogstatsd-ruby
  dotenv
  factory_bot
  fasterer
  grpc-tools
  hermes_messenger_of_the_gods (~> 2.2.0)
  instrument_all_the_things (~> 1.3.0)
  overcommit
  pry
  restforce (~> 5)
  rspec (= 3.9.0)
  rubocop (= 1.20.0)
  simplecov (~> 0.16.1)
  timecop
  webmock

RUBY VERSION
   ruby 3.1.2p20

BUNDLED WITH
   2.3.12
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

If a custom rubygems source URI is long enough, Bundler may end up raising an `ENAMETOOLONG` error and crash.

## What is your fix for the problem, implemented in this PR?

The fix is to trim the cache slug size to fit usual OS requirements.

Fixes #5505.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by martinemde** [comment]
@deivid-rodriguez Any reason this shouldn't merge? Seems good.

**Review by martinemde — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
I don't recall, I think I did not get CI green in the first pass and then abandoned the PR. Feel free to move it forward if it looks good to you!

File: bundler/spec/install/global_cache_spec.rb [hunk 1]
```diff
@@ -49,6 +53,16 @@ def source2_global_cache(*segments)
       expect(err).to include("Gem::Package::FormatError: package metadata is missing in #{source_global_cache("rack-1.0.0.gem")}")
     end
 
+    it "uses a shorter path for the cache to not hit filesystem limits" do
+      install_gemfile <<-G, :artifice => "compact_index", :verbose => true
```
Comment (segiddins) [inline bundler/spec/install/global_cache_spec.rb:57]:
```suggestion
      install_gemfile <<-G, artifice: "compact_index", verbose: true
```

File: bundler/lib/bundler/source/rubygems/remote.rb [hunk 2]
```diff
@@ -16,6 +16,8 @@ def initialize(uri)
           @anonymized_uri = remove_auth(@uri).freeze
         end
 
+        MAX_CACHE_SLUG_SIZE = 255
```
Comment (segiddins) [inline bundler/lib/bundler/source/rubygems/remote.rb:19]:
```suggestion
        MAX_CACHE_SLUG_SIZE = 255
        private_constant :MAX_CACHE_SLUG_SIZE
```

**Review by segiddins — APPROVED** [review]

**Comment by jcogilvie** [comment]
I am running into the `ENAMETOOLONG` issue as well and would greatly appreciate any effort to get it merged.

**Comment by martinemde** [comment]
@jcogilvie Thanks for letting us know this is affecting you. I'm working on a test fix now.

**Comment by joshbranham** [comment]
We are also hitting this when using Artifactory Access Tokens to authenticate to our gems repo.

**Comment by jcogilvie** [comment]
@martinemde any movement here?  Looks like the windows tests are still upset.

**Comment by martinemde** [comment]
I got a windows pc (almost entirely) to be able to diagnose these broken tests. Once I have it up and running I will update.

(The windows tests are often more flaky so the PC will come in handy elsewhere)

**Comment by jcogilvie** [comment]
@martinemde any luck with the new machine?

**Comment by simi** [comment]
@jcogilvie I have Windows machine around, let me check if I can reproduce failures locally and fix.

**Comment by jcogilvie** [comment]
At the risk of adding another non-productive comment, is anyone still looking at this?

**Comment by martinemde** [comment]
@jcogilvie I appreciate you keeping this alive.

It seems like you're running into this often enough for it to be annoying. Do you think you could help me reproduce it?

What is your Ruby setup? There's so many ways to install Ruby on windows that I've had trouble figuring out a way that will trigger it. Is there a certain gem and server combo that triggers this?

Anything you can do that helps reproduce would help us make progress. Thank you 🙏

**Comment by jcogilvie** [comment]
I'm going to tag in @nrowegt to give you as specific a case as he can to exercise this (though I think the issue he filed, #5505, may be as comprehensive as we can get), but in broad strokes it's triggered by the exaggeratedly long path names generated in github actions.  We're specifically trying to use a connection to artifactory from GHA.

**Comment by deivid-rodriguez** [comment]
My recollection here is that the problem was that Windows not only had a "path component" length limitation, but also a "full path" length limitation and it's the second limitation that the test was running into.

That's an existing issue that this PR can't possibly worsen, so I'd say we could skip the test on Windows and move on.

If that seems like a good approach, I'm happy to finish up this PR.

**Comment by jcogilvie** [comment]
From a user perspective that sounds fine to me.

**Comment by jcogilvie** [comment]
Looks like still a few test failures here.  Is this moving forward ignoring them, or do they need to be skipped somehow?

**Comment by deivid-rodriguez** [comment]
They need to be fixed, not skipped. I tend to recall (but I'm no longer sure anymore) that originally the PR was failing the _new test_ only on Windows. I think that would be fine to skip. But in the current state, some specs seem to be failing on Windows that were not failing before. That would be a regression so we should eventually look into that.

**Comment by a1flecke** [comment]
@deivid-rodriguez we are hitting this issue on an ubuntu system pulling rubygems from a private SaaS artifactory instance.  The URI of the source.  

```
There was an error accessing
`/home/ubuntu/.bundle/cache/compact_index/abcdefghijklmno.jfrog.io.**redacted**.443.50f7ee1e8fb0b89cc10bd667ecbc0840/info`.
The underlying system error is Errno::ENAMETOOLONG: File name too long @
dir_s_mkdir -
/home/ubuntu/.bundle/cache/compact_index/abcdefghijklmno.jfrog.io.**redacted**.443.50f7ee1e8fb0b89cc10bd667ecbc0840
````

How can we get this over the line?  I understand there might be a regression on Windows.  I cannot see the log files to see what is going on.

**Comment by deivid-rodriguez** [comment]
First thing would be to rebase this PR and retrigger CI, to check the current state. Let me do that.

**Comment by mbclu** [comment]
@deivid-rodriguez I pulled this branch down and looked at it. After getting the repo setup and reproducing the failing test locally; I noticed that all the other specs in `global_cache_spec.rb` use "myrack".

Updating the gem and expectations to use "myrack" got the tests to pass again locally.

**Comment by a1flecke** [comment]
@deivid-rodriguez : I have not had the time to investigate the failed jobs.  It looks like @mbclu has done a great job digging into it.  I was able to confirm that the fix in this MR fixed the issue that my team was running into.  

Our scenario: We are running [Renovate](https://github.com/renovatebot/renovate/) across 1000s of repositories to keep them updated.  We noticed that some of our Ruby repositories were not getting correctly updated. The logs had this error message in them.

When I applied the code change to Remote::cache_slug (first by hand by editing the installed Bundler code and then by "monkey patching" causing Ruby to load a patch when it started) the errors went away.  It would be great if this fix could go out.  Until then we will continue to "monkey patch" the Ruby that Renovate is using.

Thank you for your hard work on this project.

**Comment by deivid-rodriguez** [comment]
Ok, for starters let me apply @mbclu's fix to this PR to see what the state is after that.

**Comment by deivid-rodriguez** [comment]
It seems we're no back to the previous situation: everything green, except for Windows, where this seems to create obvious regressions.

**Comment by mbclu** [comment]
My Team has the same issue as @a1flecke where Renovate is unable to update a Gemfile.lock because of this error. If this issue is not a high priority, is it possible to modify this the implementation to platform dependent and skip Windows (for now anyway)?

**Comment by deivid-rodriguez** [comment]
As long as this does not create any regression, I'm happy to introduce this fix only for non Windows environments. But someone needs to do the work, please feel free to tackle it!

**Comment by martinemde** [comment]
I pushed a raise in the place where the code is failing on windows to try to nail this down. There should be no reason why we're hitting this limit in our tests, so something is weird. Windows seems to support up to 260 characters in a path, so I'm trying to solve for why this is not just failing in the test that tries to make a long path, but instead in tests that seem to work without our attempting to limit path size.

**Comment by martinemde** [comment]
I have decided this bug in windows is very strange.

The actual error is caused by shoveling `<< nil` into Digest::MD5. The nil comes from a blank compact index response  that causes `response.body.byteslice(1..-1)` to return nil. Here is [an example failing test line where it fails during `bundle install`](https://github.com/rubygems/rubygems/blob/515450691239ffc7184bccd8dc7bf0354c731196/bundler/spec/commands/update_spec.rb#L707)

So... I can't explain why this is working on all the other implementations and not windows. Locally, on Mac, I'm not allowed to shovel nil into md5 without the same error, so this is a difference in the compact index response between windows and mac in the windows tests? Maybe the file length of the cache is failing earlier on windows and that causes a fallback to full index, but we fixed it, so now some of them are exposing this new bug on windows.

**Comment by martinemde** [comment]
Rather than commit the fix as part of this PR, I opened #8524 with the fix. This fix should be merged regardless of our solution here to make the compact index more resilient.

**Comment by martinemde** [comment]
Unfortunately they're still failing, but the failures now are not masked by the bad response from compact index. The tests are now failing for seemingly real(?) reasons, albeit ones that make no sense since they work on all the other platforms.

Did we "fix" windows cache file paths so that they now expose some other problem that was being skipped by compact index fallback? The fact of Ruby 3.4 only failing 1 test compared to many failures on the other rubies makes me suspicious that it's a windows Ruby bug.

I'm not even sure how to skip this feature for windows. The tests aren't failing because of cache filename changes as far as I can tell.

**Comment by deivid-rodriguez** [comment]
After #8551, the errors are more clear. Our global `after` hook is failing to delete the compact index files created by the new spec on Windows. Before, this was not an error but the presence of those files in subsequent specs was randomly creating failures in random places.

This indeed seems like a Ruby on Windows bug, since it's succeeding creating files with this length, but then failing to remove them, which seems odd. I will create a workaround today.

**Review by martinemde — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
I pushed a small modification to reference the [ruby-core ticket](https://bugs.ruby-lang.org/issues/21177) I just opened. Merging now!
