### PR TITLE
Raise Gem::Package::FormatError when gem encounters corrupt EOF

### LINKED ISSUE #5981: NoMethodError: undefined method `size' for nil:NilClass
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using minitest 5.16.3
Using zeitwerk 2.6.1
Using thread_safe 0.3.6
Using builder 3.2.4
Using racc 1.6.0
Using erubi 1.11.0
Using crass 1.0.6
Using rack 2.2.4
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using mini_mime 1.1.2
Using public_suffix 5.0.0
Using ansi 1.5.0
Using ast 2.4.2
Using bindex 0.8.1
Using msgpack 1.6.0
Using bundler 2.3.23
Using byebug 11.1.3
Using matrix 0.4.2
Using regexp_parser 2.6.0
Using childprocess 4.1.0
Using marcel 1.0.2
Using ruby-rc4 0.1.5
Using ffi 1.15.5
Using rb-fsevent 0.11.2
Using mysql2 0.4.10
Using method_source 1.0.0
Using pdfkit 0.8.7
Using ttfunk 1.7.0
Using thor 1.2.1
Using rexml 3.2.5
Using rubyzip 2.3.2
Using pdf-core 0.9.0
Using tilt 2.0.11
Using websocket 1.2.9
Using spring 2.1.1
Using turbolinks-source 5.2.0
Using i18n 1.12.0
Using tzinfo 1.2.10
Using nokogiri 1.13.8 (x86_64-linux)
Using rack-test 2.0.2
Using rack-proxy 0.7.4
Using sprockets 4.1.1
Using websocket-driver 0.7.5
Using mail 2.7.1
Using addressable 2.8.1
Using bootsnap 1.13.0
Using ruby-ll 2.1.2
Using puma 4.3.12
Using combine_pdf 1.0.22
Using rb-inotify 0.10.1
Using sassc 2.4.0
Using prawn 2.4.0
Using selenium-webdriver 4.5.0
Using turbolinks 5.2.1
Using activesupport 6.0.6
Using loofah 2.19.0
Using xpath 3.2.0
Using oga 3.4
Using grover 1.1.2
Using listen 3.7.1
Using prawn-table 0.2.2
Using rails-dom-testing 2.0.3
Using rails-html-sanitizer 1.4.3
Using globalid 1.0.0
Using activemodel 6.0.6
Using webdrivers 5.2.0
Using wicked_pdf 2.6.3
Using capybara 3.37.1
Using prawn-html 0.7.1
Using spring-watcher-listen 2.0.1
Using actionview 6.0.6
Using activejob 6.0.6
Using activerecord 6.0.6
Using actionpack 6.0.6
Using jbuilder 2.11.5
Using actioncable 6.0.6
Using activestorage 6.0.6
Using actionmailer 6.0.6
Using railties 6.0.6
Using sprockets-rails 3.4.2
Using actionmailbox 6.0.6
Using actiontext 6.0.6
Using sassc-rails 2.1.2
Using web-console 4.2.0
Using webpacker 4.3.0
Using rails 6.0.6
Using sass-rails 6.0.0
Exception while verifying /usr/local/lib/ruby/gems/2.7.0/cache/wkhtmltopdf-binary-0.12.6.5.gem
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `size' for nil:NilClass
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package/tar_reader/entry.rb:139:in `read'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:365:in `block in digest'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:362:in `each'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:362:in `digest'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:664:in `verify_entry'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:683:in `block in verify_files'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package/tar_reader.rb:65:in `each'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:682:in `verify_files'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:613:in `block (2 levels) in verify'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package/tar_reader.rb:27:in `new'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:610:in `block in verify'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package/file_source.rb:29:in `open'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package/file_source.rb:29:in `with_read_io'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:609:in `verify'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:590:in `spec'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/installer.rb:287:in `spec'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/rubygems_gem_installer.rb:97:in `spec'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/source/rubygems.rb:190:in `install'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/worker.rb:54:in `loop'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.3.23
  Platforms   ruby, x86_64-linux
Ruby          2.7.6p219 (2022-04-12 revision c9c2245c0a25176072e02db9254f0e0c84c805cd) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.23
  Gem Home    /usr/local/lib/ruby/gems/2.7.0
  Gem Path    /root/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0
  User Home   /root
  User Path   /root/.gem/ruby/2.7.0
  Bin Dir     /usr/local/bin
OpenSSL       
  Compiled    OpenSSL 1.0.1f 6 Jan 2014
  Loaded      OpenSSL 1.0.1f 6 Jan 2014
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-10-05
Git SHA           250d9d485d
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.6'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.0.4', '>= 6.0.4.7'
# Use sqlite3 as the database for Active Record
# gem 'sqlite3', '~> 1.4'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'grover'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem "wicked_pdf"
gem "wkhtmltopdf-binary"
gem "pdfkit"
gem "prawn"
gem "prawn-table"
gem "prawn-html"


# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.0.6)
      actionpack (= 6.0.6)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.0.6)
      actionpack (= 6.0.6)
      activejob (= 6.0.6)
      activerecord (= 6.0.6)
      activestorage (= 6.0.6)
      activesupport (= 6.0.6)
      mail (>= 2.7.1)
    actionmailer (6.0.6)
      actionpack (= 6.0.6)
      actionview (= 6.0.6)
      activejob (= 6.0.6)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.0.6)
      actionview (= 6.0.6)
      activesupport (= 6.0.6)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.0.6)
      actionpack (= 6.0.6)
      activerecord (= 6.0.6)
      activestorage (= 6.0.6)
      activesupport (= 6.0.6)
      nokogiri (>= 1.8.5)
    actionview (6.0.6)
      activesupport (= 6.0.6)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.0.6)
      activesupport (= 6.0.6)
      globalid (>= 0.3.6)
    activemodel (6.0.6)
      activesupport (= 6.0.6)
    activerecord (6.0.6)
      activemodel (= 6.0.6)
      activesupport (= 6.0.6)
    activestorage (6.0.6)
      actionpack (= 6.0.6)
      activejob (= 6.0.6)
      activerecord (= 6.0.6)
      marcel (~> 1.0)
    activesupport (6.0.6)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2, >= 2.2.2)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    ansi (1.5.0)
    ast (2.4.2)
    bindex (0.8.1)
    bootsnap (1.13.0)
      msgpack (~> 1.2)
    builder (3.2.4)
    byebug (11.1.3)
    capybara (3.37.1)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    combine_pdf (1.0.22)
      matrix
      ruby-rc4 (>= 0.1.5)
    concurrent-ruby (1.1.10)
    crass (1.0.6)
    erubi (1.11.0)
    ffi (1.15.5)
    globalid (1.0.0)
      activesupport (>= 5.0)
    grover (1.1.2)
      combine_pdf (~> 1.0)
      nokogiri (~> 1.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    listen (3.7.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.19.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    minitest (5.16.3)
    msgpack (1.6.0)
    mysql2 (0.4.10)
    nio4r (2.5.8)
    nokogiri (1.13.8-x86_64-linux)
      racc (~> 1.4)
    oga (3.4)
      ast
      ruby-ll (~> 2.1)
    pdf-core (0.9.0)
    pdfkit (0.8.7)
    prawn (2.4.0)
      pdf-core (~> 0.9.0)
      ttfunk (~> 1.7)
    prawn-html (0.7.1)
      oga (~> 3.3)
      prawn (~> 2.4)
    prawn-table (0.2.2)
      prawn (>= 1.3.0, < 3.0.0)
    public_suffix (5.0.0)
    puma (4.3.12)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.4)
    rack-proxy (0.7.4)
      rack
    rack-test (2.0.2)
      rack (>= 1.3)
    rails (6.0.6)
      actioncable (= 6.0.6)
      actionmailbox (= 6.0.6)
      actionmailer (= 6.0.6)
      actionpack (= 6.0.6)
      actiontext (= 6.0.6)
      actionview (= 6.0.6)
      activejob (= 6.0.6)
      activemodel (= 6.0.6)
      activerecord (= 6.0.6)
      activestorage (= 6.0.6)
      activesupport (= 6.0.6)
      bundler (>= 1.3.0)
      railties (= 6.0.6)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.3)
      loofah (~> 2.3)
    railties (6.0.6)
      actionpack (= 6.0.6)
      activesupport (= 6.0.6)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.20.3, < 2.0)
    rake (13.0.6)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    regexp_parser (2.6.0)
    rexml (3.2.5)
    ruby-ll (2.1.2)
      ansi
      ast
    ruby-rc4 (0.1.5)
    rubyzip (2.3.2)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    selenium-webdriver (4.5.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    spring (2.1.1)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (4.1.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    thor (1.2.1)
    thread_safe (0.3.6)
    tilt (2.0.11)
    ttfunk (1.7.0)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.10)
      thread_safe (~> 0.1)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.2.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    webpacker (4.3.0)
      activesupport (>= 4.2)
      rack-proxy (>= 0.6.1)
      railties (>= 4.2)
    websocket (1.2.9)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    wicked_pdf (2.6.3)
      activesupport
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.1)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  bootsnap (>= 1.4.2)
  byebug
  capybara (>= 2.15)
  grover
  jbuilder (~> 2.7)
  listen (~> 3.2)
  mysql2 (>= 0.3.18, < 0.5)
  pdfkit
  prawn
  prawn-html
  prawn-table
  puma (~> 4.1)
  rails (~> 6.0.4, >= 6.0.4.7)
  sass-rails (>= 6)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  turbolinks (~> 5)
  tzinfo-data
  web-console (>= 3.3.0)
  webdrivers
  webpacker (~> 4.0)
  wicked_pdf

RUBY VERSION
   ruby 2.7.6p219

BUNDLED WITH
   2.3.23
```

--- TEMPLATE END ----------------------------------------------------------------

### PR DESCRIPTION
**Pull request by martinemde**
## What was the end-user or developer problem that led to this PR?

Fixes #5981 which raised a `NoMethodError` when the real problem was attempting to read a corrupted gem file.

## What is your fix for the problem, implemented in this PR?

`Gem::Package::TarReader::Entry` raises `EOFError` or returns `nil` appropriately based on Ruby core `IO.read` and `IO.readpartial` behavior.

Zlib handles `EOFError` and `nil` reads by raising `Zlib::GzipFile::Error`.

When verifying a gem or extracting contents, rescue these expected `EOFError`s and Zlib errors to return appropriate FormatError for a corrupt gem.

Started as a fix for a bug where `size` was called on `nil` because `TarReader` didn't handle unexpected `nil` returned from `IO.read`.

## Make sure the following tasks are checked

- [X] Describe the problem / feature
- [X] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [X] Write code to solve the problem
- [X] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: lib/rubygems/package/tar_reader/entry.rb [hunk 1]
```diff
@@ -230,8 +226,8 @@ def seek(offset, whence = IO::SEEK_SET)
     end
 
     while pending > 0 do
-      size_read = @io.read([pending, 4096].min).size
-      raise UnexpectedEOF if @io.eof?
+      ret = @io.readpartial([pending, 4096].min)
+      size_read = ret.size
```
Comment (martinemde) [inline lib/rubygems/package/tar_reader/entry.rb:230]: Same problem here where we ignored the possible `nil` return from read.

I also removed UnexpectedEOF here. I think there's two problems: If the read above hit an EOF without reading any bytes, then `.size` would raise. If it _properly_ read to right up to the EOF, like if this was the last file in the archive, then this would raise when it should not. The only reason to raise here is if we hit a normal EOFError due to readpartial, so I just let readpartial handle raising.

We could remove the UnexpectedEOF constant also. It was only (never) used here, so I think it's safe to remove completely. Besides, all EOFErrors are unexpected. 🤷‍♂️

File: test/rubygems/test_gem_package.rb [hunk 2]
```diff
@@ -946,6 +946,87 @@ def test_verify_corrupt
     tf.close!
   end
 
+  def test_verify_corrupt_tar_metadata_entry
+    gem = tar_file_header("metadata.gz", "", 0, 999, Time.now)
```
Comment (martinemde) [inline test/rubygems/test_gem_package.rb:950]: `verify` handles metadata, checksums, and data.tar.gz slightly differently, raising different errors when each is corrupt. That's why there's so many new tests here for seemingly the same thing.

File: test/rubygems/test_gem_package.rb [hunk 3]
```diff
@@ -946,6 +946,87 @@ def test_verify_corrupt
...
+      package.contents
+    end
+
+    assert_equal "end of file reached in corrupt.gem", e.message
+
+    e = assert_raise Gem::Package::FormatError do
+      package.extract_files @destination
+    end
+
+    assert_equal "end of file reached in corrupt.gem", e.message
```
Comment (martinemde) [inline test/rubygems/test_gem_package.rb:1027]: Should I make the error better? Currently it's just a passthru error message for EOFError or Zlib's "not in gzip format" error. We could be more clear about it being "corrupt". Opinions?

**Comment by martinemde** [comment]
Looks like the errors are legitimate. I'll work on them today.

File: lib/rubygems/package.rb [hunk 4]
```diff
@@ -702,7 +706,7 @@ def verify_files(gem)
 
   def verify_gz(entry) # :nodoc:
     Zlib::GzipReader.wrap entry do |gzio|
-      gzio.read 16_384 until gzio.eof? # gzip checksum verification
+      gzio.readpartial 16_384 until gzio.eof? # gzip checksum verification
```
[the remark this answers is not in the document]
Comment (martinemde) [reply lib/rubygems/package.rb]: readpartial seems to cause an error in zlib that doesn't happen with `read`.

**Review by segiddins — APPROVED** [review]
