### PR TITLE
Fix `stub.activated?` sometimes returning false after activation under bundler

### LINKED ISSUE #8068: Under bundler, `Bundler::StubSpecification#activated?` returns false after activation
### Describe the problem as clearly as you can

Without bundler, I can do the following to understand if a gem is activated:

```rb
$ irb
irb(main):001> Gem::Specification.stubs.to_a.find { _1.name == "rainbow" }.activated?
=> nil
irb(main):002> gem "rainbow"
=> true
irb(main):003> Gem::Specification.stubs.to_a.find { _1.name == "rainbow" }.activated?
=> true
```

I would like to to the same with bundler, however I currently have to do a bit more to make that work.

### Did you try upgrading rubygems & bundler?

Yes, Bundler 2.5.20, Rubygems 3.5.20

### Post steps to reproduce the problem

* gem install rainbow
* Create a Gemfile with rainbow and lock
* Run the following in `irb`:
  ```rb
  gem "rainbow"
  Gem::Specification.stubs.to_a.find { _1.name == "rainbow" }.activated?
  # => true
  ```
* Run the following in `bundle exec irb`
  ```rb
  gem "rainbow"
  Gem::Specification.stubs.to_a.find { _1.name == "rainbow" }.activated?
  # => false
  ```
* However:
  ```rb
  gem "rainbow"
  Gem::Specification.stubs.to_a.find { _1.name == "rainbow" }.stub.activated?
  # => true
  ```

### Possible solution

I think there is a type in the code here: https://github.com/rubygems/rubygems/blob/c63c4b0305de7a5712436d37decca648b14b0091/bundler/lib/bundler/stub_specification.rb#L48-L50

I'm somewhat confident that should be `activated?` instead, since calling `activated` raises `NoMethodError` and `activated?`  now just delegates to the `RemoteSpecification`:
https://github.com/rubygems/rubygems/blob/c63c4b0305de7a5712436d37decca648b14b0091/bundler/lib/bundler/remote_specification.rb#L112-L114

However, it could also just be that checking in the stub is expected. I'm not sure on the relation of all these classes and what they really mean.

### PR DESCRIPTION
**Pull request by Earlopain**
## What was the end-user or developer problem that led to this PR?

Closes #8068

## What is your fix for the problem, implemented in this PR?

Correct the typo.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/spec/bundler/stub_specification_spec.rb [hunk 1]
```diff
@@ -55,4 +55,24 @@
...
+      stub.activated = true
+      expect(stub.activated?).to be true
+    end
+
+    it "returns true after activation if the underlying stub is a `Gem::StubSpecification`" do
+      spec_path = File.join(File.dirname(__FILE__), "specifications", "foo.gemspec")
+      gem_stub = Gem::StubSpecification.new(spec_path, File.dirname(__FILE__),"","")
+      stub = described_class.from_stub(gem_stub)
+
+      expect(stub.activated?).to be nil
```
Comment (Earlopain) [inline bundler/spec/bundler/stub_specification_spec.rb:73]: While the other test returns `false` here, `nil` is falsy and I think that's fine.

File: bundler/spec/bundler/stub_specification_spec.rb [hunk 2]
```diff
@@ -55,4 +55,24 @@
...
+      stub = described_class.from_stub(with_bundler_stub_spec)
+
+      expect(stub.activated?).to be false
+      stub.activated = true
+      expect(stub.activated?).to be true
+    end
+
+    it "returns true after activation if the underlying stub is a `Gem::StubSpecification`" do
+      spec_path = File.join(File.dirname(__FILE__), "specifications", "foo.gemspec")
+      gem_stub = Gem::StubSpecification.new(spec_path, File.dirname(__FILE__),"","")
```
Comment (Earlopain) [inline bundler/spec/bundler/stub_specification_spec.rb:70]: I'm not quite sure which codepath this ends up exercising but in the end the test would fail with this.

**Review by Earlopain — COMMENTED** [review]
I tried manually verifying with `ruby bundler/spec/support/bundle.rb exec irb` and running things there but it just returns the correct thing already :shrug:. At least I managed to write a proper test.

**Comment by deivid-rodriguez** [comment]
> I tried manually verifying with ruby bundler/spec/support/bundle.rb exec irb and running things there but it just returns the correct thing already 🤷. At least I managed to write a proper test.

Interesting! I'm able to reproduce the error with that command and validate that the fix works.

File: bundler/spec/bundler/stub_specification_spec.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply bundler/spec/bundler/stub_specification_spec.rb:73]: Yeah, I get we could make it consistent by making sure `Gem::StubSpecification#activated?` returns only true/false, but I honestly think it's fine as is. We could use `be_falsey` though to make these two tests consistent.

File: bundler/spec/bundler/stub_specification_spec.rb (hunk 2 above)
Comment (deivid-rodriguez) [reply bundler/spec/bundler/stub_specification_spec.rb:70]: Yeah, this seems ok to me. The reason the other test works already is because `Gem::Specification` aliases `#activated?` to `#activated`, but `Gem::StubSpecification` does not do that.

**Review by deivid-rodriguez — COMMENTED** [review]
I'd use `be_falsey` in both specs to make them consistent but other than that looks good!

File: bundler/spec/bundler/stub_specification_spec.rb (hunk 1 above)
Comment (Earlopain) [reply bundler/spec/bundler/stub_specification_spec.rb]: Nice suggestion, I changed it to `be_falsy`.

**Review by deivid-rodriguez — APPROVED** [review]
