### PR TITLE
Indicate a gem which has been deleted on `bundle info`

### LINKED ISSUE #3493: `bundle info` does not indicate a gem which has been deleted, unlike `bundle show`
(Sorry, I didn't follow the template because this is pretty straightforward...)

## To reproduce:
1. Install a gem by adding it to your Gemfile/gemspec and running `bundle install` (I installed the `logstash-core-plugin-api` gem)
2. Locate the gems installation path (on my machine it is `C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/`) and delete the folder containing the installed gem (on mine, it is `logstash-core-plugin-api-2.1.28-java`)
3. Run `bundle info <gem>`

## Actual output:

```bash
> bundle info logstash-core-plugin-api
  * logstash-core-plugin-api (2.1.28)
        Summary: Define the plugin API that the plugin need to follow.
        Homepage: http://www.elastic.co/guide/en/logstash/current/index.html
        Path: C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/logstash-core-plugin-api-2.1.28-java
```

## What's wrong:
The output does not indicate that the folder has been removed. Compare this to the output of `bundle show`, which is now deprecated:

```bash
> bundle show logstash-core-plugin-api
[DEPRECATED] use `bundle info logstash-core-plugin-api` instead of `bundle show logstash-core-plugin-api`
The gem logstash-core-plugin-api has been deleted. It was installed at: C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/logstash-core-plugin-api-2.1.28-java
```

### PR DESCRIPTION
**Pull request by devraj-kumar**
# Description:

`bundle info` does not indicate a gem which has been deleted, unlike `bundle show`

Fixes #3493.

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by devraj-kumar** [comment]
@deivid-rodriguez, hey I just tried to solve one of issue, but I think due to less familiarity with code I am unable to understand why specs are failing, can you help me with little bit hint/guidance! Thankyou

File: bundler/lib/bundler/cli/info.rb [hunk 1]
```diff
@@ -14,6 +14,20 @@ def run
...
+          path = File.expand_path("../../../..", __FILE__)
+        else
+          spec = Bundler::CLI::Common.select_spec(gem_name, :regex_match)
+          return unless spec
+          path = spec.full_gem_path
+          unless File.directory?(path)
+            return Bundler.ui.warn "The gem #{gem_name} has been deleted. It was installed at: #{path}"
+          end
+        end
+        return Bundler.ui.info(path)
```
Comment (deivid-rodriguez) [inline bundler/lib/bundler/cli/info.rb:28]: Hi @devraj-kumar! Thanks for keeping on helping us! :heart:

I see that the CI is complaining because our specs expect a bunch of output to be printed by `bundle info`, but now only the path is being printed. That suggests that you at least need to remove this early `return`, and simply print the information and go on. Something like:

```suggestion
        Bundler.ui.info(path)
```

However, though, it seems that that "path information" is being printed at the `print_gem_path` method further down. So I believe the check about directory existence should be moved to there.

Let me know if this information allows you to move on or if you need further help.

**Comment by devraj-kumar** [comment]
@deivid-rodriguez, thank you for your guidance, I gave some time understanding code and specs and refactor it now, can you review this one?

**Comment by deivid-rodriguez** [comment]
Could you also copy the `bundle show` spec that was covering this feature into `bundle info` specs?

**Comment by devraj-kumar** [comment]
ROGER!, Ohkk I will do as you directed, and with an aim of finishing this today anyhow!

**Comment by deivid-rodriguez** [comment]
PR rebased and CI fixed! Thanks @devraj-kumar!
