### PR TITLE
Make `--enable-load-relative` binstubs prolog work when Ruby is not installed in the same directory as the binstub

### LINKED ISSUE #7856: Windows + Git Bash = Cannot call gem executable directly (No such file or directory)
### Describe the problem as clearly as you can

After updating one of our instances from Ruby 2.7.7 to Ruby 3.3.4 I noticed that simple things, like running `bundler check` started to fail. I wasn't expecting this. Here is the description of the issue:

When trying to run a gem executable from Git Bash in Windows i"m getting a `No such file or directory` error.  At first I thought this was related to the fact that I was using [Scoop](https://scoop.sh/) to install ruby so I switched to the [Ruby Installer](https://rubyinstaller.org/) but there I got the same behaviour so it seems that Scoop wasn't involved there.

To reproduce the issue you can do the following:

(Under Windows)

1. Install a gem that includes an executable, for example `pry` (It doesn't matter if you install it from the Windows CLI or Git Bash, the result is the same)
2. Under Windows Command Line or Power Shell running the gem executable: `pry` works.
3. From git-bash I'm getting the following error:

```
Sergio Bobillier@DESKTOP-42FVDCQ MINGW64 ~
$ pry
/c/Users/sergio/AppData/Local/Microsoft/WindowsApps/pry: line 6: /c/Users/sergio/AppData/Local/Microsoft/WindowsApps/ruby: No such file or directory
```

👉 One important detail here is that it is trying to search for `ruby` in the path where the gem executables are located and not in the path where the Ruby interpreter is actually installed, which is `C:\Ruby33-x64\bin\ruby.exe`

I can work around this by calling `pry.bat`, then it works (although it raises different error related to IO, unrelated to this issue). But for example, it can print its version:

```
Sergio Bobillier@DESKTOP-42FVDCQ MINGW64 ~
$ pry.bat --version
Pry version 0.14.2 on Ruby 3.3.4
```

The issue seems to be related to the Bash Prolog Script, which I tracked down to here: https://github.com/rubygems/rubygems/blob/e71bef01f2f57055176c625e6f5eb468bd1f6c9a/lib/rubygems/installer.rb#L1008

I managed to make this work by editing the executable file like this:

```diff
 =begin
 bindir="${0%/*}"
-exec "$bindir/ruby" "-x" "$0" "$@"
+exec "ruby" "-x" "$0" "$@"
 =end
```

So, basically running just `ruby` instead of using the full path. That also works. But of course changing the executables does not seem to be a good idea. Plus it would be maintenance hell, but it does work:

```
Sergio Bobillier@DESKTOP-42FVDCQ MINGW64 ~
$ pry --version
Pry version 0.14.2 on Ruby 3.3.4
```

### Did you try upgrading RubyGems?

Yes, I tried to update Rubygems, but the behaviour is the same:

```
PS C:\Users\sergio> gem --version
3.5.15
```

### Post steps to reproduce the problem

Steps to reproduce the issue are provided as part of the issue description.

### Which command did you run?

Trying to run any gem executable with git-bash causes the issue.

### What were you expecting to happen?

I would expect them to run without any issue, just like they were doing in Ruby 2.7.7 (rubygems 3.1.6)

### What actually happened?

Exactly what I described, the "No such file or directory" error.

### Run `gem env` and paste the output below

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.15
  - RUBY VERSION: 3.3.4 (2024-07-09 patchlevel 94) [x64-mingw-ucrt]
  - INSTALLATION DIRECTORY: C:/Users/sergio/.gem/ruby/3.3.0
  - USER INSTALLATION DIRECTORY: C:/Users/sergio/.gem/ruby/3.3.0
  - RUBY EXECUTABLE: C:/Ruby33-x64/bin/ruby.exe
  - GIT EXECUTABLE: C:\Program Files\Git\cmd/git.EXE
  - EXECUTABLE DIRECTORY: C:/Users/sergio/.gem/ruby/3.3.0/bin
  - SPEC CACHE DIRECTORY: C:/Users/sergio/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
     - ruby
     - x64-mingw-ucrt
  - GEM PATHS:
     - C:/Users/sergio/.gem/ruby/3.3.0
     - C:/Ruby33-x64/lib/ruby/gems/3.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - "gem" => ["--install-dir", "C:/Users/sergio/.gem/ruby/3.3.0", "--bindir", "C:/Users/sergio/AppData/Local/Microsoft/WindowsApps"]
     - "# Feel free to add any rubygems config options as described on" => nil
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Ruby33-x64\bin
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\WINDOWS\System32\OpenSSH\
     - C:\Program Files\Git\cmd
     - C:\Program Files\PowerShell\7\
     - C:\Program Files\Git\bin
     - C:\Program Files\Git\usr\bin
     - C:\Users\sergio\scoop\shims
     - C:\Users\sergio\AppData\Local\Microsoft\WindowsApps
     - C:\Users\sergio\AppData\Local\Programs\Microsoft VS Code\bin
```

### LINKED ISSUE #8135: shebang problem when installing gem executable into non-standard location with --install-dir on an --enable-load-relative ruby
I ran into the following problem which I thought was a variation of #2929, however I was informed that that issue had been fixed long ago.

# Steps to reproduce

### First build an --enable-load-relative ruby and use it to install a gem (in this case fpm) to a non-standard location with --install-dir
```
$ mkdir -p tmp/share
$ cd tmp
$ wget https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.5.tar.gz
$ tar -xf ruby-3.3.5.tar.gz
$ cd ruby-3.3.5
$ ./autogen.sh
$ ./configure --enable-load-relative --prefix $(realpath ../share)
$ make
$ make install
$ cd ..
$ mkdir gems
$ share/bin/gem install --install-dir gems fpm
```
### When I try to use the gem though I get the following error
```
$ gems/bin/fpm --version
gems/bin/fpm: 6: exec: gems/bin/ruby: not found
```
### The problem can be seen by inspecting the top of the `gems/bin/fpm` executable
```
$ head -n 16 gems/bin/fpm 
#!/bin/sh
# -*- ruby -*-
_=_\
=begin
bindir="${0%/*}"
exec "$bindir/ruby" "-x" "$0" "$@"
=end
#!/tmp/share/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'fpm' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'
```

This shows that this executable expects ruby to be in the same directory as itself.

### Workaround

During gem installation if I use the gem configuration file option `custom_shebang: $ruby`, then it just puts the path to the executing ruby interpreter as the shebang on the installed gem executable, and all is well (assuming GEM_PATH points at the custom gem dir).

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

If Ruby was configured with the `--enable-load-relative` option, and RubyGems is configured to not install gems to the default bindir, then RubyGems generated binstubs don't work because the `--enable-load-relative` prolog assumes this can't happen.

## What is your fix for the problem, implemented in this PR?

I figured we could fallback to relying on PATH if Ruby is not installed in the same directory as the binstub.

Fixes #7856.
Fixes #8135.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: lib/rubygems/installer.rb [hunk 1]
```diff
@@ -998,18 +998,17 @@ def load_relative_enabled?
...
-
       <<~EOS
         #!/bin/sh
         # -*- ruby -*-
         _=_\\
         =begin
-        #{script.chomp}
+        bindir="${0%/*}"
+        ruby="$bindir/#{ruby_install_name}"
+        if [ ! -f $ruby ]; then
```
Comment (nobu) [inline lib/rubygems/installer.rb:1008]:
```suggestion
        if [ ! -f "$ruby" ]; then
```
