### PR TITLE
Workaround JRuby + Windows issue with net-http-persistent vendored code

### LINKED ISSUE #4129: Bundler 2.2.0 fails on JRuby 9.2 on Windows
See https://github.com/ruby/setup-ruby/runs/1542347124
Happens with both JRuby 9.2.14.0 and 9.2.13.0 on both windows-2016/2019 in GitHub Actions.

I'm not sure if it's an issue of JRuby or Bundler (or both), but AFAIK it did not happen with Bundler 2.1.4, so I guessed it's a Bundler issue.
cc @headius 

```
  C:\windows\system32\cmd.exe /D /S /C "D:\jruby-9.2.14.0\bin\gem.bat install bundler -v "~> 2" --no-document"
  Successfully installed bundler-2.2.0
  1 gem installed
  Took  21.69 seconds
```
```
 C:\windows\system32\cmd.exe /D /S /C "D:\jruby-9.2.14.0\bin\bundle.bat config --local path vendor/bundle"
  C:\windows\system32\cmd.exe /D /S /C "D:\jruby-9.2.14.0\bin\bundle.bat lock"
  D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:162: warning: Process#getrlimit not supported on this platform
```

  # Error Report
  
  ## Questions
  
  - **What did you do?**
  
    I ran the command `D:\jruby-9.2.14.0\bin\bundle lock`

  ## Backtrace
  
  ```
  NoMethodError: undefined method `first' for 9223372036854775807:Integer
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:162:in `<class:Persistent>'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:144:in `<main>'
    org/jruby/RubyKernel.java:974:in `require'
    org/jruby/RubyKernel.java:1002:in `require_relative'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendored_persistent.rb:11:in `<main>'
    org/jruby/RubyKernel.java:974:in `require'
    org/jruby/RubyKernel.java:1002:in `require_relative'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/fetcher.rb:3:in `<main>'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/cli/lock.rb:21:in `run'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/cli.rb:684:in `lock'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/cli.rb:30:in `dispatch'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/cli.rb:24:in `start'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/exe/bundle:49:in `block in <main>'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/exe/bundle:37:in `<main>'
    org/jruby/RubyKernel.java:1009:in `load'
    D:\jruby-9.2.14.0\bin\bundle:23:in `<main>'
  ```
  
  ## Environment
  
  ```
  Bundler       2.2.0
    Platforms   ruby, universal-java-1.8
  Ruby          2.5.7p0 (2020-12-08 revision 67816) [java]
    Full Path   D:/jruby-9.2.14.0/bin/jruby.exe
    Config Dir  D:/jruby-9.2.14.0/etc
  RubyGems      3.0.6
    Gem Home    D:/jruby-9.2.14.0/lib/ruby/gems/shared
    Gem Path    C:\Users\runneradmin/.gem/jruby/2.5.0;D:/jruby-9.2.14.0/lib/ruby/gems/shared
    User Home   C:\Users\runneradmin
    User Path   C:\Users\runneradmin/.gem/jruby/2.5.0
    Bin Dir     D:/jruby-9.2.14.0/bin
  OpenSSL       
    Compiled    JRuby-OpenSSL 0.10.5
    Loaded      JRuby-OpenSSL 0.10.5
    Cert File   C:\Program Files\Java\jdk8u275-b01\jre/lib/security/cacerts
    Cert Dir    C:\Program Files\Java\jdk8u275-b01\jre/lib/security
  Tools         
    Git         2.29.2.windows.2
    RVM         not installed
    rbenv       not installed
    chruby      not installed
  ```
  
  ## Bundler Build Metadata
  
  ```
  Built At          2020-12-10
  Git SHA           d3628e5019
  Released Version  true
  ```
  
  ## Bundler settings
  
  ```
  path
    Set for your local app (D:/a/setup-ruby/setup-ruby/.bundle/config): "vendor/bundle"
  ```
  
  ## Gemfile
  
  ### Gemfile
  
  ```ruby
  # Used for testing
  source 'https://rubygems.org'
  
  gem "rake"
  gem "path"
  gem "json", "2.2.0"
  ```
  
  ### Gemfile.lock
  
  ```
  <No D:/a/setup-ruby/setup-ruby/Gemfile.lock found>
  ```

### PR DESCRIPTION
**Pull request by slonopotamus**
Closes #4129.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
The whole test suite is suuuupuuuuuuuer slow on jruby, not really acceptable for running on every PR, and also it doesn't fully pass. If you can take care of skipping everything that currently fails on jruby, and move it to a daily job, I think it could be acceptable. Alternatively I would write a single test that catches the issue we're facing now and run just that.

**Comment by deivid-rodriguez** [comment]
Actually it seems that merely installing dependencies fails due to this issue? In that case, I think we can just test that :)

**Comment by slonopotamus** [comment]
I actually was not sure where to add JRuby+Windows combo. You have `.github/workflows/jruby-bundler.yml` that tests JRuby only on Linux but also have `.github/workflows/windows-bundler.yml` that tests multiple Rubies on Windows.

**Comment by slonopotamus** [comment]
Okay, at least it actually reproduces exact issue that happened in #4129: https://github.com/rubygems/rubygems/runs/1545806033?check_suite_focus=true#step:4:12

**Comment by deivid-rodriguez** [comment]
Yep, that's what I was saying. Where you added jruby is the right place. What I'd do for now is to limit the jruby job to just run the `bin/rake spec:parallel_deps` task, since that itself reproduces the issue, and running the full test suite is not going to work. I'd add a `if: "!startsWith(matrix.ruby, 'jruby')"` to all steps except for the one installing dependencies and before.

File: bundler/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb [hunk 1]
```diff
@@ -159,7 +159,14 @@ class Bundler::Persistent::Net::HTTP::Persistent
   # limits (typically windows).
 
   if Process.const_defined? :RLIMIT_NOFILE
-    DEFAULT_POOL_SIZE = Process.getrlimit(Process::RLIMIT_NOFILE).first / 4
+    open_file_limits = Process.getrlimit(Process::RLIMIT_NOFILE)
+
+    # Under Jruby on Windows Process responds to `getrlimit` but returns something that does not match docs
```
Comment (headius) [inline bundler/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:164]: The fix here is fine, if a little embarrassing. 😊 The bonus of this fix is that it will also solve the issue on non-native JRuby environments, like some enterprise web containers.

An alternative would be to use multiple assignment to get the first value. When it is a single value instead of an array it will still work.

```ruby
DEFAULT_POOL_SIZE, * = Process.getrlimit(Process::RLIMIT_NOFILE)
```

Oh, and it is spelled "JRuby" please ❤️

Comment (headius) [reply bundler/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:164]: Though, we do return a rather odd value so your original fix may be cleaner:

```
$ rvm jruby-9.2.14.0 do jruby -Xnative.enabled=false -e 'p Process.getrlimit(Process::RLIMIT_NOFILE)'
-e:1: warning: Process#getrlimit not supported on this platform
9223372036854775807
```

**Comment by headius** [comment]
The fix as written is simple and will cover all known breaking cases.

I think we should also try to get this into net-http-persistent since that library is now also broken for JRuby 9.2.14.0 and earlier on Windows.

File: bundler/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply bundler/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:164]: Yeah, I had the same thought but I thought the value didn't make much sense as a resource limit so decided to disregard it.

> Oh, and it is spelled "JRuby" please heart

Sorry, I'll fix my typos in this regard :)

**Comment by deivid-rodriguez** [comment]
Yes, I'm planning to forward port the fix to net-http-persistent too :+1:.
