### PR TITLE
Fix `bundle fund` when the gemfile contains optional groups

### LINKED ISSUE #7757: `bundle fund` errors when gemfile contains optional group
## Testcase

```rb
  # bundler/spec/commands/fund_spec.rb
  it "prints fund information when the bundle contains optional groups" do
    install_gemfile <<-G
      source "#{file_uri_for(gem_repo2)}"
      group :whatever, optional: true do
        gem 'has_funding_and_other_metadata'
      end
      gem 'has_funding'
      gem 'rack-obama'
    G

    bundle "fund"

    expect(out).to include("* has_funding (1.2.3)\n  Funding: https://example.com/has_funding/funding")
    expect(out).to_not include("has_funding_and_other_metadata")
    expect(out).to_not include("rack-obama")
  end
```

The problem is that `Bundler.definition.specs` doesn't include optional groups. It utilizes `requested_groups` which excludes them: https://github.com/rubygems/rubygems/blob/4ce4e978eb5259a6887012240e76eafc540471fc/bundler/lib/bundler/definition.rb#L1004-L1008

There is then a mismatch between the dependencies and specs here:
https://github.com/rubygems/rubygems/blob/4ce4e978eb5259a6887012240e76eafc540471fc/bundler/lib/bundler/cli/fund.rb#L16-L27

`current_dependencies` returns all. I tried a few ways to fix this myself but I'm not familiar enough with all this so I only have the above testcase. I guess safe navigation would work? Can't say if that would be the correct fix.

<details><summary>Error</summary>
<p>

 ```
       NoMethodError: undefined method `metadata' for nil
         /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/cli/fund.rb:24:in `block in run'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/cli/fund.rb:22:in `each'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/cli/fund.rb:22:in `each_with_object'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/cli/fund.rb:22:in `run'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/cli.rb:396:in `fund'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/cli.rb:35:in `dispatch'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/cli.rb:29:in `start'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/exe/bundle:28:in `block in <top (required)>'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.6.0.dev/exe/bundle:20:in `<top (required)>'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/bin/bundle:25:in `load'
                 /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/bin/bundle:25:in `<main>'
     
       ```
     
       ## Environment
     
       ```
       Bundler       2.6.0.dev
         Platforms   ruby, x86_64-linux
       Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [x86_64-linux]
         Full Path   /home/earlopain/.rbenv/versions/3.3.1/bin/ruby
         Config Dir  /home/earlopain/.rbenv/versions/3.3.1/etc
       RubyGems      3.5.10
         Gem Home    /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system
         Gem Path    /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system
         User Home   /home/earlopain/Documents/rubygems/bundler/tmp/1/home
         User Path   /home/earlopain/Documents/rubygems/bundler/tmp/1/home/.local/share/gem/ruby/3.3.0
         Bin Dir     /home/earlopain/Documents/rubygems/bundler/tmp/1/gems/system/bin
       OpenSSL       
         Compiled    OpenSSL 3.2.1 30 Jan 2024
         Loaded      OpenSSL 3.3.1 4 Jun 2024
         Cert File   /etc/ssl/cert.pem
         Cert Dir    /etc/ssl/certs
       Tools         
         Git         2.45.2
         RVM         not installed
         rbenv       rbenv 1.2.0
         chruby      not installed
       ```
     
       ## Bundler Build Metadata
     
       ```
       Built At          2024-06-14
       Git SHA           8bb960a6d
       Released Version  true
       ```
     
       ## Gemfile
     
       ### Gemfile
     
       ```ruby
       source "file:///home/earlopain/Documents/rubygems/bundler/tmp/1/gems/remote2"
       group :whatever, optional: true do
         gem 'has_funding_and_other_metadata'
       end
       gem 'has_funding'
       gem 'rack-obama'
       ```
     
       ### Gemfile.lock
     
       ```
       GEM
         remote: file:///home/earlopain/Documents/rubygems/bundler/tmp/1/gems/remote2/
         specs:
           has_funding (1.2.3)
           has_funding_and_other_metadata (1.0)
           rack (1.0.0)
           rack-obama (1.0)
             rack
     
       PLATFORMS
         ruby
         x86_64-linux
     
       DEPENDENCIES
         has_funding
         has_funding_and_other_metadata
         rack-obama
     
       BUNDLED WITH
          2.6.0.dev
       ```

</p>
</details>

### PR DESCRIPTION
**Pull request by Earlopain**
Closes #7757

## What was the end-user or developer problem that led to this PR?

`bundle fund` errors when the gemfile contains optional groups

## What is your fix for the problem, implemented in this PR?

`current_dependencies` doesn't return gems in optional groups, while `specs` would. As suggested in https://github.com/rubygems/rubygems/issues/7757#issuecomment-2168340472, use `requested_dependencies` instead which does the right thing.

The error lies here: https://github.com/rubygems/rubygems/blob/4ce4e978eb5259a6887012240e76eafc540471fc/bundler/lib/bundler/cli/fund.rb#L16-L27

specs doesn't contain enough data, some dependencies are present which aren't in the spec resulting in `spec.metadata` blowing up.

Note that only the first test I created actually fails without this change. I added the second one for consistencies sake but it's not strictly necessary.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/spec/commands/fund_spec.rb [hunk 1]
```diff
@@ -55,6 +55,41 @@
...
+    install_gemfile <<-G
+      source "#{file_uri_for(gem_repo2)}"
+      group :whatever, optional: true do
+        gem 'has_funding_and_other_metadata'
+      end
+      gem 'has_funding'
+      gem 'rack-obama'
+    G
+
+    bundle "install", with: "whatever"
```
Comment (deivid-rodriguez) [inline bundler/spec/commands/fund_spec.rb:85]: Is `with: "whatever"` needed? The `--with` flag will be removed in Bundler 3, so Bundler 3 specs raise an error here.

Comment (Earlopain) [reply bundler/spec/commands/fund_spec.rb]: Ah, right. Yeah, those are going away. It's needed since only installed gems are considered for funding. Switched it over to using the env variable instead.

File: bundler/spec/commands/fund_spec.rb [hunk 2]
```diff
@@ -55,6 +55,45 @@
...
+    install_gemfile <<-G
+      source "#{file_uri_for(gem_repo2)}"
+      group :whatever, optional: true do
+        gem 'has_funding_and_other_metadata'
+      end
+      gem 'has_funding'
+      gem 'rack-obama'
+    G
+
+    ENV["BUNDLE_WITH"] = "whatever"
```
Comment (deivid-rodriguez) [inline bundler/spec/commands/fund_spec.rb:85]: You can instead run `bundle config with whatever` before `install_gemfile` above, so you don't need to `bundle install` again nor to clean up the `ENV` variable in an `ensure` block (I think it's not necessary anyways since the global `after` hook will reset `ENV` anyways).

**Review by deivid-rodriguez — COMMENTED** [review]
Just a small comment on the spec!

File: bundler/spec/commands/fund_spec.rb [hunk 3]
```diff
@@ -55,6 +55,42 @@
...
+    install_gemfile <<-G
+      source "#{file_uri_for(gem_repo2)}"
+      group :whatever, optional: true do
+        gem 'has_funding_and_other_metadata'
+      end
+      gem 'has_funding'
+      gem 'rack-obama'
+    G
+
+    bundle "config set with whatever"
```
Comment (deivid-rodriguez) [inline bundler/spec/commands/fund_spec.rb:85]: Sorry, I meant _before_ `install_gemfile` above, so that you can remove the line below and don't need to run `bundle "install"` again.

Comment (Earlopain) [reply bundler/spec/commands/fund_spec.rb]: Ah, right. Yeah, makes sense. It didn't really register that `install_gemfile` does that already

Comment (deivid-rodriguez) [reply bundler/spec/commands/fund_spec.rb]: No problem, it was something very minor! :)

**Review by deivid-rodriguez — APPROVED** [review]
Thanks for your fix!
