### PR TITLE
Prevent downgrades to untested rubygems versions

### LINKED ISSUE #4397: Prevent downgrading rubygems to versions older than the version shipping with each ruby
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/home/rahul/.rbenv/versions/3.0.0/bin/bundle install`

- **What did you expect to happen?**

  I expected Bundler to...

- **What happened instead?**

  Instead, what happened was...

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried...

- **Have you read our issues document, https://github.com/rubygems/rubygems/blob/master/bundler/doc/contributing/ISSUES.md?**

  ...

## Backtrace

```
Gem::Package::FormatError: package is corrupt, exception while verifying: wrong number of arguments (given 2, expected 1) (ArgumentError) in /home/rahul/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/cache/pg-1.2.3.gem
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:585:in `rescue in verify_entry'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:564:in `verify_entry'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:593:in `block in verify_files'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:592:in `verify_files'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:522:in `block (2 levels) in verify'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package/tar_reader.rb:29:in `new'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:519:in `block in verify'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package/file_source.rb:30:in `open'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package/file_source.rb:30:in `with_read_io'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:518:in `verify'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:499:in `spec'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/rubygems_integration.rb:252:in `spec_from_gem'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/source/rubygems.rb:124:in `install'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:67:in `install'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:18:in `install_from_spec'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:163:in `do_install'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:154:in `block in worker_pool'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /home/rahul/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/worker.rb:88:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.3
  Platforms   ruby, x86_64-linux
Ruby          3.0.0p0 (2020-12-25 revision 95aff214687a5e12c3eb57d056665741e734c188) [x86_64-linux]
  Full Path   /home/rahul/.rbenv/versions/3.0.0/bin/ruby
  Config Dir  /home/rahul/.rbenv/versions/3.0.0/etc
RubyGems      2.5.2
  Gem Home    /home/rahul/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0
  Gem Path    /home/rahul/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0:/home/rahul/.gem/ruby/3.0.0
  User Home   /home/rahul
  User Path   /home/rahul/.gem/ruby/3.0.0
  Bin Dir     /home/rahul/.rbenv/versions/3.0.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1f  31 Mar 2020
  Loaded      OpenSSL 1.1.1f  31 Mar 2020
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.25.1
  RVM         not installed
  rbenv       rbenv 1.1.2-40-g62d7798
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-02-19
Git SHA           unknown
Released Version  false
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
<No /home/rahul/aws-rails/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Downgrading rubygems can actually make your ruby installation no longer usable.

## What is your fix for the problem, implemented in this PR?

My fix is to prevent downgrading to ruby-rubygems combinations that are never tested.

Fixes #4397.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: lib/rubygems/commands/update_command.rb [hunk 1]
```diff
@@ -327,8 +327,26 @@ def which_to_update(highest_installed_gems, gem_names, system = false)
...
+  #
+  # Oldest version we support downgrading to. This is the version that
+  # originally ships with the first patch version of each ruby, because we never
+  # test each ruby against older rubygems, so we can't really guarantee it
+  # works. Version list can be checked here: https://stdgems.org/rubygems
+  #
   def oldest_supported_version
-    # for Ruby 2.3
-    @oldest_supported_version ||= Gem::Version.new("2.5.2")
+    @oldest_supported_version ||=
```
Comment (simi) [inline lib/rubygems/commands/update_command.rb:337]: Would it make sense for future rubies to include info of minimal supported RubyGems into `RbConfig::CONFIG` (or somewhere else) to be able to get rid of this list at some point (and at least do not need to maintain it starting Ruby 3.1 for now)?

Comment (deivid-rodriguez) [reply lib/rubygems/commands/update_command.rb:337]: Maybe? Not really sure.

If we wanted to remove this list we could bump this to use the rubygems version shipped originally with each ruby (here I'm using the version shipped with the `.0` version of each ruby). That version could be extracted from `RbConfig::CONFIG['rubylibdir'] + "/rubygems.rb"` without having to maintain this list.

But given this would require only 1/2 changes per year, it doesn't seem like a big deal?

Comment (deivid-rodriguez) [reply lib/rubygems/commands/update_command.rb:337]: What do you think @simi? Fine as is for now, or should I change anything?

Comment (simi) [reply lib/rubygems/commands/update_command.rb:337]: Feel free to keep it simple (as if) for now.

Comment (deivid-rodriguez) [reply lib/rubygems/commands/update_command.rb:337]: Alright, let's try it as it is and iterate as we go.
