### PR TITLE
Fix rdoc issues when running `gem` commands in a `bundle exec` context

### LINKED ISSUE #8477: `rake build` task builds bundled gems (rdoc) into incorrect file names.
### Describe the problem as clearly as you can

When building `rdoc`, the gem's target `.gem` name is incorrectly determined by the latest `rdoc` version installed.

For example

```
# Inside the local rdoc repo

$ gem list rdoc

*** LOCAL GEMS ***

rdoc (6.9.1, 6.9.0, 6.8.1, 6.7.0, default: 6.6.3.1, 6.6.2)
rorvswild_theme_rdoc (0.1)
$ be rake build 
Running RuboCop...
Inspecting 4 files
....

4 files inspected, no offenses detected

Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-rake (https://rubygems.org/gems/rubocop-rake)

You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false
rdoc 6.12.0 built to pkg/rdoc-6.9.1.gem. # <============= here
```

### Did you try upgrading RubyGems?

Yes

```
$ gem -v
3.6.3
```

### Post steps to reproduce the problem

1. Clone the [`rdoc` repo](https://github.com/ruby/rdoc)
2. Run `bundle install`
3. Make sure you do NOT have the [latest RDoc release](https://github.com/ruby/rdoc/releases) installed
4. Run `bundle exec rake build` and you should see something like `rdoc 6.12.0 built to pkg/rdoc-6.11.0.gem.`

### What were you expecting to happen?

RDoc is built to `rdoc-[version-indicated-in-rdoc-version.rb].gem`

### What actually happened?

RDoc is built to `rdoc-[latest-installed-rdoc-version].gem`

### Run `gem env` and paste the output below

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.6.3
  - RUBY VERSION: 3.3.3 (2024-06-12 patchlevel 89) [arm64-darwin23]
  - INSTALLATION DIRECTORY: /Users/hung-wulo/.gem/ruby/ruby-3.3.3
  - USER INSTALLATION DIRECTORY: /Users/hung-wulo/.gem/ruby/3.3.0
  - CREDENTIALS FILE: /Users/hung-wulo/.local/share/gem/credentials
  - RUBY EXECUTABLE: /Users/hung-wulo/.rubies/ruby-3.3.3/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/bin/git
  - EXECUTABLE DIRECTORY: /Users/hung-wulo/.gem/ruby/ruby-3.3.3/bin
  - SPEC CACHE DIRECTORY: /Users/hung-wulo/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/hung-wulo/.rubies/ruby-3.3.3/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-23
  - GEM PATHS:
     - /Users/hung-wulo/.gem/ruby/ruby-3.3.3
     - /Users/hung-wulo/.rubies/ruby-3.3.3/lib/ruby/gems/3.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/hung-wulo/.gem/ruby/ruby-3.3.3/bin
     - /Users/hung-wulo/.rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/bin
     - /Users/hung-wulo/.rubies/ruby-3.3.3/bin
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /Users/hung-wulo/.pyenv/shims
     - /Users/hung-wulo/.dev/binaries
     - /Users/hung-wulo/.cargo/bin
     - /opt/dev/bin/user
     - /usr/local/bin
     - /System/Cryptexes/App/usr/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
     - /Library/Apple/usr/bin
     - /usr/local/go/bin
     - ```

### LINKED ISSUE #8674: `bundle exec gem install <gem>` fails if rdoc 6.12.0 is installed (Ruby 3.3)
### Describe the problem as clearly as you can

`bundle exec gem install <gem>` fails if rdoc 6.12.0 is installed. Tested with Ruby 3.3.7.

I discovered this because `bundle rake install` (from [`require 'bundler/gem_tasks'`](https://github.com/84codes/rubocop-eighty-four-codes/blob/5480d5dd34c6a4947ee5b3af201feb97f3e85ad3/Rakefile#L3)) [runs](https://github.com/rubygems/rubygems/blob/f1a1979ad7281d7adb13343d2b5087ca9c95c4c9/bundler/lib/bundler/gem_helper.rb#L97-L103) `gem install <the built .gem file>`)

Good to know: it does not reproduce if you have `install: --no-document` in your `~/.gemrc`.

### Did you try upgrading rubygems & bundler?

I'm using the latest versions.

### Post steps to reproduce the problem

```shell
$ bundle init
Writing new Gemfile to /Users/dentarg/bundler-rdoc-bug/Gemfile

$ bundle
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ cat Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  arm64-darwin-23
  ruby

DEPENDENCIES

BUNDLED WITH
   2.6.8

$ ruby -v
ruby 3.3.7 (2025-01-15 revision be31f993d7) [arm64-darwin23]

$ bundle -v
Bundler version 2.6.8

$ gem -v
3.6.8

$ gem install -v 6.12.0 rdoc
Successfully installed rdoc-6.12.0
Parsing documentation for rdoc-6.12.0
Done installing documentation for rdoc after 1 seconds
1 gem installed

$ gem list rdoc

*** LOCAL GEMS ***

rdoc (6.12.0, default: 6.6.3.1)

$ bundle exec gem install dyno_metadata
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/version.rb:8: warning: already initialized constant RDoc::VERSION
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/version.rb:8: warning: previous definition of VERSION was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc.rb:70: warning: already initialized constant RDoc::VISIBILITIES
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc.rb:68: warning: previous definition of VISIBILITIES was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc.rb:76: warning: already initialized constant RDoc::DOT_DOC_FILENAME
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc.rb:74: warning: previous definition of DOT_DOC_FILENAME was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc.rb:81: warning: already initialized constant RDoc::GENERAL_MODIFIERS
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc.rb:79: warning: previous definition of GENERAL_MODIFIERS was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc.rb:86: warning: already initialized constant RDoc::CLASS_MODIFIERS
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc.rb:84: warning: previous definition of CLASS_MODIFIERS was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc.rb:91: warning: already initialized constant RDoc::ATTR_MODIFIERS
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc.rb:89: warning: previous definition of ATTR_MODIFIERS was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc.rb:96: warning: already initialized constant RDoc::CONSTANT_MODIFIERS
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc.rb:94: warning: previous definition of CONSTANT_MODIFIERS was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc.rb:101: warning: already initialized constant RDoc::METHOD_MODIFIERS
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc.rb:99: warning: previous definition of METHOD_MODIFIERS was here
Successfully installed dyno_metadata-0.0.4
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/rdoc.rb:36: warning: already initialized constant RDoc::RDoc::GENERATORS
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/rdoc.rb:36: warning: previous definition of GENERATORS was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/rdoc.rb:41: warning: already initialized constant RDoc::RDoc::UNCONDITIONALLY_SKIPPED_DIRECTORIES
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/rdoc.rb:41: warning: previous definition of UNCONDITIONALLY_SKIPPED_DIRECTORIES was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/rdoc.rb:46: warning: already initialized constant RDoc::RDoc::TEST_SUITE_DIRECTORY_NAMES
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/rdoc.rb:46: warning: previous definition of TEST_SUITE_DIRECTORY_NAMES was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/generator/darkfish.rb:64: warning: already initialized constant RDoc::Generator::Darkfish::BUILTIN_STYLE_ITEMS
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/generator/darkfish.rb:64: warning: previous definition of BUILTIN_STYLE_ITEMS was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/generator/darkfish.rb:80: warning: already initialized constant RDoc::Generator::Darkfish::GENERATOR_DIR
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/generator/darkfish.rb:80: warning: previous definition of GENERATOR_DIR was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/generator/darkfish.rb:85: warning: already initialized constant RDoc::Generator::Darkfish::VERSION
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/generator/darkfish.rb:85: warning: previous definition of VERSION was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/generator/darkfish.rb:90: warning: already initialized constant RDoc::Generator::Darkfish::DESCRIPTION
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/generator/darkfish.rb:90: warning: previous definition of DESCRIPTION was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/generator/darkfish.rb:640: warning: already initialized constant RDoc::Generator::Darkfish::SVNID_PATTERN
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/generator/darkfish.rb:637: warning: previous definition of SVNID_PATTERN was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/generator/ri.rb:12: warning: already initialized constant RDoc::Generator::RI::DESCRIPTION
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/generator/ri.rb:12: warning: previous definition of DESCRIPTION was here
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0/gems/rdoc-6.12.0/lib/rdoc/generator/pot.rb:63: warning: already initialized constant RDoc::Generator::POT::DESCRIPTION
/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/3.3.0/rdoc/generator/pot.rb:63: warning: previous definition of DESCRIPTION was here
Parsing documentation for dyno_metadata-0.0.4
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /Users/dentarg/.arm64_rubies/3.3.7/bin/ruby -c lib/dyno_metadata.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

  (ArgumentError) wrong number of arguments (given 4, expected 5)

ERROR:  While executing gem ... (ArgumentError)
    wrong number of arguments (ArgumentError)
```

It does not fail with Ruby 3.4.3, but the warnings are still printed.

```shell
$ ruby -v
ruby 3.4.3 (2025-04-14 revision d0b7e5b6a0) +PRISM [arm64-darwin23]

$ gem -v
3.6.8

$ bundle -v
Bundler version 2.6.8

$ gem list rdoc

*** LOCAL GEMS ***

rdoc (6.12.0, default: 6.10.0)

$ bundle exec gem install dyno_metadata
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/3.4.0/rdoc/version.rb:8: warning: already initialized constant RDoc::VERSION
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/gems/3.4.0/gems/rdoc-6.12.0/lib/rdoc/version.rb:8: warning: previous definition of VERSION was here
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/3.4.0/rdoc.rb:68: warning: already initialized constant RDoc::VISIBILITIES
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/gems/3.4.0/gems/rdoc-6.12.0/lib/rdoc.rb:68: warning: previous definition of VISIBILITIES was here
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/3.4.0/rdoc.rb:74: warning: already initialized constant RDoc::DOT_DOC_FILENAME
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/gems/3.4.0/gems/rdoc-6.12.0/lib/rdoc.rb:74: warning: previous definition of DOT_DOC_FILENAME was here
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/3.4.0/rdoc.rb:79: warning: already initialized constant RDoc::GENERAL_MODIFIERS
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/gems/3.4.0/gems/rdoc-6.12.0/lib/rdoc.rb:79: warning: previous definition of GENERAL_MODIFIERS was here
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/3.4.0/rdoc.rb:84: warning: already initialized constant RDoc::CLASS_MODIFIERS
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/gems/3.4.0/gems/rdoc-6.12.0/lib/rdoc.rb:84: warning: previous definition of CLASS_MODIFIERS was here
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/3.4.0/rdoc.rb:89: warning: already initialized constant RDoc::ATTR_MODIFIERS
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/gems/3.4.0/gems/rdoc-6.12.0/lib/rdoc.rb:89: warning: previous definition of ATTR_MODIFIERS was here
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/3.4.0/rdoc.rb:94: warning: already initialized constant RDoc::CONSTANT_MODIFIERS
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/gems/3.4.0/gems/rdoc-6.12.0/lib/rdoc.rb:94: warning: previous definition of CONSTANT_MODIFIERS was here
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/3.4.0/rdoc.rb:99: warning: already initialized constant RDoc::METHOD_MODIFIERS
/Users/dentarg/.arm64_rubies/3.4.3/lib/ruby/gems/3.4.0/gems/rdoc-6.12.0/lib/rdoc.rb:99: warning: previous definition of METHOD_MODIFIERS was here
Successfully installed dyno_metadata-0.0.4
Parsing documentation for dyno_metadata-0.0.4
Done installing documentation for dyno_metadata after 0 seconds
1 gem installed
```

### Which command did you run?

See above.

### What were you expecting to happen?

That it works without errors.

### What happened instead?

See above.

### If not included with the output of your command, run `bundle env` and paste the output below

Environment

```
Bundler       2.6.8
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.7p123 (2025-01-15 revision be31f993d7fa0219d85f7b3c694d454da4ecc10b) [arm64-darwin-23]
  Full Path   /Users/dentarg/.arm64_rubies/3.3.7/bin/ruby
  Config Dir  /Users/dentarg/.arm64_rubies/3.3.7/etc
RubyGems      3.6.8
  Gem Home    /Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0
  Gem Path    /Users/dentarg/.gem/ruby/3.3.0:/Users/dentarg/.arm64_rubies/3.3.7/lib/ruby/gems/3.3.0
  User Home   /Users/dentarg
  User Path   /Users/dentarg/.gem/ruby/3.3.0
  Bin Dir     /Users/dentarg/.arm64_rubies/3.3.7/bin
Tools
  Git         2.39.5 (Apple Git-154)
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

Bundler Build Metadata

```
Built At          1980-01-02
Git SHA           2a353e42e2e
Released Version  true
```

Bundler settings

```
disable_local_branch_check
  Set via BUNDLE_DISABLE_LOCAL_BRANCH_CHECK: true
disable_local_revision_check
  Set via BUNDLE_DISABLE_LOCAL_REVISION_CHECK: true
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Currently, running `gem` commands in a `bundle exec` contexts loads all installed rubygems plugins. This creates several issues, in particular, related to double loads of the RDoc gem, when mixed versions are loaded from plugins and from building docs in `gem install` or `gem build`.

## What is your fix for the problem, implemented in this PR?

In a `bundle exec` context, only plugins from gems in the bundle should be loaded, so this PR overrides `Gem.load_plugins` to do that.

Fixes #8477.
Fixes #8674.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/lib/bundler/rubygems_integration.rb [hunk 1]
```diff
@@ -447,6 +449,12 @@ def find_name(name)
     def default_stubs
       Gem::Specification.default_stubs("*.gemspec")
     end
+
+    private
+
+    def gem_class
+      class << Gem; self; end
+    end
```
Comment (st0012) [inline bundler/lib/bundler/rubygems_integration.rb:457]: Just curious: is this part of the fix too, or just `redefine_method` of `gem_class`?

Comment (deivid-rodriguez) [reply bundler/lib/bundler/rubygems_integration.rb:457]: Nah, I just noticed that we needed to find this class in several different places so I moved the logic to a separate method in 758f6615d6da5ac6d18fd4716b1262fcdd3c2035. The real fix is redefining `Gem.load_plugins` to only load plugins of gems inside the bundle.

Comment (st0012) [reply bundler/lib/bundler/rubygems_integration.rb:457]: I see. Thanks!
