### PR TITLE
Fix system man pages no longer working after bundler overrides `MANPATH`

### LINKED ISSUE #5038: Bundler incorrectly sets MANPATH when a gem contains a man/ directory
I noticed that when I had the [kramdown](https://github.com/gettalong/kramdown) gem in my `Gemfile`, `man` commands would mysteriously not be able to find system man pages (ex: `system("man ls")` or `IO.popen("man ls")`). 

## Steps To Reproduce

Control to make sure there's a man page for the `ls` command:

```shell
$ man ls
```

Without Bundler or kramdown (note: `command` bypasses any shell aliases):

```shell
$ command ruby -e 'system("man ls")'
```

With Bundler and kramdown loaded:

```shell
$ bundle exec ruby -e 'system("man ls")'
```

### Gemfile:

```ruby
source 'https://rubygems.org/'

gem 'kramdown', '2.3.1'
```

## Actual Output

Without Bundler or kramdown:

```
*opens the man page for ls*
```

With Bundler and kramdown loaded:

```
No manual entry for ls
```

## Expected Output

The commands should display the man page for `ls`.

## Versions

* ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
* rubygems 3.2.22
* Bundler version 2.2.24

Reproducible on ruby 2.x as well.

## Additional Information

On a hunch, I decided to test whether `$MANPATH` was being overrode:

```shell
$ command ruby -e 'system("echo $MANPATH")'

$ bundle exec ruby -e 'system("echo $MANPATH")'
/home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.0.0/gems/kramdown-2.3.1/man
```

It appears that because the kramdown gem contains a top-level `man/` directory, bundler is adding the directory to `MANPATH`. Since `MANPATH` is not set, this actually overrides the `MANPATH` causing the `man` command to not search `/usr/share/man` or `/usr/local/share/man`, thus preventing any Ruby code from opening or reading man pages installed on the system.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

When a gem is shipping man pages, bundler overrides MANPATH in a way that system man pages no longer work.

## What is your fix for the problem, implemented in this PR?

Leave ":" in front of the MANPATH. I found it on https://askubuntu.com/a/693612/100732.

EDIT: In the end, we're appending ":" to `MANPATH` to still give priority to man pages from gems, while defaulting to system man pages otherwise.

Fixes #5038.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/spec/runtime/setup_spec.rb [hunk 1]
```diff
@@ -757,28 +757,28 @@ def clean_load_path(lp)
...
-      it "adds the gem's man dir to the MANPATH" do
+      it "appends the gem's man dir to the MANPATH" do
         install_gemfile <<-G
           source "#{file_uri_for(gem_repo4)}"
           gem "with_man"
         G
 
         run "puts ENV['MANPATH']"
-        expect(out).to eq("#{default_bundle_path("gems/with_man-1.0/man")}#{File::PATH_SEPARATOR}/foo")
+        expect(out).to eq("/foo#{File::PATH_SEPARATOR}#{default_bundle_path("gems/with_man-1.0/man")}")
```
Comment (simi) [inline bundler/spec/runtime/setup_spec.rb:767]: If I understand it well, this now appends (instead of original prepending) bundle man path. Is that really intended?

Comment (deivid-rodriguez) [reply bundler/spec/runtime/setup_spec.rb:767]: You have a point. The trick as documented on the stackoverflow page is to prepend `:` to the `MANPATH`, but maybe it also works by appending it? I will try tomorrow. If appending `:` works, it will be the best behavior and it would make things fully backwards compatible.

If appending `:` doesn't work, we can still do better and keep the current behavior when the `MANPATH` is set.

I will improve this 👍.

Comment (postmodern) [reply bundler/spec/runtime/setup_spec.rb:767]: Confirmed prepending `:` works.

```
MANPATH=/home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.0.0/gems/kramdown-2.3.1/man man ls
No manual entry for ls
MANPATH=:/home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.0.0/gems/kramdown-2.3.1/man man ls
```

Comment (deivid-rodriguez) [reply bundler/spec/runtime/setup_spec.rb:767]: Appending `:` seems to also work, so that should be the way to go 👍.

Comment (deivid-rodriguez) [reply bundler/spec/runtime/setup_spec.rb]: I pushed a new version, it should be better now. But maybe I should add a `man ls` test to double check this works.

File: bundler/lib/bundler/runtime.rb [hunk 2]
```diff
@@ -265,7 +265,7 @@ def setup_manpath
 
       return if manuals.empty?
       Bundler::SharedHelpers.set_env "MANPATH", manuals.concat(
-        ENV["MANPATH"].to_s.split(File::PATH_SEPARATOR)
+        ENV["MANPATH"] ? ENV["MANPATH"].to_s.split(File::PATH_SEPARATOR) : [""]
```
Comment (simi) [inline bundler/lib/bundler/runtime.rb:268]: My idea was to enhance `MANPATH`:

1. if `MANPATH` is empty, assign to `manuals` with `:` prepended
2. if `MANPATH` is not empty, just append `manuals`

Comment (deivid-rodriguez) [reply bundler/lib/bundler/runtime.rb:268]: If understand this trick correctly, prepending `:` makes system man pages have precedence over gem man pages while appending it make gem man pages have precedence. So by appending, a gem overriding a potentially globally installed executable would get its man pages properly displayed.

But this is just a guess on how I would intiutively expect this to work, I need to try it and verify it.

Comment (deivid-rodriguez) [reply bundler/lib/bundler/runtime.rb:268]: Ok, I added some more specs to verify that this works exactly as we want, and they confirm appending `:` to the man path when not already set does the trick.

I skipped `MANPATH` specs on Windows because I don't think Windows has `man`?

Comment (simi) [reply bundler/lib/bundler/runtime.rb:268]: There is no `man` on Windows, at least no by default.

**Comment by simi** [comment]
:muscle:
