### PR TITLE
Fix misleading error if compact index cannot be copied

### LINKED ISSUE #5707: Bundler gives misleading permission denied error if source file cannot be copied
### Describe the problem as clearly as you can

Suppose `~/.bundle/cache/compact_index/rubygems.org.*` directory can only be read by root:

```
$ ls -al /home/git/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/
total 16904
drwxr-xr-x 4 git  git     4096 Jul 11 21:49 .
drwxr-xr-x 3 git  git     4096 Jul 11 21:49 ..
drwxr-xr-x 2 git  git     4096 Jul 11 21:49 info
drwxr-xr-x 2 git  git     4096 Jul 11 21:49 info-special-characters
-rw------- 1 root git 17290515 Jul 11 21:49 versions
```

`bundle install` fails with a misleading error message:

```
$ bundle install
There was an error while trying to write to `/tmp/bundler-compact-index-20220711-1823-npllre/versions`. It is likely that you need to grant write permissions for that path.
```

`bundle install --verbose` shows:

<details>
<pre>
$ bundle install --verbose
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:105:in `rescue in filesystem_access'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:102:in `filesystem_access'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/compact_index_client/updater.rb:38:in `block in update'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/tmpdir/lib/tmpdir.rb:96:in `mktmpdir'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/compact_index_client/updater.rb:29:in `update'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/compact_index_client.rb:92:in `update'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/compact_index_client.rb:79:in `update_and_parse_checksums!'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/fetcher/compact_index.rb:70:in `available?'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/fetcher/compact_index.rb:16:in `call'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/fetcher/compact_index.rb:16:in `block in compact_index_request'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/fetcher.rb:162:in `use_api'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:431:in `block in api_fetchers'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:431:in `select'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:431:in `api_fetchers'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:436:in `block in remote_specs'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/index.rb:9:in `build'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:435:in `remote_specs'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:131:in `specs'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:169:in `index_for'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:177:in `results_for'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:114:in `search_for'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:255:in `block in verify_gemfile_dependencies_are_found!'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:252:in `map!'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:252:in `verify_gemfile_dependencies_are_found!'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:50:in `start'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:24:in `resolve'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:269:in `resolve'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:181:in `resolve_remotely!'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:271:in `resolve_if_needed'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:82:in `block in run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/process_lock.rb:9:in `open'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/process_lock.rb:9:in `lock'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:71:in `run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:23:in `install'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli/install.rb:62:in `run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:255:in `block in install'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/settings.rb:131:in `temporary'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:254:in `install'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:31:in `dispatch'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:25:in `start'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/exe/bundle:48:in `block in <top (required)>'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/exe/bundle:36:in `<top (required)>'
  /usr/local/bin/bundle:25:in `load'
  /usr/local/bin/bundle:25:in `<main>'
</pre>
</details>

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

With a `Gemfile` in the path:

1. Run `bundle install`
2. `chown root  ~bundle/cache/compact_index/rubygems.org.443.*/versions`
3. `chmod 600  ~bundle/cache/compact_index/rubygems.org.443.*/versions`
4. `rm Gemfile.lock`
5. `bundle install`

### Which command did you run?

`bundle install`

### What were you expecting to happen?

An error message pointing to the source `versions`.

### What actually happened?

An error message pointing to the target path.

This happens because `SharedHelpers.filesystem_access` wraps only the target directory:

https://github.com/rubygems/rubygems/blob/46a92b2b033e1e42a780ab5559782aacca3230a4/bundler/lib/bundler/compact_index_client/updater.rb#L34-L36

This is supposed to wrap access errors nicely, but the raw exception would have been more useful here:

https://github.com/rubygems/rubygems/blob/46a92b2b033e1e42a780ab5559782aacca3230a4/bundler/lib/bundler/shared_helpers.rb#L102-L105

I had to hack the helper to see the real message:

```diff
diff --git a/lib/bundler/shared_helpers.rb b/lib/bundler/shared_helpers.rb
index 6e83bc5ff4..949fd5753f 100644
--- a/lib/bundler/shared_helpers.rb
+++ b/lib/bundler/shared_helpers.rb
@@ -101,6 +101,8 @@ module Bundler
     # @see {Bundler::PermissionError}
     def filesystem_access(path, action = :write, &block)
       yield(path.dup.tap{|x| x.untaint if RUBY_VERSION < "2.7" })
+    rescue => e
+      raise e
     rescue Errno::EACCES
       raise PermissionError.new(path, action)
     rescue Errno::EAGAIN
```

Which then gave me the right error:

```
Errno::EACCES: Permission denied @ rb_sysopen - /home/git/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:103:in `read'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:103:in `read'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:103:in `filesystem_access'
```

https://github.com/rubygems/rubygems/pull/5110 doesn't help here because the `SharedHelpers.filesystem_access` still hides the original `Errno::EACCES` message.

Some ideas to fix this:

1. Allow the `PermissionError` to report the original exception message.
1. Make it possible to wrap multiple paths in `SharedHelpers.filesystem_access`.
1. Manually check `File#readable?`.

### PR DESCRIPTION
**Pull request by stanhu**
## What was the end-user or developer problem that led to this PR?

Previously if `~/.bundle/cache/compact_index/rubygems.org.*/version`
were owned by root with read-only access, `bundle install` would fail
with a misleading error message. For example:

```
There was an error while trying to write to `/tmp/bundler-compact-index-20220711-1823-npllre/versions`. It is
likely that you need to grant write permissions for that path.
```

This happened because the EACCESS error was caught by
`SharedHelpers.filesystem_access`, which makes it look like the target
directory is at fault instead of the source.

## What is your fix for the problem, implemented in this PR?

Dropping this guard appears to make `bundle install` report the right
error:

<details>
<pre>
Bundler::PermissionError: There was an error while trying to read from `/home/git/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions`. It is likely that you need to grant read permissions for that path.
/usr/local/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:105:in `rescue in filesystem_access'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:102:in `filesystem_access'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/compact_index_client/cache.rb:83:in `lines'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/compact_index_client/cache.rb:55:in `checksums'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/compact_index_client.rb:80:in `update_and_parse_checksums!'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/fetcher/compact_index.rb:70:in `available?'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/fetcher/compact_index.rb:16:in `call'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/fetcher/compact_index.rb:16:in `block in compact_index_request'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/fetcher.rb:162:in `use_api'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:431:in `block in api_fetchers'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:431:in `select'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:431:in `api_fetchers'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:436:in `block in remote_specs'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/index.rb:9:in `build'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:435:in `remote_specs'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:131:in `specs'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:169:in `index_for'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:177:in `results_for'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:114:in `search_for'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:255:in `block in verify_gemfile_dependencies_are_found!'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:252:in `map!'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:252:in `verify_gemfile_dependencies_are_found!'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:50:in `start'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:24:in `resolve'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:269:in `resolve'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:181:in `resolve_remotely!'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:271:in `resolve_if_needed'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:82:in `block in run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/process_lock.rb:19:in `rescue in lock'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/process_lock.rb:15:in `lock'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:71:in `run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:23:in `install'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli/install.rb:62:in `run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:255:in `block in install'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/settings.rb:131:in `temporary'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:254:in `install'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:31:in `dispatch'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:25:in `start'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/exe/bundle:48:in `block in <top (required)>'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/exe/bundle:36:in `<top (required)>'
  /usr/local/bin/bundle:25:in `load'
  /usr/local/bin/bundle:25:in `<main>'
</pre>
</details>

We can't simply drop this guard because that causes the opposite
problem: the permission error appears to come from the the source
instead of the target, since `CompactIndexClient::Cache#lines` also
wraps read access errors.

Instead, we attempt a read of the source so that we can raise the
proper error.

Closes #5707

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/lib/bundler/compact_index_client/updater.rb [hunk 1]
```diff
@@ -31,9 +31,7 @@ def update(local_path, remote_path, retrying = nil)
 
           # first try to fetch any new bytes on the existing file
           if retrying.nil? && local_path.file?
-            SharedHelpers.filesystem_access(local_temp_path) do
-              FileUtils.cp local_path, local_temp_path
-            end
+            FileUtils.cp local_path, local_temp_path
```
Comment (stanhu) [inline bundler/lib/bundler/compact_index_client/updater.rb:34]: This might cause a misleading error message for `local_temp_path`. Hmm.

File: bundler/lib/bundler/compact_index_client/updater.rb [hunk 2]
```diff
@@ -31,6 +31,11 @@ def update(local_path, remote_path, retrying = nil)
 
           # first try to fetch any new bytes on the existing file
           if retrying.nil? && local_path.file?
+            # Ensure that we can read the source since we can't distinguish an
+            # access error between the source and target file in FileUtils.cp.
+            SharedHelpers.filesystem_access(local_path, :read) do
```
Comment (stanhu) [inline bundler/lib/bundler/compact_index_client/updater.rb:36]: In general, I find `SharedHelpers.filesystem_access` problematic because they don't check whether the `EACCES` error comes from the path they're supposed to protect. Nested calls can attribute the exception to the wrong path.

**Comment by deivid-rodriguez** [comment]
Thanks @stanhu, this must've been so confusing...

I pushed a modified version to fix this that I think it's a bit cleaner.

**Comment by stanhu** [comment]
@deivid-rodriguez Thanks, that's much cleaner.

File: bundler/lib/bundler/compact_index_client/updater.rb [hunk 3]
```diff
@@ -98,6 +97,20 @@ def checksum_for_file(path)
...
       end
+
+      private
+
+      def copy_file(source, dest)
+        SharedHelpers.filesystem_access(source, :read) do
+          File.open(source, "r") do |s|
+            SharedHelpers.filesystem_access(dest, :write) do
+              File.open(dest, "wb", s.stat.mode) do |f|
+                IO.copy_stream(s, f)
```
Comment (stanhu) [inline bundler/lib/bundler/compact_index_client/updater.rb:108]: Just in case someone runs this test on a slightly outdated kernel. There was a bug in Linux 5.10 that caused `IO.copy_stream` to copy 0 bytes. It has since been fixed: https://github.com/docker/for-linux/issues/1015#issuecomment-985799437

Comment (stanhu) [reply bundler/lib/bundler/compact_index_client/updater.rb:108]: Ah, of course. So no change in behavior. Great, thanks!
