### PR TITLE
Fix outdated lockfile during `bundle lock` when source changes

### LINKED ISSUE #8961: Using eagerly bumped git version of a gem doesn't downgrade when switching back to rubygems
### Describe the problem as clearly as you can

When using a git gem, the version in git may be more recent than what is available on rubygems. Using that works fine of course, but when going back to resolving it from rubygems it keeps the version from the git source, which doesn't exist.

### Post steps to reproduce the problem

Start out with the following gemfile

```rb
source "https://rubygems.org"
gem "ruby-lsp", github: "shopify/ruby-lsp"
```

Run `bundle lock`. Lockfile contents:

```
GIT
  remote: https://github.com/shopify/ruby-lsp.git
  revision: 8d6751a6e4128e2fa88835398ee12db9fed54fd8
  specs:
    ruby-lsp (0.26.2)
      language_server-protocol (~> 3.17.0)
      prism (>= 1.2, < 2.0)
      rbs (>= 3, < 5)

GEM
  remote: https://rubygems.org/
  specs:
    language_server-protocol (3.17.0.5)
    logger (1.7.0)
    prism (1.4.0)
    rbs (3.9.5)
      logger

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  ruby-lsp!

BUNDLED WITH
   2.7.2
```

Now, modify the gemfile to point to rubygems:

```rb
source "https://rubygems.org"
gem "ruby-lsp"
```

Run `bundle lock`. Lockfile content:

```
GEM
  remote: https://rubygems.org/
  specs:
    language_server-protocol (3.17.0.5)
    logger (1.7.0)
    prism (1.4.0)
    rbs (3.9.5)
      logger
    ruby-lsp (0.26.2)
      language_server-protocol (~> 3.17.0)
      prism (>= 1.2, < 2.0)
      rbs (>= 3, < 5)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  ruby-lsp

BUNDLED WITH
   2.7.2
```

At the time of writing this there is no `ruby-lsp` 0.26.2 and yet it doesn't complain or downgrade it. Only after running other bundler commands (like `bundle install`) does it notice that something is wrong. I feel like bundler should not result in invalid lockfiles when `bundle lock` is invoked. Perhaps this is related to https://github.com/rubygems/rubygems/issues/8238? It looks somewhat similar.

### If not included with the output of your command, run `bundle env` and paste the output below

<details><summary>bundle env</summary>
<p>

## Environment

```
Bundler       2.7.2
  Platforms   ruby, x86_64-linux
Ruby          3.4.2p28 (2025-02-15 revision d2930f8e7a5db8a7337fa43370940381b420cc3e) [x86_64-linux]
  Full Path   /home/user/.rbenv/versions/3.4.2/bin/ruby
  Config Dir  /home/user/.rbenv/versions/3.4.2/etc
RubyGems      3.7.2
  Gem Home    /home/user/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0
  Gem Path    /home/user/.gem/ruby/3.4.0:/home/user/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0
  User Home   /home/user
  User Path   /home/user/.gem/ruby/3.4.0
  Bin Dir     /home/user/.rbenv/versions/3.4.2/bin
Tools         
  Git         2.51.0
  RVM         not installed
  rbenv       rbenv 1.3.2
  chruby      not installed
```

## Bundler Build Metadata

```
Timestamp  2025-09-09
Git SHA    b463ced1459
```

## Bundler settings

```
gem.changelog
  Set for the current user (/home/user/.bundle/config): false
gem.ci
  Set for the current user (/home/user/.bundle/config): false
gem.coc
  Set for the current user (/home/user/.bundle/config): false
gem.linter
  Set for the current user (/home/user/.bundle/config): false
gem.mit
  Set for the current user (/home/user/.bundle/config): false
gem.test
  Set for the current user (/home/user/.bundle/config): "minitest"
```

### Gemfile

```ruby
# Gemfile
source "https://rubygems.org"

gem "ruby-lsp"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    language_server-protocol (3.17.0.5)
    logger (1.7.0)
    prism (1.4.0)
    rbs (3.9.5)
      logger
    ruby-lsp (0.26.1)
      language_server-protocol (~> 3.17.0)
      prism (>= 1.2, < 2.0)
      rbs (>= 3, < 5)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  ruby-lsp

BUNDLED WITH
   2.7.2
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Earlopain**
## What was the end-user or developer problem that led to this PR?

Closes #8961

When the source used to be git and switches back to rubygems, it is possible that the git source contains a version that ruybgems doesn't know about yet.

## What is your fix for the problem, implemented in this PR?

Since different sources are not guaranteed to contain the same information , it seems ok to simply re-resolve the dependency in such cases.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: bundler/spec/install/gemfile/sources_spec.rb [hunk 1]
```diff
@@ -1495,8 +1495,8 @@
       G
     end
 
-    it "conservatively installs the existing locked version" do
-      expect(the_bundle).to include_gems("myrack 1.0.0")
+    it "discards the old source and install the version from the new source" do
```
Comment (Earlopain) [inline bundler/spec/install/gemfile/sources_spec.rb]: I initially had this to only change when the source type changes. But I don't think that makes sense, since the same also applies when just the source url changes, like in this spec here.

Does that make sense?

Comment (deivid-rodriguez) [reply bundler/spec/install/gemfile/sources_spec.rb]: I think ideally this spec stays the same? You may want to change the source, but still keep the same version. Say you're moving your private sources from one private registry to another.

Comment (Earlopain) [reply bundler/spec/install/gemfile/sources_spec.rb]: Makes sense. I will take a look

Comment (Earlopain) [reply bundler/spec/install/gemfile/sources_spec.rb]: I can't seem to figure this out. I tried adding `source.specs.search([name, s.version]).empty?` to the condition but it looks like I'm not supposed to access `source.specs` yet since the test then can't find the gem in the remote anymore.

Comment (deivid-rodriguez) [reply bundler/spec/install/gemfile/sources_spec.rb]: Definition logic, although has gotten gradually simpler, is unfortunately still quite complicated. I'll have another look tomorrow and try figure it out!

Comment (deivid-rodriguez) [reply bundler/spec/install/gemfile/sources_spec.rb]: I pushed some changes to get your spec and this spec to pass and to simplify the related code a bit, too.

Comment (deivid-rodriguez) [reply bundler/spec/install/gemfile/sources_spec.rb]: The gist of the fix is that, rather than explicitly unlocking the gem (which forces the version to be bumped in all cases), we don't add it to the "base resolve" (which is something like "the set of versions that should preferably stay the same"), and we also don't add a lower bound requirement to prevent downgrades, since a downgrade is possibly expected if the source changes.

Comment (Earlopain) [reply bundler/spec/install/gemfile/sources_spec.rb]: Thanks for the explanation! No chance I would have come up with the fix myself. At least the test was good :sweat_smile:

Comment (deivid-rodriguez) [reply bundler/spec/install/gemfile/sources_spec.rb]: Well, you were on the right track and your initial patch was helpful for figuring it out, thank you!
