### PR TITLE
Don't corrupt lockfile when user moves a gem that's already in the lockfile to an incorrect source by mistake

### LINKED ISSUE #5067: Incorrectly specifying a gem under a source where it doesn't exist generates an incorrect lockfile if the gem is cached
### Describe the problem as clearly as you can

Issue was first reported by @sambostock at https://github.com/rubygems/rubygems/issues/4875#issuecomment-910414293.

As stated in the title, incorrectly specifying a gem under a source where it doesn't exist generates an incorrect lockfile if the gem had been previously cached from the correct source.

Furthermore, this lockfile cannot be properly installed on a fresh machine because it's completely incorrect.

### Did you try upgrading rubygems & bundler?

Yes, it happens on the latest bundler.

### Post steps to reproduce the problem

A sample repository to reproduce this was provided at: https://github.com/sambostock/rubygems-rubygems-4875-demo.

If you have a Gemfile and `Gemfile.lock` like the following, where `some_private_gem` lives at `http://localhost:9292` and depends on `example`, which lives at `https://rubygems.org`:

```ruby
source 'https://rubygems.org'

source 'http://localhost:9292' do
  gem 'some_private_gem'
end
```

```
GEM
  remote: http://localhost:9292/
  specs:
    example (1.0.2)
    some_private_gem (0.1.0)
      example (~> 1.0)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  arm64-darwin-20

DEPENDENCIES
  example!
  some_private_gem!

BUNDLED WITH
   2.3.0.dev
```

If you mistakenly edit the lockfile like this

```diff
diff --git a/app/Gemfile b/app/Gemfile
index aa3930e..ae9231a 100644
--- a/app/Gemfile
+++ b/app/Gemfile
@@ -2,6 +2,7 @@ source 'https://rubygems.org'
 
 source 'http://localhost:9292' do
   gem 'some_private_gem'
+  gem 'example'
 end
```

Then `bundle install` will generate an incorrect lockfile like the following that will always error out on machines where `example` is not already installed or where `bundler` needs to re-resolve for some reason:

```
GEM
  remote: http://localhost:9292/
  specs:
    example (1.0.2)
    some_private_gem (0.1.0)
      example (~> 1.0)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  arm64-darwin-20
  x86_64-darwin-20

DEPENDENCIES
  example!
  some_private_gem!

BUNDLED WITH
   2.3.0.dev
```

This incorrect lockfile is generated _only_ when the `example` gem from rubygems.org was previously present in cache.

Initial investigation shows that the problem is that the current gem cache does not discriminate sources.

### Which command did you run?

`bundle install` on a `Gemfile` where the source for a gem is incorrect.

### What were you expecting to happen?

An error.

### What actually happened?

"Success" with an incorrect lockfile getting generated.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

A mistake by a user editing a Gemfile could make bundler generate a bad lockfile, and a situation quite tricky to workaround.

## What is your fix for the problem, implemented in this PR?

At the beginning of resolution, where we make sure that all top level dependencies are available, make sure we ignore locked specs.

Fixes #5067.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by doodzik — APPROVED** [review]

**Comment by doodzik** [comment]
This is such a good change 🙌

File: bundler/lib/bundler/definition.rb [hunk 1]
```diff
@@ -385,8 +385,8 @@ def ensure_equivalent_gemfile_and_lockfile(explicit_flag = false)
 
       # Check if it is possible that the source is only changed thing
       if (new_deps.empty? && deleted_deps.empty?) && (!new_sources.empty? && !deleted_sources.empty?)
-        new_sources.reject! {|source| (source.path? && source.path.exist?) || equivalent_rubygems_remotes?(source) }
-        deleted_sources.reject! {|source| (source.path? && source.path.exist?) || equivalent_rubygems_remotes?(source) }
+        new_sources.reject! {|source| source.path? && source.path.exist? }
+        deleted_sources.reject! {|source| source.path? && source.path.exist? }
```
Comment (doodzik) [inline bundler/lib/bundler/definition.rb:385]: \nit Would it make sense to add a dedicated method for the `source.path? && source.path.exist?` check on source? IMO this would make the code a bit more readable.

File: bundler/lib/bundler/definition.rb [hunk 2]
```diff
@@ -716,6 +716,10 @@ def converge_specs(specs)
           if s.source.include?(effective_source)
             deps << dep
           else
+            if effective_source.dup.specs.search_all(s.name).empty?
```
Comment (doodzik) [inline bundler/lib/bundler/definition.rb:719]: \nit the check can probably be moved into a separate method so it doesn't expose as many internals.

File: bundler/lib/bundler/definition.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply bundler/lib/bundler/definition.rb:385]: Yes, I actually had some more refactorings on gemfile vs lockfile equivalence, and I was planning on removing this whole block of code, since I don't think it's needed. But I decided to leave them out of this PR for now to keep it smaller.

File: bundler/lib/bundler/definition.rb (hunk 2 above)
Comment (deivid-rodriguez) [reply bundler/lib/bundler/definition.rb:719]: Yes, I will do that, thanks! :+1:

Comment (deivid-rodriguez) [reply bundler/lib/bundler/definition.rb]: I wasn't fully satisfied with checking this at this point, so I'm working on a simpler solution. I marked this a WIP for now.

File: bundler/lib/bundler/definition.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply bundler/lib/bundler/definition.rb:385]: I created #5120 that completely removes this block of code.
