### PR TITLE
Give a better error when trying to write the lock file on a read-only filesystem

### LINKED ISSUE #5893: Bundler 2.3.21 attempts to update PLATFORMS in Gemfile.lock on bundle exec, fails on read-only filesystem
### Describe the problem as clearly as you can

We run our apps with a read-only filesystem in a Docker container.

In many of our apps' Gemfile.lock, we have a `PLATFORMS` section that lists various platforms we use for development and deployment; we do not typically maintain this list ourselves. Example:

```
PLATFORMS
  x86_64-darwin-17
  x86_64-darwin-19
  x86_64-darwin-20
  x86_64-linux-musl
```

As of Bundler 2.3.21, when we run our app using `bundle exec`, it attempts to write to Gemfile.lock to add the platform relevant for the current system (e.g. linux on the server). Because we're running in a read only file system, this fails with:

`Errno::EROFS: Read-only file system @ rb_sysopen - /app/Gemfile.lock`

**As a workaround**, we have found that removing other platforms and adding the `ruby` platform to Gemfile.lock prevents the issue, but we don't really understand why, or if this is a good general solution.

### Did you try upgrading rubygems & bundler?

Yes :) 

### What were you expecting to happen?

Running `bundle exec` commands does not attempt to write to Gemfile.lock or any other files.

### What actually happened?

`Errno::EROFS: Read-only file system @ rb_sysopen - /app/Gemfile.lock`

### If not included with the output of your command, run `bundle env` and paste the output below

Can provide this if needed.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

If `bundle exec` tries to write to the lock file on a read-only filesystem, Bundler will fail but it's unclear why.

## What is your fix for the problem, implemented in this PR?

Suggest a solution to fix the problem.

Closes #5893.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by lyricsboy — COMMENTED** [review]
This looks like a good improvement to me! It would definitely have helped my understanding of the problem.

**Comment by deivid-rodriguez** [comment]
Thanks! I will eventually loop back and investigate why this broke CI.

File: bundler/lib/bundler/shared_helpers.rb [hunk 1]
```diff
@@ -115,10 +115,6 @@ def filesystem_access(path, action = :write, &block)
       raise NoSpaceOnDeviceError.new(path, action)
     rescue Errno::ENOTSUP
       raise OperationNotSupportedError.new(path, action)
-    rescue Errno::EEXIST, Errno::ENOENT
-      raise
-    rescue SystemCallError => e
-      raise GenericSystemCallError.new(e, "There was an error #{[:create, :write].include?(action) ? "creating" : "accessing"} `#{path}`.")
```
Comment (segiddins) [inline bundler/lib/bundler/shared_helpers.rb:121]: I'm a bit concerned about removing this fallback. Instead, what if we raised a new exception on `Errno::EROFS` that `write_lock` could rescue

Comment (deivid-rodriguez) [reply bundler/lib/bundler/shared_helpers.rb:121]: Yes, I was just thinking the same, sounds good 👍.

**Comment by deivid-rodriguez** [comment]
This now rescues a specific Bundler exception for read-only situations 👍
