### PR TITLE
Fix `gem install does-not-exist` being super slow

### LINKED ISSUE #6821: `gem install <gem-that-does-not-exist>` is very slow
### Describe the problem as clearly as you can

Not a huge issue but `gem install <gem-that-does-not-exist>` is very slow, unnecessarily.

```

### Did you try upgrading RubyGems?

Yes.

### Post steps to reproduce the problem

```
$ time sudo gem install --debug --verbose pony-gem
NOTE:  Debugging mode prints all exceptions even when rescued
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/pony-gem
404 Not Found
Exception `Gem::RemoteFetcher::FetchError' at /usr/local/lib/site_ruby/3.1.0/rubygems/remote_fetcher.rb:232 - bad response Not Found 404 (https://index.rubygems.org/info/pony-gem)
GET https://index.rubygems.org/prerelease_specs.4.8.gz
200 OK
GET https://index.rubygems.org/specs.4.8.gz
200 OK
# >>>>>>>>>>> IT HANGS HERE FOR A MINUTE <<<<<<<<<<<<
Exception `Gem::UnsatisfiableDependencyError' at /usr/local/lib/site_ruby/3.1.0/rubygems/resolver/installer_set.rb:82 - Unable to resolve dependency: user requested 'pony-gem (>= 0)'
ERROR:  Could not find a valid gem 'pony-gem' (>= 0) in any repository
GET https://rubygems.org/latest_specs.4.8.gz
200 OK
ERROR:  Possible alternatives: donsgem, moneygem, poc_gem, pokegem, pry-gem, tinygem

real    1m15.133s
user    0m0.010s
sys     0m0.021s
```

### Which command did you run?

`gem install` with a gem that does not exist.

### What were you expecting to happen?

After the gem is found to not exist in the compact index API, fail directly.

### What actually happened?

RubyGems fallback to trying to find the gem inside the full marshaled index, which is very slow.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Every time a gem is not found in the Compact Index API, RubyGems will fallback to the full index, which is very slow. This is unnecessary because both indexes should be providing the same gems, so if a gem can't be found in the Compact Index API, it won't be found in the full index.

## What is your fix for the problem, implemented in this PR?

We _do_ want a fallback to the full index, whenever the Compact Index API is not implemented. To detect that, we check that the API responds to the "/versions" endpoint, just like Bundler does.

Before:

```
$ time gem install fooasdsfafs
ERROR:  Could not find a valid gem 'fooasdsfafs' (>= 0) in any repository
gem  20,77s user 0,59s system 96% cpu 22,017 total
```

After:

```
$ time gem install fooasdsfafs
ERROR:  Could not find a valid gem 'fooasdsfafs' (>= 0) in any repository
gem  5,02s user 0,09s system 91% cpu 5,568 total
```

Fixes #6821, addressing the issues with https://github.com/rubygems/rubygems/pull/6990.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Also note that this is still slower than it should, because "did you mean" functionality to find similarly named gems still uses the full index. It should probably be switched to use the `/names` Compact Index endpoint instead. These are the results without similarly named gems suggestions:

#### Before

```
$ time gem install fooasdsfafs --no-suggestions
ERROR:  Could not find a valid gem 'fooasdsfafs' (>= 0) in any repository
gem  14,95s user 0,54s system 93% cpu 16,601 total
```

#### After

```
$ time gem install fooasdsfafs --no-suggestions                         
ERROR:  Could not find a valid gem 'fooasdsfafs' (>= 0) in any repository
gem  0,10s user 0,02s system 29% cpu 0,406 total
```

File: lib/rubygems/source.rb [hunk 1]
```diff
@@ -79,7 +79,7 @@ def dependency_resolver_set # :nodoc:
       uri
     end
 
-    bundler_api_uri = enforce_trailing_slash(fetch_uri)
+    bundler_api_uri = enforce_trailing_slash(fetch_uri) + "./versions"
```
Comment (martinemde) [inline lib/rubygems/source.rb:82]: I'm curious about why the `/./` is put into the url. Am I misunderstanding the code?

**Review by martinemde — APPROVED** [review]
Looks a lot simpler. Glad you found the problem.

**Comment by martinemde** [comment]
Using /names for did-you-mean seems like a great way to utilize that endpoint. I assume it's ready to go but it's never been used. I'd support that.

File: lib/rubygems/source.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply lib/rubygems/source.rb:82]: I used the same style that was used previously with the old API before https://github.com/rubygems/rubygems/commit/c9d157defb1783a7c5f5b890916cc3349dd1ffb7#diff-3a6811b74628a1ec350eb51728ad8c87e8110e8fb4d8938567dc50e9dcc0958eL83, but I don't think it's necessary, let me remove it.

**Review by LabsideArowo — COMMENTED** [review]
✨✨✅
