### PR TITLE
Don't load `resolv` unnecessarily

### LINKED ISSUE #4605: Can't run bundle install on windows
C:\Users\Mahmoud\blog>bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `C:/Ruby27-x64/bin/bundle install`

- **What did you expect to happen?**

  I expected Bundler to...

- **What happened instead?**

  Instead, what happened was...

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried...

- **Have you read our issues document, https://github.com/rubygems/rubygems/blob/master/bundler/doc/contributing/ISSUES.md?**

  ...

## Backtrace

```
ArgumentError: unknown encoding name - CP720
  C:/Ruby27-x64/lib/ruby/2.7.0/win32/registry.rb:72:in `find'
  C:/Ruby27-x64/lib/ruby/2.7.0/win32/registry.rb:72:in `<module:Win32>'
  C:/Ruby27-x64/lib/ruby/2.7.0/win32/registry.rb:4:in `<top (required)>'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/2.7.0/win32/resolv.rb:7:in `<top (required)>'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/2.7.0/resolv.rb:171:in `<class:Hosts>'
  C:/Ruby27-x64/lib/ruby/2.7.0/resolv.rb:168:in `<class:Resolv>'
  C:/Ruby27-x64/lib/ruby/2.7.0/resolv.rb:38:in `<top (required)>'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/remote_fetcher.rb:9:in `<top (required)>'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/fetcher/index.rb:4:in `<top (required)>'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/fetcher.rb:221:in `<class:Fetcher>'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/fetcher.rb:11:in `<module:Bundler>'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/fetcher.rb:9:in `<top (required)>'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli/install.rb:52:in `run'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli.rb:259:in `block in install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/settings.rb:134:in `temporary'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli.rb:258:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli.rb:30:in `dispatch'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli.rb:24:in `start'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/exe/bundle:49:in `block in <top (required)>'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/exe/bundle:37:in `<top (required)>'
  C:/Ruby27-x64/bin/bundle:23:in `load'
  C:/Ruby27-x64/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.17
  Platforms   ruby, x64-mingw32
Ruby          2.7.3p183 (2021-04-05 revision 6847ee089d7655b2a0eea4fee3133aeacd4cc7cc) [x64-mingw32]
  Full Path   C:/Ruby27-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.1.6
  Gem Home    C:/Ruby27-x64/lib/ruby/gems/2.7.0
  Gem Path    C:/Users/Mahmoud/.gem/ruby/2.7.0;C:/Ruby27-x64/lib/ruby/gems/2.7.0
  User Home   C:/Users/Mahmoud
  User Path   C:/Users/Mahmoud/.gem/ruby/2.7.0
  Bin Dir     C:/Ruby27-x64/bin
OpenSSL
  Compiled    OpenSSL 1.1.1k  25 Mar 2021
  Loaded      OpenSSL 1.1.1k  25 Mar 2021
  Cert File   C:/Ruby27-x64/ssl/cert.pem
  Cert Dir    C:/Ruby27-x64/ssl/certs
Tools
  Git         2.31.1.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-05-05
Git SHA           69cbd6e10e
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'duktape'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
<No C:/Users/Mahmoud/blog/Gemfile.lock found>
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Bundler loads the `resolv` library unnecessarily, and that could cause issues with default gems, and maybe others like #4605.

## What is your fix for the problem, implemented in this PR?

Don't load `resolv`. This will be followed by another PR to rubygems to do the samething. Splitting just so that each PR gets its own separated changelog entry.

I think this should either fix #4605 or at least change it to throw a different error, so I'll set this PR to close that ticket.

Closes #4605.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

File: lib/rubygems/remote_fetcher.rb [hunk 1]
```diff
@@ -78,7 +77,7 @@ def self.fetcher
   # +headers+: A set of additional HTTP headers to be sent to the server when
   #            fetching the gem.
 
-  def initialize(proxy=nil, dns=nil, headers={})
+  def initialize(proxy=nil, headers={})
```
Comment (deivid-rodriguez) [inline lib/rubygems/remote_fetcher.rb:80]: @simi Do you know a good way to gracefully deprecate the removal of one parameter? :thinking: I don't think this is public API but still.

Comment (simi) [reply lib/rubygems/remote_fetcher.rb:80]: My initial idea is to handle arguments manually.

```ruby
def deprecated_initialize(*arguments)
  if arguments.length > 3
    raise ArgumentError, "(wrong number of arguments (given #{arguments.length}, expected 0..3))"
  end

  if arguments.length == 3
    warn "dns is not used anymore deprecation warning"
    proxy = arguments[0]
    headers = arguments[2]
  else
    proxy = arguments[0]
    headers = arguments[1]
  end

  headers ||= {} # assign default value

  p "proxy: #{proxy}"
  p "headers: #{headers}"
end
```

```ruby
deprecated_initialize("proxy", "dns", "headers") # old API
#=> "dns is not used anymore deprecation warning"
#=> "proxy: proxy"
#=> "headers: headers"

deprecated_initialize("proxy", "headers") # new API
#=> "proxy: proxy"
#=> "headers: headers"

deprecated_initialize("proxy") # new API + default value
#=> "proxy: proxy"
#=> "headers: {}"


```

It is not 100% (it works differently with explicitly passed `nil` as headers). :thinking: But is that really worth the complexity in here?

Comment (deivid-rodriguez) [reply lib/rubygems/remote_fetcher.rb:80]: I was just curious how you'd handle it, that seems like it would be the way to go yeah, thanks!

I think this is fine to just remove or otherwise just leave the `dns` parameter in there for now since it's actually unrelated from this PR, I only want to stop requiring `resolv`.

Comment (simi) [reply lib/rubygems/remote_fetcher.rb]: :muscle:

**Review by Bangdkai — COMMENTED** [review]
bundler/lib/bundler/rubygems_integration.rb

File: bundler/lib/bundler/fetcher/index.rb [hunk 2]
```diff
@@ -1,7 +1,6 @@
 # frozen_string_literal: true
 
 require_relative "base"
-require "rubygems/remote_fetcher"
```
Comment (Bangdkai) [inline bundler/lib/bundler/fetcher/index.rb:4]: #4640

File: bundler/lib/bundler/rubygems_integration.rb [hunk 3]
```diff
@@ -529,10 +529,9 @@ def download_gem(spec, uri, path)
     end
 
     def gem_remote_fetcher
-      require "resolv"
```
Comment (Bangdkai) [inline bundler/lib/bundler/rubygems_integration.rb:532]: #4640

File: bundler/lib/bundler/rubygems_integration.rb [hunk 4]
```diff
@@ -529,10 +529,9 @@ def download_gem(spec, uri, path)
...
+      require "rubygems/remote_fetcher"
       proxy = configuration[:http_proxy]
-      dns = Resolv::DNS.new
-      Gem::RemoteFetcher.new(proxy, dns)
```
Comment (Bangdkai) [inline bundler/lib/bundler/rubygems_integration.rb:535]: #4640

File: bundler/lib/bundler/rubygems_integration.rb [hunk 5]
```diff
@@ -529,10 +529,9 @@ def download_gem(spec, uri, path)
...
+      Gem::RemoteFetcher.new(proxy)
```
Comment (Bangdkai) [inline bundler/lib/bundler/rubygems_integration.rb:534]: Duplicate of #

Comment (Bangdkai) [inline bundler/lib/bundler/rubygems_integration.rb:534]: Duplicate of #

File: bundler/lib/bundler/rubygems_integration.rb [hunk 6]
```diff
@@ -529,10 +529,9 @@ def download_gem(spec, uri, path)
     end
 
     def gem_remote_fetcher
-      require "resolv"
+      require "rubygems/remote_fetcher"
       proxy = configuration[:http_proxy]
-      dns = Resolv::DNS.new
```
Comment (Bangdkai) [inline bundler/lib/bundler/rubygems_integration.rb:534]: #4640

File: bundler/lib/bundler/rubygems_integration.rb (hunk 4 above)
Comment (Bangdkai) [inline bundler/lib/bundler/rubygems_integration.rb:535]: #4640

File: bundler/spec/bundler/fetcher/index_spec.rb [hunk 7]
```diff
@@ -1,5 +1,7 @@
 # frozen_string_literal: true
 
+require "rubygems/remote_fetcher"
+
```
Comment (Bangdkai) [inline bundler/spec/bundler/fetcher/index_spec.rb:4]: Duplicate of #

**Review by Bangdkai — COMMENTED** [review]
@deivid-rodriguez
